src/labs/lit-extended.ts, src/test/labs/lit-extended_test.ts, test/index.html
Fixes #4 
Uncovered another issue filed as #6
=> Add ommitted line in extended. Add test suite.

src/lit-html.ts, src/test/lit-html_test.ts
Currently the only optimization is to prefer a simple list walking loop over `Range`. @sorvell to provide the performance improvement numbers.
=> Optimizations

src/lit-html.ts
* break into individual functions depending on type
* improves readability
* moves function args to be monomorphic
* improved some private benchmarks by about 40%
=> refactor NodePart::setValue

src/lit-html.ts
This adds `SinglePart` and `MultiPart` interfaces, and `MultiPart#setValue(values: any[], index: number)`
This just reduces list allocations for AttributeParts. Not a big change in code or perf.
=> Add a new Part.setValue() variation

.gitignore, .travis.yml, package-lock.json, package.json, src/lit-html.ts, test/index.html
=> Travis CI integration

README.md, api.md, src/lib/lit-extended.ts, src/lib/repeat.ts, src/lib/until.ts, src/lit-html.ts, src/test/lib/repeat_test.ts, src/test/lit-html_test.ts
=> Add the directive() function, don’t treat function values as directives by default

src/lib/lit-extended.ts, src/test/lib/lit-extended_test.ts
=> Fix PropertyPart bug

package-lock.json, src/lib/lit-extended.ts, src/test/lib/lit-extended_test.ts
=> Fix removal of event listeners. Support handleEvent methods for listeners

src/lib/repeat.ts, src/test/lib/repeat_test.ts
=> Fix double accounting of old parts.

src/lib/repeat.ts, src/lit-html.ts, src/test/lib/repeat_test.ts, src/test/lit-html_test.ts
=> Fix iterables not clearing previous values when updating with smaller lists

package.json, src/lit-html.ts, src/test/lit-html_test.ts
=> Fix for partial tables.

README.md
=> Add link to the Justin talk

src/lit-html.ts, src/test/lit-html_test.ts
=> Only remove whitespace between, or at the start or end of, elements.

src/lit-html.ts, src/test/lit-html_test.ts
=> Fix bug with templates with comments

package-lock.json, package.json, test/index.html
This removes the need for the bower_components symlink hack.
=> Upgrade WCT to 6.3.0

.travis.yml, package.json, src/lit-html.ts, src/test/lib/until_test.ts, src/test/lit-html_test.ts, test/index.html
=> Enable automated testing on Firefox, Safari, and Edge

package.json, test/index.html
With this tests at least run on IE11 :p
```
Test Results
54 failing tests
20 passing tests
Evaluated 73 tests in 520ms.
```
once this is done I guess there is a need for some follow up PRs for IE11
=> fix: add polyfills so test can run on IE11

src/lit-html.ts
closes #128
current workaround
http://jsbin.com/nahoyatoxe/edit?html,output
=> fix(NodePart): reuse same Node elements

src/lit-html.ts, src/test/lit-html_test.ts
=> Fix bindings in styles

src/lib/lit-extended.ts, src/lit-html.ts
Oh, and make `extendedPartCallback` a bit smaller.
=> Share AttributePart/EventPart interpolation code

src/lit-html.ts
I'll do an inline review of the changes.
=> Various improvements

src/lit-html.ts
We have this reimplemented three times, twice here and once (soon) in the repeat directive.
Should we create a utils module? This probably shouldn't be exported with the main binary, but it'll need to be imported in multiple files.
=> Add removeNodes helper

src/lit-html.ts, src/test/lit-html_test.ts
=> Fix bug when expressions directly followed an element

CHANGELOG.md, src/lib/repeat.ts, src/lit-html.ts, src/test/lit-html_test.ts
=>  Allow all valid HTML attribute names.

src/lib/repeat.ts, src/lit-html.ts, src/test/lib/repeat_test.ts
=> Fix infinite loop with repeated repeat node

CHANGELOG.md, README.md, src/lib/async-append.ts, src/lib/async-replace.ts, src/lib/until.ts, src/lit-html.ts, src/test/lib/async-append_test.ts, src/test/lib/async-replace_test.ts, src/test/lib/deferred.ts, src/test/lib/test-async-iterable.ts, src/test/lib/until_test.ts, test/index.html, tsconfig.json
This also updates the directive API, so that directives no longer return values, but have to call the part.setValue() API.
Fixes #15
=> Add asyncAppend and asyncReplace directives

src/lit-html.ts, src/test/lib/async-append_test.ts, src/test/lib/async-replace_test.ts, src/test/lib/repeat_test.ts, src/test/lib/unsafe-html_test.ts, src/test/lib/until_test.ts, src/test/lit-html_test.ts
This is a rollback of the IE compatibility PR (#202)
With this PR the master branch should be in a stable and hopefully releasable state.
I applaud the effort going into IE compatibility, but I think having a stable release is a more pressing issue at this time. I am looking forward to seeing PR (#229) and other IE fixes land soon.
=> Revert comments for markers

README.md
`asyncAppend` and `asyncReplace` added in [0.8.0](https://github.com/Polymer/lit-html/blob/master/CHANGELOG.md#080---2018-01-12)
=> Remove note about Future Work: Async Iterables

src/lib/lit-extended.ts, src/lit-html.ts
This ports the dirty checking code from NodePart into AttributePart
and PropertyPart as well.
Fixes #199
=> Add previous value optimizations to AttributePart and PropertyPart

CHANGELOG.md, package-lock.json, package.json, src/lib/lit-extended.ts, src/lib/shady-render.ts, src/lit-html.ts, src/test/lib/lit-extended_test.ts, src/test/lib/shady-render_test.ts, src/test/lit-html_test.ts, test/index.html, test/shady.html
=> ShadyCSS Support

docs/index.html
I believe this should be "ever" not "every".
=> Fix 'every' typo

src/lib/async-append.ts
:wave:
Awesome project! Was reading through the source and found this little correction to make.
Thanks!
=> Let's -> Lets

src/lib/async-append.ts, src/lib/async-replace.ts, src/lib/repeat.ts, src/lib/unsafe-html.ts, src/lib/until.ts, src/lit-html.ts
Fixes #224 
The patch is not as small as I intended bc I had to propagate the changes to the available directives.
=> Better type for directives

README.md
Consistently sort browsers and add the minimum supported Edge version in the readme.
=> Clean up browser list in Readme

src/lib/shady-render.ts, src/lit-html.ts, src/test/lib/shady-render_test.ts, src/test/lit-html_test.ts, test/index.html
=> Allow for bindings in <template> elements.

src/test/lit-html_test.ts
=> Add test for dirty checking Node values.

src/lit-html.ts, src/test/lit-html_test.ts
=> Handle forms as Node instead of iterable

src/core.ts
https://github.com/Polymer/lit-html/pull/416#discussion_r205924886
It's the same size, but less work. 😉
=> Avoid forward isTextBinding search

src/test/core_test.ts
This fixes the labels of two tests that are mixed up.
=> Fix test labels

docs-src/guide/02-writing-templates.md, src/directives/if-defined.ts, src/test/directives/if-defined_test.ts, test/index.html
For AttributeParts, sets the attribute if the value is defined and removes the attribute if the value is undefined.
For other part types, this directive is a no-op.
Example:
```js
const render = () => html`
<div class=${ifDefined(className)}></div>
`;
```
=> Add ifDefined() directive

src/lib/template.ts, src/test/lib/render_test.ts
=>  Don’t break templates when HTML comments have bindings in them

src/lib/parts.ts, src/test/lib/render_test.ts
=> Handle Symbol values

src/lib/template-result.ts, src/lib/template.ts, src/test/lib/render_test.ts, src/test/lib/template-result_test.ts
=> Fix style attribute bindings in IE

src/lib/render.ts, src/lib/shady-render.ts
Fixes #394
This is also handled by #445 - not sure if you want to pursue that PR, but this fixes the issue until then.
=> Use WeakMap for templateInstances

src/lib/shady-render.ts, src/test/lib/incompatible-shady-render_test.ts, src/test/lib/shady-render_test.ts, test/incompatible-shady.html
This implements a cache for the ShadyCSS version check, which improves ShadyCSS render performance.
=> Cache ShadyCSS version (Fixes #476)

.travis.yml
Add Chrome 41, Edge 17, and Safari 11
=> Update sauce browser testing list

src/lib/parts.ts
This will set the values in templates before elements are upgraded.
=> Update properties before upgrading custom elements (Fixes #453)

src/directives/async-replace.ts, src/test/directives/async-replace_test.ts
It solves the problem commented on the issue Polymer/lit-html#484
=> Add AsyncIterator tracking on async-replace directive

docs-src/guide/index.md
Fixed a typo in markdown source file.
=> fixed a typo in docs-src / guide / index.md

README.md
The [awesome list](https://github.com/web-padawan/awesome-lit-html) for lit-html has been approved in sindresorhus/awesome#1357 
Please consider adding this badge, so as we could help more people with blog posts, tools etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/polymer/lit-html/535)
=> Add awesome-lit-html badge [skip ci]

docs/css/main.css
=> Remove lighter font-weight styles for readability

src/directives/repeat.ts
=> Fix KeyFn and ItemTemplate types

package-lock.json
Targeted package-lock updates to get wct-local@2.1.3
=> Updated package-lock.json to get latest wct-local which fixes issue testing Firefox 63.

src/directives/style-map.ts, src/test/directives/style-map_test.ts
=> Handle CSS variables in styleMap

src/lib/parts.ts
=> Only call getOptions() in EventPart when we add an event listener

demo/clock/clock.js, demo/clock/index.html
=> Update demo to load polyfills and center the clock.

CHANGELOG.md, src/directives/cache.ts, src/lib/shady-render.ts, src/lib/template-factory.ts, src/lib/template-instance.ts, src/test/directives/cache_test.ts, test/index.html
=> Add cache() directive

src/directives/guard.ts, src/test/directives/guard_test.ts
=> Update guard to handle multiple checked values and undefined

src/lib/modify-template.ts, src/lib/parts.ts, src/lib/template.ts, src/polyfills/template_polyfill.ts
Since we're not running a minifier.
=> Use known numeric constants

src/lib/shady-render.ts
This is breaking API doc generation currently.
=> Fix JSDoc comment.

src/directives/until.ts, src/test/directives/until_test.ts
=> Fix until() directive to not overwrite high-priority Promises when lower-priority values change.

docs/index.md
One less line in the code block, looks fine on desktop and mobile
=> Remove line break in comments

docs/_guide/01-getting-started.md
A couple typo fixes and phrase rewords.
=> [docs] Improve text, fix typos in Getting Started

docs/guide.md
Add a link to Getting Started from the Introduction.
Looking for suggestions on the wording.
=> Link to Getting Started from Introduction

docs/_layouts/post.html, docs/css/main.css, docs/guide.md
=> Highlight active link in side nav

docs/_layouts/post.html
=> Remove pre-release disclaimers

docs/_guide/01-getting-started.md
=> Open online editors links in new tab

src/test/lib/render_test.ts
=> Add another test for comments with bindings

src/test/lib/render_test.ts
=> Add tests for bindings in tag-name position

src/lit-html.ts, src/test/lit-html_test.ts
=>  Add version global

docs/_guide/01-getting-started.md, docs/_guide/06-concepts.md, docs/_guide/07-tools.md
Staged at https://staging-dot-polymer-lit-html.appspot.com
Fixes #744
=> Add tools section.

docs/css/main.css
Similar to https://github.com/Polymer/lit-element/pull/569. Making PR for record.
=> Sync stylesheet; Place anchors below header

docs/_guide/05-template-reference.md
I copy and pasted it and didn't notice the spelling mistake at first, made me upgrade to the latest lit-element from @polymer/lit-element 👍 😄
=> Update spelling mistake in import

src/directives/until.ts
Gets rid of a few useless if checks by using an infinity value so we don't have to explicitly check for `undefined`. Also guards against an out-of-bound array access on `previousValues`.
I took a bit of liberty with using a 2<sup>31</sup>-1 as "infinity". If you want, we can use the real `Infinity` value.
=> Cleanup until directive

src/directives/class-map.ts
- The `toggle` polyfill was broken (it didn't toggle 😆). And it was just unnecessary.
- `classMapStatics` is unnecessary, we can determine if this is the first render by just checking `classMapCache`.
- Use variables for repeated property accesses to save some space
=> Cleanup the classMap directive

src/polyfills/template_polyfill.ts
=> Use tagName when appropriate

src/directives/repeat.ts
It was annoying me too much to read it this way.
=> Reformat the repeat directive's comment

src/lib/template-instance.ts, src/lib/template.ts, src/test/lib/render_test.ts
On the heels of #825, this unrolls our recursive template processor into a stack based one.
=>  Use a stack to create walk nested templates

src/lib/template-instance.ts, src/test/lib/render_test.ts
Safari doesn't yet implement `CustomElementRegistry#upgrade`
=> Revert the change to template instance clone/upgrade ordering to fix Safari

src/directives/cache.ts, src/directives/class-map.ts, src/directives/style-map.ts, src/directives/unsafe-html.ts, src/lib/default-template-processor.ts, src/lib/dom.ts, src/lib/part.ts, src/lib/parts.ts, src/lib/render-options.ts, src/lib/template-factory.ts, src/lib/template-instance.ts, src/lib/template-processor.ts, src/lib/template-result.ts, src/lib/template.ts
Conceptually with the no-any branch, but split out for clarity, and because that branch had gotten big enough.
=> Mark fields as readonly where possible. Likewise use ReadonlyArray.

src/lib/template-result.ts, src/test/lib/render_test.ts
Fixes #881 
This is a more incremental fix than #847 or #863. Those may be better in the long term, but we want to measure the perf and size impacts of those first.
=> Fix bindings in comments

src/lib/part.ts
=> Remove typing from noChange

src/lib/template.ts
Yet another minor lint warning that keeps bugging me
=> Typo: fix common misspelling

src/lib/parts.ts
Move setting this.value into the value changed branch for boolean attributes
=> set this.value conditionally

docs/api/classes/lit_html.attributepart.html, docs/api/classes/lit_html.propertypart.html, src/lib/default-template-processor.ts, src/lib/parts.ts
Hi everyone.
I hope it's ok to submit this micro pull request without discussing it first.
I came across this small discrepancy when I reviewed the code for my Reverse Engineering video and thought that, this is strange is there a word "comit"?
I'm not a native speaker so there might be one that I'm not aware of.
I did a search through the code a manually added an extra m every place where I found this word.
If you feel that this pull request is bad or that I didn't follow the right process then just see this as information and close the pull request. No hard feelings.
Thanks for a great library and keep up the great work.
Best regards
Daniel
=> Change some instances of "comit" to "commit".

docs/_guide/02-writing-templates.md
Sentence was reading weird previously, fixed up the wording.
=> Clarify DOM inconsistency for falsy values

src/test/lib/render_test.ts
Edge renders attributes in differing order.
=> Fix test in Edge

docs/_guide/06-template-reference.md
Fixes #804, see issue for details
=> Remove outdated classMap warning

src/lib/dom.ts, src/lib/modify-template.ts, src/lib/template-instance.ts, src/lib/template.ts
Note, this is a PR into your [`walkers`](https://github.com/Polymer/lit-html/tree/walkers) branch, not master. We'll still need to merge https://github.com/Polymer/lit-html/pull/917 after this.
=> Use a single tree walker, ensure it's reset

CHANGELOG.md
I forgot to do this in that PR.
=> Update CHANGELOG.md for PR #910.

package-lock.json, package.json, src/lib/shady-render.ts, src/test/lib/modify-template_test.ts
A few typing fixes needed for TypeScript 3.5
=> Bump TypeScript and tach/benchmarks packages

src/test/directives/style-map_test.ts, src/test/lib/shady-render-apply_test.ts
Not sure why these aren’t causing CI to fail
=> Fix lint warnings

docs/_guide/06-template-reference.md
=> Remove warning that directives may change before 1.0 release

docs/_guide/06-template-reference.md
Tweaks to classMap, styleMap documentation.
Staged here: https://style-map-fix-dot-polymer-lit-html.appspot.com/guide/template-reference#classmap
=> Update notes on classMap, styleMap usage.

CHANGELOG.md, src/directives/class-map.ts, src/directives/style-map.ts
=> Class style map

package-lock.json, package.json, src/test/lib/trusted-types_test.ts, test/index.html
First thing I'm trying, don't run trusted type tests in ancient browsers.
=> Fix the build

docs/guide.md
Fixing a merge issue in #1043 that left us with *two* asides, alas.
=> Remove duplicate aside. Sigh.

README.md
Same as Polymer/lit-element#830
=> Add Slack badge to README for discoverability

src/directives/unsafe-svg.ts, src/test/directives/unsafe-svg_test.ts
Trying the tests I wrote to see if they pass...
=> Replace unsafeSVG tests

CHANGELOG.md, src/directives/if-defined.ts, src/test/directives/if-defined_test.ts
=> ifDefined: Only set attributes when values change

.travis.yml, package-lock.json, package.json, wct.conf.json
=> Fix Chrome 80 test timeouts.

CHANGELOG.md, src/directives/if-defined.ts, src/directives/live.ts, src/lib/parts.ts, src/test/directives/if-defined_test.ts, src/test/directives/live_test.ts, src/test/lib/render_test.ts, src/test/lib/trusted-types_test.ts
This reverts commit 6eabb313f4ad2ebeb18c737be0b922081fbf5421.
Addresses #1096
=> Revert "Support namespaces attributes (#1072)"

docs/_includes/release-notes.html, docs/guide/10-release-notes.md, docs/guide/release-notes/1.2.0.md, docs/guide/release-notes/release-notes.json, package-lock.json
=> Add 1.2.0 release notes

CHANGELOG.md, docs/_includes/release-notes.html, docs/guide/10-release-notes.md, docs/guide/release-notes/1.2.0.md, docs/guide/release-notes/release-notes.json, package-lock.json, package.json, src/directives/class-map.ts, src/test/directives/class-map_test.ts, src/test/lib/shady-render_test.ts
Preparing for a google3 import.
Note I also enable branch protection for the security branch, requiring reviewed pull requests and disallowing forced pushes.
=> Merge master into security

src/directives/class-map.ts
Not sure why these weren't caught on CI. Need to look into that.
=> Fix lint errors

CHANGELOG.md, package.json, src/lit-html.ts
=> Prepare 1.2.0-pre.1 release

.github/workflows/test_old_compile.yml, .gitignore, CHANGELOG.md, package-lock.json, package.json
Related to https://github.com/Polymer/lit-element/issues/935
Haven't heard anything about this being a problem for lit-html, but better to be ahead of any issues.
=> Use downlevel-dts, test compile in TS 3.4

package-lock.json, package.json
=> Update lint dependencies

docs/guide/05-creating-directives.md
=> Update a broken link in the documentation. #1137

package-lock.json, package.json, src/test/directives/unsafe-html_test.ts, src/test/lib/modify-template_test.ts, src/test/lib/shady-render-apply_test.ts, src/test/lib/shady-render-scoping-shim_test.ts, src/test/lib/trusted-types_test.ts, src/test/polyfills/template_polyfill_test.ts, src/test/test-utils/security.ts, test/incompatible-shady.html, test/index.html, test/no-template.html, test/shady-apply.html, test/shady-scoping-shim.html, test/shady.html, test/shady_no-wc.html, test/trusted-types.html
Builds on top of https://github.com/Polymer/lit-html/pull/1153
Needs https://github.com/Polymer/tools/pull/3503 to be released before it will work
=> Trusted types tests

src/lib/hydrate.ts, src/lib/parts.ts
=> Hydrate iterables

src/lib/hydrate.ts
Partly closes https://github.com/PolymerLabs/lit-ssr/issues/17
=> Support event parts

src/lib/hydrate.ts
Integration tests added in https://github.com/PolymerLabs/lit-ssr/pull/39.
=> [hydration] Add noChange handling & align w/NodePart:commit

src/lib/template.ts, src/test/lib/template_test.ts
Associated lit-ssr PR: https://github.com/PolymerLabs/lit-ssr/pull/52
=> Ensure client template has end marker to match index counting on server

docs/css/main.css, docs/index.md
Staged: https://20200603t165446-dot-polymer-lit-html.uk.r.appspot.com
=> Add BLM banner

src/lib/shady-render.ts
=> Export shadyTemplateFactory

packages/lit-html/package-lock.json, packages/lit-html/package.json, packages/lit-html/rollup.config.js, packages/lit-html/src/lib/lit-html.ts
This sets up a build just to check the bundled size.
Eventually we'll change the setup to publish the bundle.
=> [lit-next] Add Rollup, Terser, and checksize script

packages/lit-element/CHANGELOG.md, packages/lit-element/src/lib/updating-element.ts, packages/lit-element/src/test/updating-element_test.ts
Non-breaking fixes for minor issues.
* fixes https://github.com/Polymer/lit-element/issues/722
* fixes https://github.com/Polymer/lit-element/issues/890
=> [lit-element] Address minor issues with LitElement

packages/lit-html/src/lib/lit-html.ts
Re: https://github.com/Polymer/lit-html/pull/1215#pullrequestreview-480472253
=> [lit-html] Fix two logical assignment bugs

packages/lit-html/rollup.config.js, packages/lit-html/src/directives/guard.ts, packages/lit-html/src/test/directives/guard_test.ts
Tests are failing until #1250 is merged due to lack of array support.
=> [lit-html] Add guard() directive

packages/lit-element/rollup.config.js
Fixes build for individual decorators.
=> Fix LitElement build

packages/tests/package-lock.json, packages/tests/package.json, packages/tests/web-test-runner.config.js
I'm investigating different issues in the saucelabs launcher with different projects, and making improvements. Making a PR of the changes I made so far, feel free to merge or close it.
The test failures on chrome and safari are all related to styling, so it likely has to do with the way we run tests concurrently. Setting a concurrency of 1 makes them pass at least, though it's slower. I'm looking into what we can do here to either fix the issue or make it faster.
This also updates the test runner dependencies to a version which handles logging in tests run with selenium, so that errors in saucelabs are easier to debug. For IE11 and Edge there are actionable errors.
=> Make tests pass in saucelabs

packages/lit-element/src/test/updating-element_test.ts
Warning by ESLint.
Extracted from https://github.com/Polymer/lit-html/pull/1297
=> [lit-next] Update string types

packages/benchmarks/lit-html/kitchen-sink/index.ts, packages/lit-element/src/lib/updating-element.ts, packages/lit-element/src/test/lit-element_styling_test.ts, packages/lit-html/src/directives/cache.ts, packages/lit-html/src/directives/repeat.ts, packages/lit-html/src/test/lit-html_test.ts
Warning by ESLint.
Extracted from https://github.com/Polymer/lit-html/pull/1297
=> [lit-next] Replace some let with const

packages/lit-html/src/test/platform-support/lit-html-apply_html-test.ts, packages/lit-html/src/test/platform-support/lit-html_html-test.ts
One minor improve to remove the file disabled rules
Ping to @aomarks
=> [lit-next] Update file disabled rules to inline disabled

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts, rollup-common.js
See #750 for details of this API.
This is a basic implementation. More of it can be probably be removed from the release build with some more terser cleverness.
=> Port sanitization hooks to lit-next. 

packages/localize/CHANGELOG.md, packages/localize/examples/runtime/package.json, packages/localize/examples/transform/package.json, packages/localize/package.json
=> [localize] Add missing localized-element.js and config.schema.json files

packages/lit-html/src/lit-html.ts
=> [lit-html] Use Element#getAttributeNames() instead of Element#attributes

packages/benchmarks/lit-html/kitchen-sink/index.ts, packages/lit-element/src/lit-element.ts, packages/lit-html/CHANGELOG.md, packages/lit-html/README.md, packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/directive.ts, packages/lit-html/src/directives/cache.ts, packages/lit-html/src/directives/class-map.ts, packages/lit-html/src/directives/guard.ts, packages/lit-html/src/directives/live.ts, packages/lit-html/src/directives/render-light.ts, packages/lit-html/src/directives/repeat.ts, packages/lit-html/src/directives/style-map.ts, packages/lit-html/src/directives/template-content.ts, packages/lit-html/src/directives/unsafe-html.ts, packages/lit-html/src/disconnectable-directive.ts, packages/lit-html/src/hydrate.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/platform-support.ts, packages/lit-html/src/test/directive-helpers_test.ts, packages/lit-html/src/test/directives/class-map_test.ts, packages/lit-html/src/test/directives/if-defined_test.ts, packages/lit-html/src/test/directives/style-map_test.ts, packages/lit-html/src/test/directives/until_test.ts, packages/lit-html/src/test/lit-html_test.ts, packages/lit-html/src/test/platform-support/lit-html-scoping-shim_html-test.ts, packages/lit-ssr/package-lock.json, packages/lit-ssr/src/lib/render-lit-html.ts, packages/lit-ssr/src/test/integration/tests/basic.ts, rollup-common.js
Also renames several methods, properties, and constants related to NodeParts.
=> [lit-html] Rename NodePart to ChildPart

packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/directives/cache.ts, packages/lit-html/src/directives/live.ts, packages/lit-html/src/directives/repeat.ts, packages/lit-html/src/disconnectable-directive.ts, packages/lit-html/src/hydrate.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/platform-support.ts, rollup-common.js
`getPartValue()` → `getCommittedValue()`
`setPartValue()` → `setCommittedValue()`
`Part._$value`  → `Part._$committedValue`
=> Rename getPartValue to getCommittedValue, etc.

packages/lit-element/README.md, packages/lit-html/README.md, packages/reactive-element/README.md
* remove examples from ReactiveElement
* remove out of date known limitations
* include examples for loading polyfill-support
=> [lit-next] Update Lit/ReactiveElement readmes

lit-next.code-workspace, packages/lit-element/src/polyfill-support.ts, packages/lit-element/tsconfig.polyfill-support.json, packages/lit-html/package.json, packages/lit-html/src/polyfill-support.ts, packages/lit-html/tsconfig.json, packages/lit-html/tsconfig.polyfill-support.json, packages/lit-starter-js/test/my-element_test.js, packages/lit-starter-js/web-test-runner.config.js, packages/lit-starter-ts/src/test/my-element_test.ts, packages/lit-starter-ts/web-test-runner.config.js, packages/lit/package.json, packages/lit/tsconfig.json, packages/lit/tsconfig.polyfill-support.json, packages/reactive-element/src/polyfill-support.ts, packages/reactive-element/tsconfig.json, packages/reactive-element/tsconfig.polyfill-support.json, rollup-common.js
Fixes https://github.com/Polymer/lit-html/issues/1564
=> [lit-next] Add tsconfig for dowleveling polyfill-support to ES5

packages/tests/package-lock.json, packages/tests/package.json
Fixes:
```
browserType.launch: No executable path is specified. Pass "executablePath" option directly. 
```
=> Update test dependencies to fix test running

packages/tests/package-lock.json, packages/tests/package.json
Pull in fix https://github.com/modernweb-dev/web/pull/1283, which aims to help IE11 flakiness
=> [tests] Update @web/test-runner

packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/directives/cache.ts, packages/lit-html/src/directives/live.ts, packages/lit-html/src/directives/repeat.ts
=> fix: typo in exported fn names comitted -> committed

packages/lit-html/src/directives/ref.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/directives/ref_test.ts
=> [lit-html]Call ref callback against options.host. Fixes #1628

packages/lit-ssr/src/demo/app-client.ts
Import order is important or LitElement on the client is not patched properly with hydration support.
=> fix: change ssr demo to hydrate in place properly

packages/lit-html/src/directives/cache.ts, packages/lit-html/src/test/directives/cache_test.ts
=> [lit-html] Fix issue where 2nd render of same value cleared value storage.

packages/reactive-element/CHANGELOG.md, packages/reactive-element/src/reactive-controller.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element-controllers_test.ts
=> [reactive-element] Calls `hostUpdated` before host's `firstUpdated`

packages/localize-tools/CHANGELOG.md, packages/localize-tools/package-lock.json, packages/localize-tools/package.json, packages/localize-tools/src/cli.ts, packages/localize-tools/src/index.ts, packages/localize/CHANGELOG.md, packages/localize/README.md, packages/localize/examples/runtime/README.md, packages/localize/examples/runtime/package-lock.json, packages/localize/examples/runtime/package.json, packages/localize/examples/runtime/src/locale-codes.ts, packages/localize/examples/runtime/src/locales/es-419.ts, packages/localize/examples/runtime/src/locales/zh_CN.ts, packages/localize/examples/transform/README.md, packages/localize/examples/transform/package-lock.json, packages/localize/examples/transform/package.json, packages/localize/examples/transform/rollup.config.mjs, packages/localize/package-lock.json, packages/localize/package.json
Also localization examples updated to new packages.
If you want to import a module from a module in your rollup config, you have to use `.mjs` extension (https://rollupjs.org/guide/en/#using-untranspiled-config-files).
=> Release @lit/localize and @lit/localize-tools

packages/lit-element/README.md, packages/lit-html/README.md, packages/reactive-element/README.md
=> [lit-next] Fix development mode typos

packages/localize-tools/CHANGELOG.md, packages/localize-tools/config.schema.json, packages/localize-tools/package-lock.json, packages/localize-tools/package.json, packages/localize-tools/src/program-analysis.ts
In particular for `xmldom`, which has an open security report.
=> Bump localize-tools dependencies

packages/lit-element/src/lit-element.ts, packages/reactive-element/src/reactive-element.ts
For creating sections on the docs site.
=> Add category annotations to LitElement and ReactiveElement

packages/lit-html/src/static.ts, packages/lit-html/src/test/static_test.ts
Unfortunately, we can't use `static` as a function name due to being a reserved keyword. After a short bikeshed, we chose `literal`.
Fixes #1713
=> Add `literal` tag to static module.

packages/localize-tools/CHANGELOG.md, packages/localize-tools/package.json, packages/localize-tools/src/formatters/xliff.ts, packages/localize-tools/testdata/extract-xliff/goldens/data/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff/goldens/data/xliff/zh_CN.xlf, packages/localize/README.md
Fixes https://github.com/Polymer/lit-html/issues/1721
Fixes https://github.com/Polymer/lit-html/issues/1720
=> Fix XLIFF header and config schema link

.eslintrc.json, packages/labs/ssr/package.json
=> Simplify ESLint config

packages/labs/motion/LICENSE, packages/labs/motion/package.json, packages/labs/scoped-registry-mixin/LICENSE, packages/labs/scoped-registry-mixin/package.json
Using the same format as @aomarks changed a few weeks ago.
=> Update motion & scoped-registry authors

README.md
Updating links to the new repository
=> Updating links to the new repository

packages/labs/react/CHANGELOG.md, packages/labs/react/src/test/use-controller_test.ts, packages/labs/react/src/use-controller.ts
=> [labs/react] Fix #1815: useController/requestUpdate bug

packages/lit-html/CHANGELOG.md, packages/lit-html/src/directives/ref.ts
This missing export was reported in Slack.
=> [lit-html] Export the Ref interface

packages/labs/ssr/package-lock.json, packages/labs/ssr/package.json, packages/labs/ssr/src/test/lit/render-lit_test.ts, packages/localize-tools/package-lock.json, packages/localize-tools/package.json, packages/localize-tools/src/tests/analysis.unit.test.ts, packages/localize-tools/src/tests/e2e/e2e-goldens-test.ts, packages/localize-tools/src/tests/transform.unit.test.ts
Fixes #1693 
I hope you don't mind me randomly trying to tackle this. If you already did it, or did it a better way, feel free to close this. I just wanted to understand more of the repo and give uvu a try meanwhile.
I also don't fully understand how you've been making lockfiles with lerna, so its possible the ones i generated are wrong. would be worth a look as they introduced dependencies for other packages in the monorepo which weren't there before.
i also don't know if you were relying on TAP output somewhere, as that will have been lost (uvu has no tap support).
=> [localize-tools, ssr] move tests to using uvu

README.md
update lit starter location to lit repo
=> [starter-kits] lit starter new location

packages/reactive-element/src/css-tag.ts, rollup-common.js
=> [reactive-element] Don't use instanceof to check for CSSResults

packages/benchmarks/package-lock.json, packages/benchmarks/package.json, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts, rollup-common.js
This matches a change I'm adding to 1.x internally to not clear the container except when this flag is present.
=> [lit-html] Add flag to clear render container

packages/labs/motion/CHANGELOG.md, packages/labs/motion/package.json, packages/labs/react/CHANGELOG.md, packages/labs/react/package.json, packages/labs/ssr-client/CHANGELOG.md, packages/labs/ssr-client/package.json, packages/labs/task/CHANGELOG.md, packages/labs/task/package.json
=> [labs] Include `development` folders in @lit-labs packages

packages/labs/motion/package.json, packages/labs/react/package.json, packages/labs/scoped-registry-mixin/package.json, packages/labs/ssr-client/package.json, packages/labs/task/package.json, packages/lit-element/package.json, packages/lit-html/package.json, packages/lit/package.json, packages/localize/package.json, packages/reactive-element/package.json
=> [all] Don't publish src/ to npm

.changeset/smart-hats-breathe.md, packages/lit-html/src/polyfill-support.ts, packages/lit-html/src/test/polyfill-support/lit-html-apply_html-test.ts
=> [lit-html] Handle case where ShadyCSS removes empty style.

packages/reactive-element/src/reactive-element.ts
We need to add something similar to the lifecycle docs for lit.dev too.
=> [reactive-element] Add addInitializer() docs

packages/reactive-element/src/reactive-element.ts
A few small things I noticed in the JSDoc comments for ReactiveElement.
=> JSDoc copyedits

packages/labs/motion/README.md
Minor edits for consistency following the renaming.
=> copyedit README

.changeset/changelog-lit.cjs, .changeset/config.json, package-lock.json, package.json
Part of #2178 
As part of testing this I noticed that we're generating changelogs for the localize examples. We need to figure out how to exclude those for full automation.
=> Add custom changelog generator function

docs/css/main.css
same treatment as lit/lit-element#1211
=> docs: Make version banner more apparent for lit-html 1.x

.changeset/tiny-hornets-visit.md, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
added tests to lit-ssr that check that reflected properties are actually rendering correctly
related #2305
=> test(ssr): add element reflecting prop tests

.changeset/silent-badgers-own.md, packages/lit/package.json
=> Fix choose directive default export path

.changeset/clever-fans-decide.md, packages/reactive-element/src/reactive-element.ts
=> Make `getPropertyOptions` public

.changeset/funny-lemons-kiss.md, packages/benchmarks/CHANGELOG.md, packages/labs/motion/README.md, packages/labs/observers/CHANGELOG.md, packages/localize-tools/CHANGELOG.md, packages/localize/CHANGELOG.md
=> Format markdown files with prettier

.changeset/eleven-paws-hear.md, packages/lit-html/src/async-directive.ts
=> [comments]: correct typos

.changeset/yellow-meals-exercise.md, packages/labs/motion/README.md, packages/labs/observers/README.md, packages/labs/react/README.md, packages/labs/ssr-client/README.md, packages/labs/task/README.md, packages/lit-element/README.md, packages/lit-html/README.md, packages/lit/README.md, packages/reactive-element/README.md
correct the link path of CONTRIBUTING.md
=> [docs]: correct the link path of CONTRIBUTING.md

.eslintignore, .github/workflows/release.yaml, .prettierignore, packages/lit/.gitignore, packages/lit/rollup.config.js
This PR stops UMD bundles from being generated and pushed to lit/bundles.
=> Stop generating UMD bundles.

.github/workflows/release.yaml
This makes the name infixes consistent between the two bundles.
=> [lit] Rename the bundles.

.changeset/perfect-pens-itch.md
Adding `lit` to changeset since core libraries are getting updated
=> Update changeset for lit release

.changeset/hip-toys-begin.md, packages/labs/ssr/src/lib/element-renderer.ts, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
closes https://github.com/lit/lit/issues/2572
=> fix(ssr): handle undefined/null element attribute values

CONTRIBUTING.md
Remove duplicated `prefixed` in CONTRIBUTING.md
=> Remove duplicated `prefixed` in CONTRIBUTING.md

.changeset/wise-cheetahs-join.md, packages/labs/analyzer/src/lib/analyzer.ts, packages/labs/analyzer/src/lib/model.ts, packages/labs/analyzer/src/lib/paths.ts, packages/labs/analyzer/src/test/analyzer_test.ts, packages/labs/analyzer/test-files/basic-elements/src/not-lit.ts
=> Add minimal class declaration gathering

package-lock.json, package.json
This way if multiple unrelated changes come in that start using wireit, they're less likely to conflict.
=> Install wireit, but don't yet use it

packages/labs/cli/package.json
So that changesets doesn't auto publish it.
=> Make @lit/cli private for now

.changeset/metal-swans-decide.md, packages/labs/context/package.json
Forgot to include the libs folder into the package.json files list!
=> [labs/context] Fixes #2811 by including libs into package files

packages/labs/context/src/lib/value-notifier.ts
if just force, no need to check value change.
=> chore: logic clearing and improve efficency

CONTRIBUTING.md
Just change `lit-html` to `lit` in CONTRIBUTING.md
=> chore(contributing): change lit-html to lit

packages/labs/analyzer/package-lock.json, packages/labs/cli/package-lock.json, packages/labs/gen-wrapper-react/package.json, packages/labs/test-projects/test-element-a/package-lock.json
Ran lerna bootstrap to install symlinks and update package locks.
gen-wrapper-react was not building for me without this. @kevinpschaaf  any idea why this didn't fail CI?
=> [labs/gen-wrapper-react] Fix missing dependency

.github/workflows/tests.yml
This PR combines the `changeset` and `lint` workflows into one workflow `changeset-lint`.
These workflows are similar enough to combine :)
=> [workflows] combine changeset and lint workflows

.changeset/rich-monkeys-flow.md, packages/labs/ssr/src/lib/render-lit-html.ts, packages/labs/ssr/src/test/integration/server/server.ts, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/labs/ssr/src/test/integration/tests/ssr-test.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts
=> [ssr] Add option to defer hydration on top level custom element

.changeset/tough-gorillas-study.md, packages/labs/react/package.json
Fixes https://github.com/lit/lit/issues/2948
=> [labs/react] Fix use-controller.js not being exported from package.json

package-lock.json, package.json
Brings in https://github.com/google/wireit/pull/312
=> Upgrade wireit

packages/lit-html/src/lit-html.ts
s/comment comment/comment/
Upstreaming cl/465058282
=> Fix typo in comment

packages/labs/ssr/README.md
Just a small correction to the README.
=> [labs/ssr] fix Hydrating LitElements example markup

.changeset/lazy-moons-train.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Adds `onComplete` and `onError` callbacks to Task.
=> Task add onComplete and onError

packages/labs/task/README.md
=> Fix typo in task README

packages/labs/router/README.md
I changed the h3 tag to be an h1 tag to match the other routes
=> Example code had an h1 tag closed by an h3 tag

.changeset/blue-olives-fetch.md
Preparing changeset for release
=> Add lit to changeset along side reactive-element

.changeset/unlucky-lamps-sing.md, packages/labs/context/src/lib/controllers/context-provider.ts, packages/labs/context/src/test/context-provider_test.ts, packages/labs/context/src/test/late-provider_test.ts
Fixes https://github.com/lit/lit/issues/3251
=> Allow ContextProvider to be added lazily and still work with ContextRoot

.changeset/nasty-rats-relate.md, .changeset/unlucky-clouds-hide.md, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/layouts/flow.ts, packages/labs/virtualizer/src/test/layouts/flow.test.ts, packages/labs/virtualizer/src/test/scenarios/immediate-items-change.test.ts
Fixes #3243 (and #3498, which was revealed in our automated tests by the fix for #3243)
=> [labs/virtualizer] Fix 3243

.changeset/slimy-bees-appear.md, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/test/scenarios/slotted-virtualizer-scrolling.test.ts
=> [labs/virtualizer] Fix #3493

.changeset/five-pandas-report.md, .changeset/neat-bananas-cough.md, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/test/scenarios/immediate-rerender.test.ts, packages/labs/virtualizer/src/test/scenarios/layout-complete.test.ts
=> [labs/virtualizer] Fix #3481 and #3518

.changeset/quick-apricots-lick.md, packages/labs/eleventy-plugin-lit/src/test/eleventy-plugin-test.ts, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts
Adding forwards compatibility with the `shadowroot` -> `shadowrootmode` breaking change ([link to intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/xzT-vN-bx0s/m/qWrGNWwQAAAJ)) Or maybe we just wait until it's shipped in _something_ behind a flag
=> [SSR] Add shadowrootmode forwards compat

packages/lit-element/README.md, packages/lit-html/README.md, packages/reactive-element/README.md
Just unify the npm badges as the Lit root npm badge.
Also remove some old `next` reference.
=> Unify the npm badges

.changeset/sweet-mice-love.md, packages/labs/context/src/lib/decorators/provide.ts
This is needed for some internal tooling.
=> Explicitly annotate the this value of set function

.changeset/chatty-bananas-dream.md, packages/labs/nextjs/README.md
=> [labs/nextjs] Fix README title

.changeset/quiet-dots-yell.md, package-lock.json, packages/lit-element/package.json, packages/lit-html/package.json, packages/lit-html/src/lit-html.ts, packages/lit-starter-js/package.json, packages/lit-starter-ts/package.json, packages/lit/package.json, packages/reactive-element/package.json, packages/tests/package.json
A small code reduction that we can do when dropping IE11 support.
=> [lit-html] Use toggleAttribute() to simplify boolean attribute parts

.changeset/rich-horses-move.md, packages/labs/ssr-client/package.json
=> [labs/ssr-client] Include node build output in npm package

package-lock.json
Updates package-lock to make versions match the newly bumped ones from recent releases.
=> [chore] Update package-lock

.changeset/tiny-mails-learn.md, packages/labs/ssr-dom-shim/src/index.ts
Fixes #3672 
This was also an issue with Astro's dev mode. This addresses that as well.
=> [labs/ssr-dom-shim] Warn instead of throwing on repeat custom element registration in dev mode

.changeset/friendly-grapes-melt.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Flagged by a linter, was leaving this off intentional?
=> Add missing await in task.ts

.changeset/khaki-pigs-visit.md, packages/benchmarks/utils/query-params.ts
Just fixing what seems to be an error in the comment.
=> Benchmarks comment typo

.changeset/old-bikes-rush.md, packages/labs/virtualizer/src/layouts/shared/SizeCache.ts, packages/labs/virtualizer/src/layouts/shared/SizeGapPaddingBaseLayout.ts
=> Add missing license headers to files to placate the compliance checks.

.changeset/calm-insects-complain.md, packages/labs/virtualizer/src/ScrollerController.ts
There are some checks in here that are unnecessary and illogical.  There are also some type assertions that do not need to be there.
=> Removing some crufty code in Virtualizer ScrollerController

dev-docs/lit-release-process.md
=> Fix typo in lit-release-process.md

.changeset/analyzer-tsconfig-extends.md, packages/labs/analyzer/src/lib/analyze-package.ts
=> fix: derive files from tsconfigs which extend

.changeset/gen-manifest-prerelease.md, packages/labs/gen-manifest/package.json
As discussed in the August community call (or was it the eng call?), this publishes the gen-manifest package for those wishing to make their own CLIs
=> feat(gen-manifest): initial prerelease

.changeset/warm-ears-breathe.md, packages/labs/gen-wrapper-angular/goldens/test-element-a/.gitignore, packages/labs/gen-wrapper-angular/goldens/test-element-a/package.json, packages/labs/gen-wrapper-angular/goldens/test-element-a/src/sub/element-sub.ts, packages/labs/gen-wrapper-angular/src/index.ts, packages/labs/gen-wrapper-angular/src/lib/package-json-template.ts, packages/labs/gen-wrapper-angular/src/lib/wrapper-module-template.ts, packages/labs/gen-wrapper-react/goldens/test-element-a/.gitignore, packages/labs/gen-wrapper-react/goldens/test-element-a/package.json, packages/labs/gen-wrapper-react/goldens/test-element-a/src/sub/element-sub.ts, packages/labs/gen-wrapper-react/src/index.ts, packages/labs/gen-wrapper-vue/goldens/test-element-a/.gitignore, packages/labs/gen-wrapper-vue/goldens/test-element-a/package.json, packages/labs/gen-wrapper-vue/goldens/test-element-a/scripts/rename.js, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/sub/ElementSub.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/vite.config.ts, packages/labs/gen-wrapper-vue/src/index.ts, packages/labs/gen-wrapper-vue/src/lib/rename-template.ts, packages/labs/gen-wrapper-vue/src/lib/vite.config-template.ts, packages/labs/gen-wrapper-vue/src/lib/wrapper-module-template-sfc.ts, packages/labs/gen-wrapper-vue/test-output/src/tests/SubContainer.vue, packages/labs/gen-wrapper-vue/test-output/src/tests/test-element-sub_test.ts, packages/labs/test-projects/test-element-a/package.json, packages/labs/test-projects/test-element-a/src/sub/element-sub.ts
Fix module path error when generating wrapper code in windows. close #4051
=> fix(labs/gen-wrapper-*): fix module path error when generating wrapper code in windows

.changeset/good-pots-beam.md, packages/labs/preact-signals/package.json
RFC: https://github.com/lit/rfcs/pull/19
Make it possible to release a release candidate for `@lit-labs/preact-signals`!
=> [lit-labs/preact-signals] pre-release preact-signals

.changeset/gen-manifest.md, packages/labs/gen-manifest/package.json
- corrects the `main` entry in package.json
- adds build artifacts to package.json `files`
=> fix(gen-manifest): npm files, main field

.changeset/perfect-bags-cheer.md, packages/labs/analyzer/src/lib/javascript/classes.ts, packages/labs/analyzer/src/lib/utils.ts, packages/labs/analyzer/src/test/javascript/classes_test.ts, packages/labs/analyzer/test-files/js/classes/classes.js, packages/labs/analyzer/test-files/ts/classes/src/classes.ts
=> fix(analyzer): ecma private members

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml
- add an entry to the bug and feature issue templates for the analyzer
=> chore: add analyzer to issue templates

.changeset/clean-avocados-type.md, packages/labs/context/src/lib/controllers/context-provider.ts, packages/labs/context/src/test/context-provider_test.ts
Fixes https://github.com/lit/lit/issues/4158
=> Fix infinite loop in Context

.changeset/lemon-ducks-smile.md, packages/labs/ssr/src/lib/render-result-readable.ts, packages/labs/ssr/src/test/lib/render-result-readable_test.ts
=> Fix SSR truncated response

packages/reactive-element/src/decorators/base.ts, packages/reactive-element/src/decorators/property.ts, packages/reactive-element/src/decorators/query-all.ts, packages/reactive-element/src/decorators/query-assigned-elements.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts, packages/reactive-element/src/decorators/query-async.ts, packages/reactive-element/src/decorators/query.ts, packages/reactive-element/src/decorators/state.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/decorators/property_test.ts, packages/reactive-element/src/test/decorators/query_test.ts, scripts/check-size.js
Based on fixing internal tests that failed.
Fixes #4222
=> Some small, subtle fixes to 3.0 decorators

.changeset/six-fishes-clean.md, packages/labs/virtualizer/src/layouts/masonry.ts, packages/labs/virtualizer/src/test/scenarios/masonry-gotchas.test.ts
This PR addresses a new failure case for #3815 (which I've just reopened). PR includes an additional test, along with the fix.
=> [labs/virtualizer] Fix new failure case for #3815

.changeset/smart-apes-rhyme.md, packages/context/src/lib/decorators/provide.ts, packages/context/src/test/decorators/provide_test.ts
Fixes https://github.com/lit/lit/issues/4349
=> [context] Make `@provide()` decorated property configurable

.changeset/mighty-geese-beg.md, packages/react/src/create-component.ts, packages/react/src/test/create-component_test.tsx
Fixes https://github.com/lit/lit/issues/4374
=> [react] Prefer element property type over React built-in type

package-lock.json
Nothing to see here. Small package-lock sync post https://github.com/lit/lit/pull/4399
Generated with `npm i`.
Continuous integration.
=> [infra] sync package-lock post release

.changeset/lazy-beans-tap.md, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
Reverts lit/lit#4418
Want to let rictic take a look. Merged too early
=> Revert "[labs/ssr] allow binding attributes to html tag when using server templates"

.changeset/bright-ways-rhyme.md, packages/labs/virtualizer/package.json
=> fix: include /support/* files into lit-virtualizer npm package

.changeset/fresh-gifts-love.md, packages/benchmarks/generator/src/deoptigate.ts, packages/lit-starter-js/docs-src/_includes/example.11ty.cjs, packages/lit-starter-ts/docs-src/_includes/example.11ty.cjs
These three seem legit, though unlikely to be exploited.
https://github.com/lit/lit/security/code-scanning/3
https://github.com/lit/lit/security/code-scanning/2
https://github.com/lit/lit/security/code-scanning/13
=> Fix security alerts:

.changeset/few-garlics-dress.md, packages/labs/ssr-client/src/lib/hydrate-lit-html.ts
=> [labs/ssr-client] Provide better error message on hydration value mismatch

.changeset/config.json
Reverts the changeset config change introduced for the SSR bug fix in https://github.com/lit/lit/pull/4515
Further work would be to see if we can add a constraint such as:
- For the 4 core packages, they should all be tied together.
=> [infra] revert changeset config.json

.changeset/warm-pens-invite.md, packages/labs/analyzer/src/lib/lit-element/lit-element.ts, packages/labs/analyzer/src/lib/types.ts, packages/labs/analyzer/src/test/server/lit-element/lit-element_test.ts, packages/labs/analyzer/test-files/ts/node-next-resolution/package.json, packages/labs/analyzer/test-files/ts/node-next-resolution/src/element-a.ts, packages/labs/analyzer/test-files/ts/node-next-resolution/src/main.ts, packages/labs/analyzer/test-files/ts/node-next-resolution/tsconfig.json
Fixes https://github.com/lit/lit/issues/4742
Fixes https://github.com/lit/lit/issues/4743
=> [labs/analyzer] Fix resolution and module detection w/ NodeNext resolution

.changeset/wicked-rabbits-trade.md, packages/labs/task/src/test/task_test.ts, packages/task/src/task.ts, packages/task/src/test/task_test.ts
=> feat(task): improve type checking for tuples

.changeset/dull-pandas-juggle.md, packages/labs/analyzer/README.md, packages/labs/compiler/README.md, packages/labs/eleventy-plugin-lit/README.md, packages/labs/eslint-plugin/README.md, packages/labs/motion/README.md, packages/labs/nextjs/README.md, packages/labs/observers/README.md, packages/labs/preact-signals/README.md, packages/labs/router/README.md, packages/labs/scoped-registry-mixin/README.md, packages/labs/signals/README.md, packages/labs/ssr-react/README.md, packages/labs/ssr/README.md, packages/labs/testing/README.md, packages/labs/tsserver-plugin/README.md, packages/labs/virtualizer/README.md, packages/labs/vue-utils/README.md
Fixes https://github.com/lit/lit/issues/2873
I didn't update *every* labs package - I skipped the CLI sub-packages.
=> [labs] Add Lit Labs notices to labs readmes

.changeset/great-swans-rule.md, package-lock.json, packages/ts-transformers/package.json
=> fix(ts-transformers): make typescript a peer dep

packages/ts-transformers/src/internal/decorators/query-all.ts
Fixup a minor mistake in an example code
=> [ts-transformers] fixup example mistake

packages/lit-html/src/lit-html.ts, packages/reactive-element/src/reactive-element.ts
=> [all] Cleanup some old comments

.changeset/huge-lamps-cheat.md, packages/labs/nextjs/src/index.ts
fixes https://github.com/lit/lit/issues/4905
=> fix(labs/nextjs): update webpack exclude to filter out node_modules

.changeset/mean-donkeys-confess.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts, scripts/check-size.js
=> [reactive-element] fixes inconsistent initial values in changed properties

.changeset/lovely-mangos-deny.md, .changeset/witty-masks-begin.md, .github/copilot-instructions.md, packages/internal-scripts/src/release-image.ts, packages/labs/vue-utils/src/wrapper-utils.ts
Added copilot instructions. Please bikeshed, copilot instructions docs recommend a very short instructions
| Parent | Children |
| -- | -- |
| [#4991](https://github.com/lit/lit/pull/4991) | [#4971](https://github.com/lit/lit/pull/4971), [#4990](https://github.com/lit/lit/pull/4990) |
=> style(copilot-instructions): add a copilot instructions file

.changeset/dirty-mirrors-matter.md, packages/context/README.md, packages/labs/motion/README.md, packages/labs/observers/README.md, packages/labs/signals/README.md, packages/labs/virtualizer/README.md, packages/lit-element/README.md, packages/lit-html/README.md, packages/lit/README.md, packages/react/README.md, packages/reactive-element/README.md, packages/task/README.md
Cleans up notices about old prereleases, adds badges and doc links, adds docs to observers.
Fixes #4996
=> [all] A bunch of README updates

packages/context/README.md, packages/react/README.md, packages/task/README.md
This small PR fixes the `CONTRIBUTING.md` reference in packages `README.md`.
=> Fix `CONTRIBUTING.md` reference

.changeset/fifty-frogs-brake.md, package-lock.json, packages/labs/rollup-plugin-minify-html-literals/package.json, packages/labs/rollup-plugin-minify-html-literals/src/index.ts, packages/labs/rollup-plugin-minify-html-literals/src/lib/minify-html-literals.ts, packages/labs/rollup-plugin-minify-html-literals/src/lib/strategy.ts, packages/labs/rollup-plugin-minify-html-literals/src/test/minify-html-literals.spec.ts, packages/labs/rollup-plugin-minify-html-literals/src/test/rollup-plugin-minify-html-literals.spec.ts, packages/labs/rollup-plugin-minify-html-literals/src/test/strategy.spec.ts
This also fixes CVE-2022-37620 :)
=> [labs/rollup-plugin-minify-html-literals] Replace unmaintained html-minifier with html-minifier-next
