lit/lit

src/labs/lit-extended.ts, src/lit-html.ts, src/test/labs/lit-extended_test.ts, src/test/lit-html_test.ts
=> `renderTo` overwrites if the container's current `TemplateInstance` has a different `Template`.

README.md, src/lit-html.ts, src/test/lit-html_test.ts
Simple change, but seems to handle the basics correctly.
Still need to decide what rejections should do. Currently they do nothing, should they could clear the part? Right now a template author realistically would have to explicitly handle rejections, which might be good.
=> Add support for Promises

src/labs/until.ts, src/test/labs/until_test.ts, test/index.html
Lets templates display default content until a Promise resolves:
```js
html`<div>${until(promise, html`<span>loading...</span>`)}</div>`
```
=> Add until() to labs/

src/test/lib/until_test.ts
For some reason the until test was failing on Chrome, but only when devtools were closed :/ It was passing fine on Safari and Firefox.
Waiting one event loop turn fixed it.
=> Fix until test

src/lib/lit-extended.ts, src/lit-html.ts, src/test/lit-html_test.ts
Seems to give a ~5% improvement on first render, and ~25% improvement on updates for a deep recursion benchmark.
=> Add dirty-checking for primitive values

src/lit-html.ts, src/test/lit-html_test.ts
This isn't a big performance improvement, but it really simplifies handling of iterables, using a for/of loop, rather than manually using the JS iteration protocol.
It should also make Array handling more easily backward compatible with IE11. We just need an Array.isArray() polyfill, and either just the existence of `Symbol` or an extra guard in case `Symbol` doesn't exist.
=> Simplify the handling of Arrays and Iterables

src/lit-html.ts, src/test/lit-html_test.ts
Suggested fix for https://github.com/PolymerLabs/lit-html/issues/62
The value of `exprMarker` becomes a magic string that breaks any template that includes it. To avoid that added a random number that changes when the file is reloaded (there are probably better ways to do that though).
=> Fix for `{{}}` in the template.

tsconfig.json
> Emit the source alongside the sourcemaps within a single file; requires `--inlineSourceMap` or `--sourceMap` to be set.
https://www.typescriptlang.org/docs/handbook/compiler-options.html
=> feat(tsconfig): inlineSources

demo/clock.html, demo/clock.js, src/lit-html.ts, src/test/lit-html_test.ts
Adds a new `svg` template tag, so you can declare that templates should produce nodes in the SVG namespace:
```javascript
html`
<svg>
<circle/>
${data.map(d => svg`<line ... />`)}
</svg>
`
```
=> Add SVG support & demo

src/lit-html.ts
Avoid adding new properties to NodePart post construction, makes closure compiler a bit more happy as well.
=> Initialize NodePart._previousValue to undefined

README.md
Chrome 61 is now stable release https://chromereleases.googleblog.com/2017/09/stable-channel-update-for-desktop.html
=> Update browser compatibility

src/lit-html.ts
just a small thing to support EDGE (tested on "Edge 40; EdgeHTML 15").
IE11 apparently renders the html but won't insert the values - needs some more investigation
=> maybe another PR if I can figure it out
@justinfagnani sooo this actually also work in IE11 :)
2 Limitations so far:
1) Last node can't be a node with a variable
```
// => works in IE11
return html`
<h2>${header}</h2>
<p>ending</p>
`;
// does not work in IE11
return html`
<h2>${header}</h2>
`;
````
2) You need a polyfill for template tag and ES6 Symbols
=> so this should be somewhere noted
I will copy this to an Issue
=> Support for Edge/IE11

src/lib/repeat.ts, src/lit-html.ts, src/test/lit-html_test.ts
This is a partial fix for #111 for Microsoft Edge. It fixes the 48 unit tests which were broken on Edge so that all 96 tests now pass.
_This still relies on native ES modules_, which must be enabled on Edge through about:flags, "Enable experimental JavaScript features". This PR just fixes the unit tests. To get everything to pass in production Edge (and, eventually, IE), separate work will be required to create a bundled build.
One thing to review: the loop that processed attributes needed to be rewritten to deal with the fact that Edge and IE don't necessarily return attributes in document order. The new loop extracts the expected string name for the attribute from the corresponding member of `strings`, then uses that to look up the actual `Attr` instance on the element. Because of that …
=> Edge unit tests pass

src/lit-html.ts, src/test/lit-html_test.ts
Two main optimizations:
1. The regexs are _really_ bad at predicting where the end of a string
is. This leads to bad performance when using a `*` quantifier to match
everything to the end. It's much faster to use `#indexOf` and
`#lastIndexOf` to find the `<` and `>`, and do some comparisons.
- https://jsperf.com/html-template-tag-context
2. String concatenation is much faster than building an array to join
it.
- https://jsperf.com/string-concatenation/47
- (This even compares an already made array, it's super slow without
even building the array in a loop!)
=> Optimizes Template#_getHtml

src/lit-html.ts
The template string iteration that's used in `Template#_getHtml` is pretty nifty. This reuses it in `AttributePart#setValue`, since it's very much the same.
=> Normalize template string part iteration

src/lit-html.ts, src/test/lit-html_test.ts
Not all thenables behave asynchronously, so we should set the
`#_previousValue` first. And, it should be private like all the other
helper methods on `NodePart`.
=> Minor fix NodePart#_setPromise

src/lib/repeat.ts
This pretty seriously optimizes the repeat directive.
Now, it creates an extra text node for every item (it creates an explicit start node for every item, instead of reusing the previous' end node). That's not _perfect_, but it simplifies a lot of code and makes it run _much_ faster. I think it's a pretty good tradeoff.
Fixes #95.
Fixes #157.
=> Optimize repeat

src/lib/lit-extended.ts, src/test/lib/lit-extended_test.ts
No need to register the part as a listener, just register the listener.
And fixes bugs with updating the event listener (instead of having to render it null first).
=> Simplify EventPart

src/lit-html.ts
No need to do it every time we clone, we can just reparent them after the DOM string is initially parsed.
I created a reusable helper like #163, since this will be useful for the repeat directive, too.
=> Reparent SVGs after initial creation

package.json
The prepare script is run after installation and before publish, meaning that
it is run during npm-link and when installing from the github repository,
e.g. when fetching a prereleased version.
This means we can use
```json
{
"//": "...",
"devDependencies": {
"lit-html": "PolymerLabs/lit-html#master",
}
}
```
and it'll work, rather than leave us with a package containing the typescript sources but no build output.
=> Add prepare script to allow linking or github installs

src/lit-html.ts
A pretty easy optimization to `lastAttributeNameRegex`. Giving it a starting bound improves the performance by 2-3x in Chrome, 3x in Safari, and 5-6x in Firefox.
See https://regex101.com/r/etquoe/2/, and try deleting the space character class at the beginning, and see the match time in the upper right side of the input.
Then try this [very long attribute name](https://regex101.com/r/etquoe/3) on on for size. It's infinitely faster (division by zero error...). And then there's improvement to super long [quoted](https://regex101.com/r/etquoe/4) and [unquoted](https://regex101.com/r/etquoe/6) attribute values.
The space between a tagname and an attribute, or between two attributes, is required by https://www.w3.org/TR/html5/syntax.html#attributes-0.
=> Optimize lastAttributeNameRegex

package-lock.json, package.json, src/test/lib/lit-extended_test.ts, src/test/lit-html_test.ts, test/index-polyserve.html, test/index.html
This PR includes a "complete" ES2015 polyfill. Alternatively we could select individual polyfills for every ES2015+ feature we use.
This PR also fixes two small issues in the tests.
Together with #202 this fixes _all tests but one_ in IE. The one failing test is linked to the template polyfill table issue.
In the past I saw some tests failing on the sorting of attributes, but I don't see them anymore. This makes me doubt whether these failing tests I saw were from lit-html or my lit-html extension.
Linked to issue #210
=> Fix IE tests depending on ES2015 features

src/test/lit-html_test.ts
This test fails due to a bug in the template polyfill. Disabling this test allows us to reach 100% passing tests on IE, which means IE can be added to the CI build.
As mentioned in #210
Together with #202 this change results in a passing build for IE.
=> Disable table test in IE

src/lit-html.ts, src/test/lib/repeat_test.ts, src/test/lib/unsafe-html_test.ts, src/test/lib/until_test.ts, src/test/lit-html_test.ts
Empty text nodes aren't cloned by IE when using document.importNode.
Putting content in the text ensures that they will be cloned by IE.
This increases the number of passing tests on IE11 from 40 to 93.
One failure remains for table handling, a couple are due to a different ordering of attributes in IE and the other remaining failures are due to missing `Promise`, `Array.from`, `String#startsWith`.
Fixes #201 
This is an alternative to #143 
Open questions:
- The nodes need a unique content. Given that we already have a unique marker, I just reused that instead of creating another unique string. This might be confusing, so maybe for readability's sake it should be a separate string?
- An alternative to the unique string could be Unicode codepoint U+2060 "word joiner", which could be left …
=> Do not use empty text nodes in the template element

package-lock.json, src/lit-html.ts, src/test/lib/repeat_test.ts, src/test/lit-html_test.ts
Our whitespace stripper doesn't understand CSS's whitespace collapsing rules. For instsance,
```js
html`<span>test<span> <a href="">ing</a>`
```
should read "test ing".
=> Leave whitespace text nodes intact

package.json
The repository URL in https://www.npmjs.com/package/lit-html looks wrong.
This PR updates `package.json` to fix the URL.
=> Update the repository location in package.json

README.md
"it's" is shorthand for "it is" instead of the possessive form.
=> Readme typo: it's/its own

.travis.yml, src/lib/lit-extended.ts, src/lit-html.ts, src/test/lib/async-append_test.ts, src/test/lib/async-replace_test.ts, src/test/lib/lit-extended_test.ts, src/test/lib/repeat_test.ts, src/test/lib/unsafe-html_test.ts, src/test/lib/until_test.ts, src/test/lit-html_test.ts, src/test/test-helpers.ts, test/shady.html
This PR uses comment nodes in templates, but replaces them with text nodes during initial cloning to continue to support all the previous binding positions. That's why tests don't have to change much compared to #202.
I added a test of a binding that requires new placeholder node generation in style tags to ensure that style bindings still work.
=> IE11 support

src/lib/lit-extended.ts, src/test/lib/lit-extended_test.ts
Fixes #306. Instead of calling add/removeEventListener whenever an EventPart's listener changes, installs the listener 1x and stores/calls the user's method, updating it via a simple property set when needed.
Note, this uses a previously committed method of updating the EventPart event listener.
=> Makes EventPart more efficiently update

src/test/lit-html_test.ts
Similar to https://github.com/Polymer/lit-html/pull/313 but checks `.textContent`. instead of `.innerHTML`. This passes on all supported browsers.
cc @jridgewell
=> Add test that expressions in <style> don’t corrupt textContent

src/lit-html.ts
This reduces the casts to `any` a little. Supersedes #227
=> Add a type for template containers.

src/lit-html.ts
The template's document doesn't have a browsing context, so custom elements aren't upgraded. This change defers upgrading any custom elements inside the template until after the treewalker that links the Parts to the DOM.
This is important because custom elements can modify their DOM at upgrade time (e.g. when using ShadyDOM).
Fixes #231
=> Keep fragment in the template's document during clone

src/lib/modify-template.ts, src/lib/shady-render.ts, src/lit-html.ts, src/test/lib/modify-template_test.ts, src/test/lib/shady-render_test.ts, test/index.html, test/shady.html
Fixes #326 by imposing a limitation that styles for a scope name can only be supplied in the initial render of that shadowRoot. This is required because `ShadyCSS` can only prepare styles for a scope once to properly track styles in that scope and process custom properties when polyfilled and @apply.
Styles are processed based on initial scope rendering, but templated DOM within a scope will always be correctly given a scoping class. 
Note that styles in the first render of a scope can contain lit parts. This is useful for one-time bindings.
**Warning:** merge only after [this ShadyCSS PR](https://github.com/webcomponents/shadycss/pull/183) is merged and released.
=> Shady render fix

src/lit-html.ts, src/test/lit-html_test.ts
As mentioned in #375, if all values for an AttributePart or PropertyPart are `undefined`, the initial render will not set the attribute/property. See [this comment](https://github.com/Polymer/lit-html/issues/375#issuecomment-399745122) for an explanation as to why that's wrong.
Instead of adding an extra property to check for the initial render and introducing logic to update the property on the first render I simply added a check on the length of `this._previousValue`, as that array can only be empty for the initial render (the property is set to an empty array in the constructor; `setValue` always sets the property to a non-empty array).
=> Render initial undefined values

package.json, src/lit-html.ts, src/test/lib/lit-extended_test.ts, src/test/lit-html_test.ts
=> Handle case-sensitive attributes like viewBox.

README.md
=> Change “render” -> “template” in places in README to avoid confusion with lit’s render()

src/lib/unsafe-html.ts, src/lit-html.ts, src/test/lib/unsafe-html_test.ts
Fixes #222 and supersedes #247 
cc @daKmoR
=> Dirty check primitive values passed to unsafeHTML()

package-lock.json, package.json, src/core.ts, src/lib/async-append.ts, src/lib/async-replace.ts, src/lib/lit-extended.ts, src/lib/repeat.ts, src/lib/unsafe-html.ts, src/lib/until.ts, src/lit-html.ts, src/test/core_test.ts, src/test/lib/lit-extended_test.ts, src/test/lib/modify-template_test.ts, src/test/lit-html_test.ts, test/index-polyserve.html, test/index.html
This PR removes the SinglePart/MultiPart distinction. AttributeParts now only have a single value, but are associated with an AttributeCommitter that commits multiple values to an attribute.
This PR is based on #398.
The attribute handling code is a bit simpler in this factoring, though the "fast" path for attribute with a single value isn't implemented here, but it is implemented for PropertyCommitter. Not sure if this matters much.
=> Refactor AttributePart to only have a single value

src/core.ts, src/lib/async-append.ts, src/lib/async-replace.ts, src/lib/repeat.ts, src/test/core_test.ts
Adds `NodePart#insertAfterNode`, `NodePart#appendIntoPart`, `NodePart#insertAfterPart` to abstract away a little of the marker node management. Cleans up some of the code in `NodePart#_setIterable`.
This brings the size of core.js to just under 2.5k
Note that I didn't put much work into cleaning up repeat(), but left a comment explaining why.
=> Add NodePart attachment methods

src/directives/guard.ts, src/test/directives/guard_test.ts
This adds a guard directive. I know there is a lot of refactoring going on in https://github.com/Polymer/lit-html/pull/436, but with this PR this can already be reviewed. I can rebase later.
The implementation is really simple, it just dirty checks the expression and if it changed since the previous render it sets the value. 
Dirty checking for objects is done on identity/pointer, so immutable data patterns need to be used for updating. Unlike the polymer data system, there is no 'escape' like doing `this.set('foo.bar')` or `notifyPath()`. We could add a 'force' parameter, but maybe see if we can get away without that first.
=> Add guard directive

src/lib/dom.ts, src/lib/parts.ts, src/lib/render.ts, src/lib/template-instance.ts, src/test/lib/render_test.ts
This keeps us from creating instance properties that alias assessors on disconnected elements.
This technique only works if `customElements.upgrade` is implemented. It's in Chrome, the polyfill, and Safari TP, and Firefox nightly.
There's two other ways we could solve this. First we either:
1. Patch TreeWalker properly in ShadyDOM
2. Don't use TreeWalker to traverse, so that we don't traverse ShadyDOM ShadowRoots created synchronously in constructors.
Then we go back to `document.importNode(template.content, true)` to clone & upgrade in one step.
=> Upgrade disconnected custom elements before setting properties on them.

src/lib/parts.ts, src/test/lib/parts_test.ts
There's a bug in your `setValue()` function in `AttributePart`
This statement always evaluates to true, which made the conditional always evaluate the true branch:
```
value !== noChange || !isPrimitive(value)
```
Clearly the intent is to do nothing if `value === noChange` (or if ` isPrimitive(value) && value === this.value`)
=> Fix bug in AttributePart setValue

src/lib/directive.ts
Just a small change, I think this variant is a little cleaner since it doesn't use 'private' properties on objects.
This saves 21 bytes in the library size (before minification and compression). It increases runtime memory consumption by a few bytes: it adds one `WeakMap` instance to the memory pool.
I found no measurable performance difference.
Someone who understands TypeScript should probably check the `any` type on the WeakMap key. I'm sure it's not correct, but I couldn't find anything else that would compile. I can update the PR with the correct type.
----
An alternative option is to use Set or WeakSet instead of a WeakMap, but I believe WeakMap performance is slightly better than Set, and WeakSet would require another polyfill for IE11.
The odds of a directive ever leaving memory …
=> Small directive optimization

src/lib/directive.ts
=> Don’t use WeakMap with primitive value keys.

CHANGELOG.md, rollup.config.js, src/lib/default-template-processor.ts, src/lib/directive.ts, src/lib/part.ts, src/lib/parts.ts, src/lib/template-instance.ts, src/lib/template-result.ts, src/lit-html.ts, src/test/lib/parts_test.ts
For compatibility with tools that don't handle cycles.
Note: I broke out more interfaces than strictly necessary (splitting TemplateProcessor would have been enough), but I didn't yet create an interface for NodePart, which would be nice to do soon.
=> Break cycle in dependency graph

CHANGELOG.md
Just a small convenience since bare #num issues don't get auto linked in markdown files
=> Make PR references in changelog into links

src/lib/shady-render.ts
Tiny optimization. The `host` variable is only used once so we don't need this duplicate check.
=> Remove unused variable

src/lib/parts.ts, src/lib/render.ts, src/lib/template-instance.ts
As discussed in #455 
For some reason ShadyRender did not have the necessary code to upgrade the elements, so this possibly fixes a bug there. If this commit does not cause any tests to break then there's clearly some testing surface missing there, because it definitely changes behaviour.
=> Make TemplateInstance clone return upgraded fragments

src/lib/shady-render.ts, src/test/lib/shady-render-apply_test.ts, src/test/lib/shady-render_test.ts
This ensures ShadyCSS can update the style in the template that will be rendered by lit-html. ShadyCSS needs to do this, for example, when the set of properties needed in any `@apply` changes.
Fixes https://github.com/Polymer/lit-element/issues/117
=> Ensure template given to ShadyCSS is the one rendered by lit-html

CHANGELOG.md, src/lib/modify-template.ts, src/lib/shady-render.ts, src/test/lib/modify-template_test.ts, src/test/lib/shady-render-apply_test.ts, src/test/lib/shady-render_test.ts, src/test/test-utils/shadow-root.ts, test/index.html, test/shady-apply.html, test/shady.html
* Correctly tests shimmed css custom properties (by fixing a typo).
* Ensures `shady` and `shady-apply` tests have a working version of ShadyCSS so that styling is tested.
* Fixes #505 by adding support for adding document fragments to templates.
* Fixes #506 by ensuring `ShadyCSS.styleElement` is called once per rendering to a given container.
* Ensures lit-html adapts to the template manipulations done by ShadyCSS so parts remain intact.
* Adds additional tests
=> Fix issues with shady-render introduced in 0.11.3

CHANGELOG.md, docs-src/guide/01-getting-started.md, docs-src/guide/02-writing-templates.md, src/directives/async-append.ts, src/directives/async-replace.ts, src/directives/repeat.ts, src/directives/when.ts, src/lib/default-template-processor.ts, src/lib/parts.ts, src/lib/render-options.ts, src/lib/render.ts, src/lib/shady-render.ts, src/lib/template-instance.ts, src/lib/template-processor.ts, src/test/lib/incompatible-shady-render_test.ts, src/test/lib/parts_test.ts, src/test/lib/render_test.ts
This PR changes the signature of `render()` and a few other methods to accept an options object with an optional `eventContext` property. The property is used by EventPart as the `this` argument when calling event listeners.
This means that a Web Component class that calls `render()` can pass itself as the event context and event listeners in templates will not have to be bound to receive the component as 'this'.
LitElement can change roughly like this:
```ts
class LitElement {
// ...
update(changedProperties: PropertyValues) {
render(this.render(), this.renderRoot!, {scopeName: this.localName!, eventContext: this});
}
// ...
}
```
And then subclasses can write event listeners as simple methods:
```ts
class MyElement extends LitElement {
private _onButtonClick(e) {
// now called with the …
```
=> Allow render() to pass an event listener context to be used as the this value for all event listener calls.

src/lib/template-result.ts
These raw tags are causing the Type Doc to get cut off.
=> Fix formatting

CHANGELOG.md, docs-src/guide/02-writing-templates.md, src/lib/parts.ts, src/test/directives/repeat_test.ts, src/test/lib/parts_test.ts, src/test/lib/render_test.ts
Event listeners can be functions or objects with a `handleEvent` method. Listeners are passed as both the listener and options arguments to `addEventListener`/`removeEventListener`, so that the listener can carry event listener options like `capture`, `passive`, and `once`.
```js
const listener = {
handleEvent(e) {
console.log('clicked');
}
capture: true;
}
html`<button @click=${listener}>Click Me</button>`
```
Fixes #145
=> Support event listener options.

src/directives/when.ts
AFAICT, Type Doc supports fenced code blocks, so this should fix the issue with this sample.
=> Fix code example formatting.

.gitignore, package.json, tsconfig.json
Declaration maps are a neat feature that landed in TS 2.9, enabling it
emits a sourcemap for declaration files (.d.ts.map). Like JS .map files
they are for resolving to the original source of declaration files, but
instead of being used by the browser they are used by the user's text
editor/ide.
Basically, where before in vscode if you go to defintion on `html` in
`import {html} from 'lit-html'` you would end up in the declaration
file, now it will take you to the correct position in the original .ts file.
=> Enable TypeScript declaration maps

CHANGELOG.md, docs/_guide/02-writing-templates.md, src/directives/async-append.ts, src/directives/async-replace.ts, src/directives/classMap.ts, src/directives/guard.ts, src/directives/if-defined.ts, src/directives/repeat.ts, src/directives/styleMap.ts, src/directives/unsafe-html.ts, src/directives/until.ts, src/directives/when.ts, src/lib/directive.ts, src/lit-html.ts, src/test/lib/render_test.ts
This change lets us abstract over directive arguments in the future if we need to, which might offer a way to build directive state management into lit's core, rather than forcing directives to use WeakMaps keyed off Parts.
In the meantime, it's a no-op in terms of functionality, though I think it looks a marginally nicer to write directives.
This is a smaller change than converting directives to classes, which I did in https://github.com/Polymer/lit-html/compare/directives
=> Change directive() function to wrap the entire directive factory.

docs/_layouts/post.html, docs/css/main.css
Expand/collapse the contents of the sidebar on narrow viewports. Already added to [pwa-starter-kit docs](https://polymer.github.io/pwa-starter-kit/sample-apps/). Preview https://keanulee.github.io/lit-html/guide
=> toggleNavButton for mobile

CHANGELOG.md, src/lib/parts.ts, src/test/lib/render_test.ts
Fixes https://github.com/Polymer/lit-html/issues/571
=> Don’t use `eventContext` for `this` of event listener objects.

src/lib/parts.ts
Cobalt has a bug on using event listener object. They are fixing the bug but it won't reach all Cobalt users until at least one year later.
This noop change will unblock us from developing lit-html on Cobalt platform.
=> Use callback as event part listener

src/env.d.ts, src/lib/parts.ts, src/lib/shady-render.ts, src/test/lib/incompatible-shady-render_test.ts, src/test/lib/shady-render_test.ts, tsconfig.json
Some minor improvements to Typescript usage (I think). I'm open to feedback 😄
- Moves `ShadowRoot`, `ShadyCSS`, and `ShadyDOM` typings to `env.d.ts` (I'm open to other names)
- Uses `AddEventListenerOptions` interface from `dom.d.ts`
- Removes `skipLibCheck: true` setting from `tsconfig.json`
Fixes #566
=> Move global types to project d.ts file

package-lock.json, package.json, src/test/lib/render_test.ts, test/incompatible-shady.html, test/index.html, test/shady-apply.html, test/shady.html
The prerelease wct-mocha package does away with the dependencies of old WCT client support code that was brought in by the wct-browser-legacy package, including some very outdated/abandoned package versions like a web-ready sinon package.
=> Switch from wct-browser-legacy to wct-mocha for testing

src/directives/async-append.ts, src/directives/async-replace.ts, src/test/directives/async-append_test.ts, src/test/directives/async-replace_test.ts
=> Don't clear() parts in asyncAppend and asyncReplace if the iterable isn't the current value.

src/lib/template-result.ts, src/lib/template.ts, src/test/lib/render_test.ts, src/test/lib/template-result_test.ts, test/index.html
Fixes #594
This changes attribute handling pretty significantly. First, it always rewrites attributes now. We could add back the conditional to only rewrite on Edge. Second, it removes the `isTextBinding` check, and instead relies on the `lastAttributeNameRegex` check to tell us if an expression is in a text position. I was a bit worried about this regex matching for non-attribute cases, but not of the tests fail. I'll try to come up with some more cases to make sure.
@frankiefu, @keanulee, and @azakus it'd be awesome to try this branch with more real-world templates like we have in PWASK and MWC, if you have a chance to do that.
=> Rewrite attribute handling to always avoid IE/Edge value parsing and rewriting

src/lib/shady-render.ts, src/test/lib/shady-render-apply_test.ts, src/test/lib/shady-render_test.ts
Fixes #518. First rendering to a scope is handled specially by (1) rendering to a fragment, (2) letting ShadyCSS scope styles on the template, (3) moving the fragment to the rendering container and making sure that container uses the part we just rendered.
=> Ensure shady-render prepares styling for a scope before attaching child elements

docs/_guide/03-template-reference.md
One reference to 'async' that escaped the original change.
=> Correct 'until' example

docs/package-lock.json, docs/package.json
The idea is to add a package.json for all the product docs sites so that they can all use the same commands:
```
npm run build
npm run serve
npm run deploy
```
And hide the jekyll/gulp stuff behind this. If this is fine, I'll follow with PRs for the other repos.
=> [docs] Add scripts for managing docs

docs/_guide/02-writing-templates.md
Escape backtick to fix rendering in docs
Fixes #691
=> Escape backtick

src/lib/template-result.ts
http://jsbench.github.io/#0ef03a15b22841332a4f3a9c4afeb2ae
=> Speed up getHTML

src/lib/template-instance.ts, src/lib/template.ts
By storing the `endNode`'s index (instead of the `startNode`), it becomes easier to reason about the `COMMENT_NODE` path.
The only reason it's complicated now is because we attempt to remove the node, provided there's some `nextSibling`. If we removed that, `COMMENT_NODE` would become dead simple (at the expensive of a unnecessary extra node).
=> Cleanup Template Preperation

src/lib/shady-render.ts
The  `prepareAcoptedCssText` API requires that `prepareTemplateStyles` is always called.
=> [shady-render] Make compatible with new ShadyCSS API

README.md
I removed the section entirely but if you want to reword instead given latest status feel free.
=> Remove status disclaimer now 1.0.0 has shipped

docs/_guide/01-getting-started.md
This PR updates the getting started docs list of browsers that have shipped support for js modules (see https://caniuse.com/#feat=es6-module).
Closes #818
=> Update docs list of browsers that support js modules

docs/_guide/05-template-reference.md
Adds some missing punctuation of the `classMap` documentation.
=> classMap syntax punctuation

src/polyfills/template_polyfill.ts
Does a few things:
- Minimal poyfills no longer collide
- Since lit doesn't create a HTMLTemplateElement class, checking for its existence doesn't prevent a second polyfilling (imagine two lit-html versions being included on the page)
- Makes `content` non-writable
- Makes `innerHTML` enumerable
- Element class methods/accessors are, strangely, all enumerable
- Uses `removeNodes` and `reparentNodes` helpers
- Reuses the original template element when upgrading it, instead of creating a div
=> Revamp template polyfill

CHANGELOG.md, src/lib/parts.ts, src/lit-html.ts, src/test/lib/parts_test.ts
Also adds an `isIterable` type guard.
Fixes #807.
=> Check if value is primitive in AttributeCommitter

src/lib/dom.ts
- Removes the unnecessary `node` variable to save a few bytes
- We can reuse the `start` variable
- Removes an unnecessary `as Node` typecast in `insertBefore`
- Renames `removeNodes`'s parameters to match `reparentNodes`
=> Cleanup dom module

src/env.d.ts, src/lib/shady-render.ts
The easiest difference to detect between a `ShadowRoot` and a `DocumentFragment` is the `host` element. Conveniently, this works in both v0 and v1.
=> Use duck-typing to test if container is ShadowRoot

src/lib/shady-render.ts, src/lib/template.ts
We can marginally speed up for-loops over non-arrays (in this case, c++
backed `NamedNodeMap` and `NodeList`).
NamedNodeMap: https://jsbench.github.io/#e730df94c251a459f9213abdafe1c34c
NodeList: https://jsbench.github.io/#f638cacc866a1b2d6e517e6cfa900d6b
=> Cache length of non-array iterables

src/lib/template-instance.ts, src/lib/template.ts
Creating `TreeWalker`s isn't very optimized, so reusing a single one in the nested templates can speed it up a bit.
https://jsbench.github.io/#d0363ded1753dec3e060e61e1794896b
=> Reuse a single TreeWalker in nested templates

src/directives/style-map.ts
- `styleMapStatics` is unnecessary, we can determine if this is the first render by just checking `styleMapCache`.
- Use variables for repeated property accesses to save some space.
=> Cleanup styleMap directive

src/lib/template-instance.ts, src/test/lib/render_test.ts
Importing the node can cause any custom elements to upgrade, and non-compliant custom elements can cause DOM mutations.
If this happens before we process the template parts, our `part.index`s walking will be broken. So, it has to wait till afterwards.
But we still have to return upgraded elements before the template part's interact with the DOM. Luckily, we just adopt and upgrade them after the processing.
Fixes #561.
=> Adopt+upgrade template fragments after processing for parts

src/lib/template-instance.ts
I'm assuming it's very common to have a large number of nodes in between the template's parts. If so, creating a small inner loop to advance the tree walker should make everything quicker.
=> Optimize TemplateInstance cloning

package.json
This will make it so npm will link to the homepage and GitHub instead of GitHub twice.
=> Add Homepage URL to package.json

src/lib/shady-render.ts
This fixes spaces inside the warning that gets printed for incompatible ShadyCSS versions.
Before and after:
=> shady-render: fix warning formatting

src/directives/repeat.ts, src/lib/parts.ts, src/lib/template.ts, src/test/directives/until_test.ts, src/test/lib/modify-template_test.ts, src/test/lib/render_test.ts, src/test/lib/shady-render-apply_test.ts, src/test/lib/shady-render_test.ts, src/test/test-utils/shadow-root.ts, tslint.json
This is the result of turning on the no-unnecessary-type-assertion tslint pass and running `--fix`, then fixing up a few tests using `Deferred` and adding an additional assertion in places where TypeScript couldn't infer that a variable was always assigned before being read.
I like this lint pass because it makes the code a bit easier to read and understand. I will admit though that I'm proposing this change because we use this lint pass downstream, and it's annoying seeing the lint warnings.
=> Remove unnecessary type assertions

src/polyfills/template_polyfill.ts, src/test/lib/render_test.ts
- Use getter to override `HTMLTemplateElement.content`
- It doesn't like to override the `content` if it's a data descriptor. A getter works fine, strangely.
- Use appendChild to avoid an infinite loop in ShadyDOM
Fixes #851.
=> Fix tests in Chrome 41

src/lib/template-result.ts
The L in HTML wasn't capitalised in SVGTemplateResult's class comment :3
=> Typo: Fixed HTML capitalisation

src/lib/template.ts, src/test/lib/render_test.ts
Also gives us a chance to use a faster check when looking for bound attributes, since we're already paying for the bytes.
Fixes #854, and includes the test from #854.
=> Fix attribute-like text rendering "$lit$"

src/lib/template.ts
The Unicode control characters include all space characters except " ". So the attribute name character class doesn't need to include them, they're already part of the `\0-\x1F` range.
=> Shorten lastAttributeNameRegex a bit

rollup.config.js, src/lib/parts.ts, src/lib/template-instance.ts
This enables mangling of private properties by giving them the `__foo` naming convention. Really, that's just to distinguish them from the `protected _bar` pattern that was introduced with the Part APIs.
Just this small change saves us 63b after compressing.
=> Mangle private properties

src/lib/template.ts, src/test/lib/render_test.ts
We forgot to update the `partIndex`, so when the attribute tried to
execute the `lastAttributeNameRegex` on the last string (determined by
the `partIndex`), it would fail to match anything.
I'm guessing this will fix #613.
=> Fix rendering comment binding followed by attribute

src/lib/template-instance.ts, src/lib/template.ts
We know how many parts are in the template by the number of values that the `TemplateResult` is holding. So, when we've found that many parts, we can stop traversing the template tree and go back to rendering that DOM.
This makes the [stack](https://github.com/Polymer/lit-html/pull/828) based traversal even more appealing. 😃
=> Early exit template creation

package-lock.json, package.json, travis-bench.sh
Results are now more useful, and use markdown:
https://github.com/Polymer/lit-html/runs/111364626
The most interesting thing to look at is the "this" row, which shows that this commit is indistinguishable from master ("parent"), and is a little faster than NPM published. You can also see now see that master is already a little faster than NPM (which is why this commit is too). Could probably still do with some improvements to readability, but at least the useful numbers are now shown if you know where to look.
=> Bump tachometer version

src/lib/parts.ts, src/lib/render.ts, src/lib/shady-render.ts, src/test/lib/parts_test.ts, src/test/lib/render_test.ts
`render` uses `NodePart` to render the given value and `NodePart#setValue` accepts `unknown`. This change propagates the `unknown` to `render`, which only accepts `TemplateResult` currently but doesn't make use of the specificity.
This also fixes a bug where a `NodePart` that is currently rendered as a single text node will throw if  asked to render a symbol next.
---
Part of changes for Polymer/lit-element#618.
=> Allow `render` to accept any type.

src/lib/parts.ts, src/lib/render.ts, src/lib/shady-render.ts, src/test/lib/parts_test.ts, src/test/lib/render_test.ts
https://github.com/Polymer/lit-html/pull/910 doesn't seem like it will be as quick a fix as expected when I started so we should probably roll #904 back in master and group them into #910 instead.
This reverts commit 5a88cc20bd047e4b6b941dfe7a9203debe90c367.
=> Revert "Allow `render` to accept any type. (#904)"

.travis.yml
Fixes https://github.com/Polymer/lit-html/issues/908
The benchmark job is marked under `allow_failures`, and that combined with `fast_finish: true` means that we'll get a green Travis badge as soon as the test job is done, while the benchmark job will continue to run. We can do that since tachometer integrates as a GitHub check directly.
GitHub UI:
Travis UI:
This PR also pins to Travis Firefox 66 temporarily, because Firefox 67 came out today and is failing to launch with WCT, and will need to be investigated:
```
Test run ended in failure: Error: [get("http://localhost:8081/components/lit-html/generated-index.html?cli_browser_id=1")] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Failed to decode response …
```
=> Run tachometer as separate Travis job, and temporarily pin to Firefox 66

CHANGELOG.md
We meant to release 1.0.1, but actually released 1.1.0. Rewriting history to reflect reality.
=> Fix version number in CHANGELOG.md

docs/_guide/05-creating-directives.md
`import from from` -> `import from`
=> Fix typo in maintaining state docs code example

src/lib/shady-render.ts, src/test/lib/shady-render_no-wc_test.ts, src/test/lib/shady-render_test.ts, test/index.html, test/shady_no-wc.html
This PR also adds an explicitly thrown error in shady-render if `options` with a `scopeName` property is not provided. Before, it would throw when reading `options.scopeName` if `options` wasn't provided, which appears broken even though the option is required.
Fixes #742.
=> Test that shady-render works without shadow DOM or custom elements.

src/test/directives/style-map_test.ts, src/test/lib/render_test.ts, src/test/lib/shady-render-apply_test.ts
Some tests conditionally disable groups of tests by capturing either `test` or `test.skip` from the top-level scope before the tests are run and later calling the captured function instead of `test`:
https://github.com/Polymer/lit-html/blob/1d0549426df5fc420285812f634970d92a027905/src/test/lib/render_test.ts#L22-L34
However, this can potentially prevent the test runner from associating them with the correct suite, which might be a problem if they are meant to be part of a suite with (e.g.) a `setup` function.
=> Conditional tests should use the value of `test` when their containing suite is called.

package-lock.json, package.json, travis-bench.sh
Fixes https://github.com/Polymer/lit-html/issues/920
Previously, only the branch build was correctly appearing as a GitHub check, and the PR build was lost. That's because GitHub expects you to attach your checks to the same feature branch commit, not the automatically-generated merge commit, for both the branch and PR builds. We distinguish them by using a different title for the check.
Note in the screenshot below (or in the checks tab on this PR) that there are now two entries under Tachometer, one for the branch, one for the PR.
=> Distinguish PR from branch builds in Tachometer checks

CHANGELOG.md, src/directives/class-map.ts, src/test/directives/class-map_test.ts
The assignment to `element.className` in `classMap` was causing the error `setting getter-only property "className"`.
According to [the SVG specification](https://www.w3.org/TR/SVG11/types.html#InterfaceSVGStylable), `className` is a read-only property. This differs from [`className` on Element](https://developer.mozilla.org/en-US/docs/Web/API/Element/className), which can be set.
Fixes #930.
=> Change classMap to set classes correctly for SVGs

CHANGELOG.md, src/directives/class-map.ts, src/test/directives/class-map_test.ts
This reverts commit dbb33127a1d500686ab8766599606ef27db18ce7.
The test added in #932 fails in IE11.
cc @AdamVig
=> Revert "Change classMap to set classes correctly for SVGs (#932)"

docs/_guide/03-styling-templates.md
=> Fix casing of window.ShadyCSS in docs

src/lib/parts.ts, src/lit-html.ts, src/test/lib/parts_test.ts, src/test/lit-html_test.ts
This adds a global DOM sanitization function which is settable via the setSanitizeDOMValue call.
If set, this function is called whenever lit-html would write an attribute, property, or text to the dom, with all of the information necessary to determine if the write is safe.
This API is analogous to the Polymer function of the same name, and it pairs nicely with https://github.com/Polymer/polymer-resin
=> Enable a resin-like sanitization mechanism.

src/directives/class-map.ts, src/directives/style-map.ts, src/test/directives/class-map_test.ts, src/test/directives/style-map_test.ts
Clone the info objects before storing them in the cache, so we can detect changes.
Fixes #972
=> Fix repeat object with classmap and stylemap

src/lib/template-result.ts
We want to check for either trustedTypes or TrustedTypes here, until the capitalized TrustedTypes implementation is gone
=> Fix typo in trusted types

src/lib/parts.ts, src/test/lib/parts_test.ts
Imagine this template structure:
```js
render(html`${
// Outer NodePart
${
html`${
// Nested NodePart here
directive()
}`
}
}`, container)
```
When the `NodePart` renders a `TemplateResult`, we get a structure somewhat like:
```html
```
This is because we take the `TemplateResult`'s template fragment (which has the nested `NodePart`'s start/end nodes as direct children), and inject it directly between the outer `NodePart`'s start/end nodes.
When we change the value that's rendered into that part, we would clear out everything between the `NodePart`'s. That leaves the `TemplateResult`'s nested `NodePart`'s start/end nodes completely detached (no `parentNode`). When the nested `NodePart` tries to update (via an async directive), we would try to mutate the nested …
=> Check Node Tree Before Committing

CHANGELOG.md, src/directives/live.ts, src/test/directives/live_test.ts, test/index.html
Fixes #877
This directive dirty-checks new values against the live DOM value rather than the previously rendered value stored by the lit-html Part. `live()` only works with attribute, property, and boolean attribute bindings.
Event bindings use addEventListener and don't have a single "live" value, so the directive doesn't make sense there. It's possible that a lit-html bound event listener is removed externally, but that seems like a very, very corner case.
I tried to make this work with NodeParts in case the text value is changed externally, like with content editable, but in those cases the part markers would likely be disturbed, making that case difficult to support. That might work with a binding to `.textContent`.
cc @LarsDenBakker who wrote a `live()` directive for open-wc.
=> Add live() directive

src/lib/dom.ts, src/lit-html.ts
I made some adjustments to make the lib loadable via import inside nodejs current as a module so we can use it and inhire from it.
- refactored checks to be conditional so the module is still loadable in nodejs for processing in advanced packaging scenarios 
This example can be build via rollup and you will get the right html version 
```
//lit-html-loader.mjs
import { html as litHtml } from 'lit-html'
import { html as strHtml } from 'str-html'
import { isNode, isBrowser, isJsdom } from './check-env-helper.mjs'
export const html = isNode ? strHtml : litHtml;
// index.mjs
import { html } from './lit-html-loader.mjs'
```
this closes: #1051
=> Load in nodejs for packaging treeshake able

.github/CODEOWNERS
Did this on LitElement, realized I hadn't done it for lit-html. 
Typo fixes to docs pages probably don't need signoff from @justinfagnani ...
=> Add arthure as codeowner for docs

package.json, rollup.config.js
Terser started preserving license comments by default, so our bundle size checks over time aren't comparable. This reverts the behavior to what we had at the 1.1.2 release. Because we don't publish the bundle, and only use it for size tracking, it's ok to remove the license comments.
=> Update terser to drop all comments

CHANGELOG.md
I messed this up when resolving a merge conflict from reverting the commit this was added in.
=> Remove trusted types mention from changelog

src/directives/class-map.ts, src/test/directives/class-map_test.ts
Fixes #1111
Revert classMap to previous implementation, but don't use classList or className.
=> Don't disturb imperatively added classes in classMap

CHANGELOG.md, package-lock.json, package.json, src/lib/parts.ts, src/lib/template-result.ts, src/test/directives/unsafe-html_test.ts, src/test/lib/modify-template_test.ts, src/test/lib/shady-render-apply_test.ts, src/test/lib/shady-render-scoping-shim_test.ts, src/test/lib/trusted-types_test.ts, src/test/polyfills/template_polyfill_test.ts, src/test/test-utils/security.ts, test/incompatible-shady.html, test/index.html, test/no-template.html, test/shady-apply.html, test/shady-scoping-shim.html, test/shady.html, test/shady_no-wc.html, test/trusted-types.html, tsconfig.json
Re-adds trusted type support now that it's soon to land in Chrome stable
Size at master:
```
┌──────────────────────────────────────┐
│                                      │
│   Destination: lit-html.bundled.js   │
│   Bundle Size:  9.13 KB              │
│   Minified Size:  9.11 KB            │
│   Gzipped Size:  3.33 KB             │
│   Brotli size: 3.01 KB               │
│                                      │
└──────────────────────────────────────┘
created lit-html.bundled.js in 601ms
3416
```
Size at c5199ab0f1f85fc93ce3bc2d48a409b63c9360a7:
```
lit-html.js → lit-html.bundled.js...
┌──────────────────────────────────────┐
│                                      │
│   Destination: lit-html.bundled.js   │
│   Bundle Size:  9.37 KB              │
│   Minified Size:  9.35 KB …
```
=> Restore trusted types

docs/guide/release-notes/1.2.0.md
The release notes md file is in a separate directory so the links added have a ../ in front of them, however when rendered on the site the release notes are at the root of the guides folder.
This change just fixes that.
=> Adds the correct path information to the release notes links for #1163

docs/_includes/default.html
#2/4. Same as the lit-html one.
Staged: https://20200527t140555-dot-polymer-lit-html.uk.r.appspot.com/
=> Correct copyright dates.

package.json, src/directives/unsafe-html.ts, src/directives/unsafe-svg.ts
Updates for integration with lit-ssr-hacker-news app:
* Adds SSR support for unsafeHTML/SVG
Associated PRs:
* https://github.com/PolymerLabs/lit-ssr-hacker-news/pull/1
* https://github.com/PolymerLabs/lit-ssr/pull/64
=> Adds SSR support for unsafeHTML/SVG

packages/lit-html/.prettierrc.json, packages/lit-html/CHANGELOG.md, packages/lit-html/package-lock.json, packages/lit-html/package.json, packages/lit-html/src/lib/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts, packages/lit-html/src/test/test-utils/strip-markers.ts, packages/lit-html/tsconfig.json, packages/lit-html/web-test-runner.config.js
This adds `html`, `render` and enough implementation to render text bindings. I removed attribute, event and boolean attribute bindings, and support for directives and arrays. There are a couple of small vestiges of other parts types that make it easier to see where they will plug in.
Apologies for the large PR, I found it a little hard to cut this down and retain the end-to-end tests.
This also adds formatting. Build steps will come next.
=> [lit-next] Initial implementation of lit-html 2.0

packages/lit-html/package.json, packages/lit-html/src/lib/lit-html.ts
Removes the `lastAttributeNameRegex` too, so we do less string scanning work overall.
Also moves the bound attribute name prefix check (checking for `.` or `?`) to template prep time and stores the constructor to use with the TemplatePart, moving a little instance work to template work.
=> [lit-next] Optimize regexes, make them more readable

packages/lit-element/CHANGELOG.md, packages/lit-element/src/lib/updating-element.ts, packages/lit-element/src/test/updating-element_test.ts
...and removes `requestUpdateInternal`.  Previously users customizing the property setter would call `requestUpdateInternal` and now they should call `requestUpdate` instead. It is identical to the old method.
=> [lit-element] Changes `requestUpdate` to no longer return a promise

packages/lit-html/package.json, packages/lit-html/src/lib/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
This adds the class-based, stateful directive design.
Currently the `update()` method accepts a part, and we haven't determined what the public API of parts are yet.
Also, nested directives are not support in either attribute or node parts. To support that we'll need to slightly change the way directive state is kept and when values are resolved in order to run directives. I'm holding off on that so we discuss alternatives, such as some kinds of direct composition support.
=> [lit-html] Add directives

.github/workflows/benchmarks.yml, packages/benchmarks/README.md, packages/benchmarks/lit-element/stub1/stub1.html, packages/benchmarks/lit-element/stub1/tachometer.json, packages/benchmarks/lit-html/stub1/stub1.html, packages/benchmarks/lit-html/stub1/tachometer.json, packages/benchmarks/package-lock.json, packages/benchmarks/package.json
- Creates packages/benchmarks
- Two trivial throwaway benchmarks, one for lit-html, one for lit-element
- Uses https://github.com/andrewiggins/tachometer-reporter-action GitHub Action to run and comment on PRs
- Depends on https://github.com/Polymer/tachometer/pull/191 (using pre-release for now)
Fixes https://github.com/Polymer/internal/issues/1064
cc @andrewiggins
=> [lit-next] Set up stub tachometer benchmarks

.github/workflows/benchmarks.yml, .github/workflows/tests.yml, package.json, packages/benchmarks/lit-element/stub1/tachometer.json, packages/benchmarks/lit-html/kitchen-sink/tachometer-nop-update.json, packages/benchmarks/lit-html/kitchen-sink/tachometer-render.json, packages/benchmarks/lit-html/kitchen-sink/tachometer-update.json, packages/benchmarks/lit-html/kitchen-sink/tachometer.json, packages/benchmarks/package-lock.json, packages/lit-element/package-lock.json, packages/lit-html/package-lock.json, packages/lit-html/package.json
This change seems to fix playwright test problems (I've got at least 10 successful runs lately). I _think_ the problem was https://github.com/microsoft/playwright/issues/3912, which I just filed.
`lerna bootstrap` runs with default >1 concurrency, so the `lit-html` and `lit-element` NPM dependencies were being installed at the same time. Both depend on `playwright`, which has a postinstall script that downloads the browser binaries. Often, those postinstall scripts were running at the same time, and would both be trying to e.g. download chromium to the same shared directory on the system. So one instance was changing the filesystem from underneath the other, and it would crash.
Also:
- Add caching for our `node_modules/` and playwright browser binaries folder. This lets us skip`npm …
=> [lit-next] Fix playwright test problems, also add caching

packages/lit-element/src/lib/updating-element.ts
Unnecessary since `finalize` now returns true if finalization work was done.
=> Remove hasFinalized API, decided this is unnecessary

packages/benchmarks/lit-element/stub1/stub1.html, packages/benchmarks/lit-html/kitchen-sink/index.ts
This PR makes sure there's only one performance entry with the name specified in the Tachometer config. It seems like there's a Tachometer issue in here, where it should disambiguate between marks and measures.
=> Fix benchmark measurements

packages/benchmarks/lit-html/kitchen-sink/index.ts
This also moves some non-rendering work out of measurements and makes measurements easier to profile.
=> [benchmarks] Update lit-html kitchen-sink benchmark to use real directives

packages/lit-element/src/lib/updating-element.ts
This comment was out of date. I wasn't sure what to put for the new `options` parameter though; it sort of looks like it's only there to avoid calling `getPropertyOptions`.
=> Update the comment for `requestUpdate()`.

.github/workflows/tests.yml, package.json, packages/tests/package-lock.json, packages/tests/package.json, packages/tests/web-test-runner.config.js
- Set up the rigging for Sauce with `@web/test-runner`.
- Adds Firefox 68 (ESR) on Windows to our CI.
- For now, running the sauce browsers in a separate job, because I think it's likely we'll see some failures, and it will be less disruptive if we can quickly see whether its local vs sauce that's failing.
- The other browsers still don't work, since the plugin is very new. Firefox 68 is the only one I've gotten to work from the preliminary set for lit-next. https://github.com/modernweb-dev/web/issues/472 is tracking the problems, so we'll just keep an eye on it and uncomment browsers as they start working.
- Adds a `BROWSER` environment variable, read by our wtr config. Makes it easy to pick the browsers from the commandline. You can specify Sauce ones like `SAUCE_USERNAME=polymer-devs …
=> [lit-next] Set up Sauce with Firefox ESR

.github/workflows/tests.yml, CONTRIBUTING.md
Also, makes it so the Sauce job won't fail a commit (since it's still flaky), and disables the Sauce job on forked PRs (since they can't access secrets).
Fixes https://github.com/Polymer/lit-html/issues/1306
=> [lit-next] Document manual testing

packages/lit-html/src/lit-html.ts
Warning by ESLint.
Extracted from https://github.com/Polymer/lit-html/pull/1297
=> [lit-next] Remove unneeded \

packages/lit-html/package-lock.json, packages/lit-html/package.json, packages/lit-html/rollup.config.js, packages/lit-html/src/directives/repeat.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/parts.ts
The Terser shared name cache allows us to mangle the names of properties consistently across modules, so that e.g. `parts.js` can safely access internal details of `lit-html.js`.
However, we still have to account for the problem of mangled names getting _re-used for different properties across files_, because Terser does not consult the `nameCache` to decide whether a mangled name is available or not.
For example:
```
file1:
obj.foo -> A
obj.bar -> B
file2:
obj.bar -> B (Correctly chosen from nameCache.)
obj.baz -> A (Oops, foo and baz are different properties on the same
object, but now they both have the same mangled name,
which could result in very unpredictable behavior).
```
To trick Terser into doing what we need here, we first create a giant bundle of all our code in a single file, …
=> [lit-next] Mangle more lit-html properties by fixing Terser name mangling problem

packages/lit-element/CHANGELOG.md, packages/lit-element/README.md, packages/lit-element/package.json, packages/lit-html/CHANGELOG.md, packages/lit-html/README.md, packages/lit-html/package.json
Adds `exports` configurations to the lit-html and lit-element `package.json` files, to enable users to switch between production and development mode using a Node export condition.
lit-html and lit-element next will be distributed with two builds:
1. A default minified build suitable for serving to users.
2. An optional development build, which will log additional correctness, debugging, performance etc. information to the console, suitable only during development.
The development builds are configured using a Node export condition (see https://nodejs.org/api/esm.html#esm_conditional_exports) named `"development"`.
<strike>Note: I picked `"lit-development"` over `"development"` so that it's less likely to collide with other packages that might also have a similar export condition, because …
=> [lit-next] Add NPM exports configs for lit-html and lit-element

packages/lit-element/src/lib/css-tag.ts, packages/lit-element/src/lit-element.ts
Warning by ESLint.
Extracted from https://github.com/Polymer/lit-html/pull/1297
=> [lit-next] Update interfaces to types

packages/lit-element/package.json, packages/lit-element/scripts/check-version-tracker.js
Now with modules as requested here: https://github.com/Polymer/lit-html/pull/1298#discussion_r493071519
=> [lit-next] Unify the both check-version-tracker scripts

.github/workflows/benchmarks.yml
Unfortunately we can't currently run benchmarks on PRs from forked repos, because the tachometer action reports results by posting a comment, which requires a github token that isn't available.
=> [lit-next] Disable benchmarks action on forks

packages/lit-element/src/lib/updating-element.ts
This makes this repo compliant with Bazel's TypeScript rules: https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsetse/rules/must_type_assert_json_parse_rule.ts
https://github.com/Polymer/lit-element/pull/1086#pullrequestreview-505141528
=> Add type assertion to JSON.parse().

packages/tests/web-test-runner.config.js
Small bug from https://github.com/Polymer/lit-html/pull/1362, didn't get caught because we can't run Sauce browsers on CI :sob:
=> Fix incorrect Sauce regex parsing

.github/workflows/tests.yml
Now that everything works and is up to date, I think we can add a lint step to the GitHub Actions.
Just 24 seconds:
=> [lit-next] Add lint step to the CI

packages/lit-element/CHANGELOG.md, packages/lit-element/src/test/lit-element_test.ts, packages/updating-element/CHANGELOG.md, packages/updating-element/src/test/updating-element_test.ts, packages/updating-element/src/updating-element.ts
Errors that occur during the update cycle are squelched to allow subsequent updates to proceed normally. However, they are now refired so developers have a chance to observe them. This can be done by implementing `window.onunhandledrejection`. Fixes https://github.com/Polymer/lit-element/issues/1081
=> [lit-next] Re-fires errors in update cycle asynchronously

packages/tests/web-test-runner.config.js
Recently, tests that were running on Chrome on Sauce with versions of the form `latest-N` started failing with this error being thrown on every test page: `WebDriverError: Unexpected server error.` Capitalizing `Chrome` in the browser identifier strings seems to fix them. I have no idea why. I also capitalized the others because it felt right, I guess.
=> Capitalize browser names in Sauce browser identifers.

.github/workflows/benchmarks.yml, .github/workflows/tests.yml
A deprecation warning is being printed in the "Set environment variables" step during test runs that points to this link: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Update the deprecated `::set-env` in GitHub workflows.

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
I haven't looked into the cause for the failures this exposes, but I believe they're all legitimately failing tests so we shouldn't (necessarily) wait to make them pass in this PR before merging.
=> Remove a `test.only` in the lit-html tests.

packages/labs/package-lock.json, packages/labs/package.json, packages/lit-element/package-lock.json, packages/lit-element/package.json, packages/lit-html/package-lock.json, packages/lit-html/package.json, packages/localize/package-lock.json, packages/updating-element/package-lock.json, packages/updating-element/package.json
Some packages other than `tests` depend on `@webcomponents/webcomponentsjs` directly, this PR updates them to `^2.5.0` also. I think that those packages likely shouldn't depend on the polyfills like that since, IIRC, web-test-runner will inject them, so I'm going to try removing them and possibly make a follow-up PR.
=> Update package-local versions of webcomponentsjs to ^2.5.0 .

packages/lit-html/src/platform-support.ts
webcomponentsjs includes these as of 2.5.0, which the lit-next branch is now using.
=> Remove the inline append / remove polyfills from the platform-support module.

docs/guide/03-styling-templates.md
Example function has a body, hence it doesn't have an implicit return value. An explicit return value is needed for the example to make sense.
=> Fix styleMap example

packages/localize/src_client/lit-localize.ts
Don't use `Array.fill` since IE11 doesn't support it.
=> [localize] Don't use Array.fill because of IE11

CONTRIBUTING.md, package-lock.json, packages/benchmarks/package-lock.json, packages/benchmarks/package.json, packages/benchmarks/tsconfig.json, packages/labs/tsconfig.json, packages/lit-element/tsconfig.json, packages/lit-html/.gitignore, packages/lit-html/tsconfig.json, packages/lit-ssr/tsconfig.json, packages/localize/tsconfig.json, packages/tests/web-test-runner.config.js, packages/updating-element/tsconfig.json
- Regen package-lock to pick up rollup-plugin-filesize 9.1.0
- Update most tsconfigs to target es2020.
- Update Firefox ESR in tests to latest version
=> Output ES2020

packages/localize/README.md, packages/localize/examples/runtime/src/locales/es-419.ts, packages/localize/examples/runtime/src/locales/zh_CN.ts, packages/localize/examples/runtime/xliff/es-419.xlf, packages/localize/examples/runtime/xliff/zh_CN.xlf, packages/localize/examples/transform/xliff/es-419.xlf, packages/localize/examples/transform/xliff/zh_CN.xlf, packages/localize/src/tests/analysis.unit.test.ts, packages/localize/src_client/fnv1a64.ts, packages/localize/src_client/id-generation.ts, packages/localize/src_client/tests/lit-localize.test.ts, packages/localize/testdata/xliff/goldens/tsout/es-419.ts, packages/localize/testdata/xliff/goldens/tsout/zh_CN.ts, packages/localize/testdata/xliff/goldens/xliff/es-419.xlf, packages/localize/testdata/xliff/goldens/xliff/zh_CN.xlf, packages/localize/testdata/xliff/input/xliff/es-419.xlf
This drops total `lit-localize.js` minified + brotli size from 1.09 KiB to 0.95 KiB (13.94 -> 11.25 uncompressed). The hash module by itself drops from 0.38 KiB to 0.25 KiB (4.15 -> 1.46 uncompressed).
Previously we were using a version that converted each charcode to UTF-8, but there's no reason to do that other than compatibility with other more-common UTF-8 based implementations, which isn't a requirement.
First render of 100 templates:
Also two additional changes that further drop `lit-localize.js` to 0.94 KiB (10.98 uncompressed):
- Omit the `a` version prefix from IDs. The `h` and `s` can effectively already serve as a version indicator, because if we did a V2, we could just switch to different characters, or add a prefix. This also removes a byte from each generated ID.
- Use …
=> [localize] Switch to UTF-16 version of FNV-1A hash

packages/localize/README.md
Forgot to update these examples when I dropped the leading `a` from the localize message id scheme. Doesn't really matter, but makes sense to show the real IDs.
=> [localize] README nit, update some auto IDs

packages/benchmarks/lit-html/kitchen-sink/index.ts, packages/lit-html/src/directives/class-map.ts, packages/lit-html/src/directives/style-map.ts, packages/lit-html/src/disconnectable-directive.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/parts.ts, packages/localize/src/tests/e2e-goldens-test.ts, packages/updating-element/src/css-tag.ts, packages/updating-element/src/decorators/query.ts, packages/updating-element/src/decorators/queryAssignedNodes.ts, packages/updating-element/src/updating-element.ts
Fixed a few typos, like
the the -> the
@returns -> @return
Dropped types from jsdoc, as they're now in TypeScript.
Reflowed a few comments in @param and @return for consistency.
=> Small documentation cleanups

packages/labs/package.json, packages/updating-element/package.json
Now they are in the root `package.json`.
Probably from a wrong merge.
=> [lit-next] Remove unneeded scripts

packages/lit-html/src/directives/live.ts, packages/lit-html/src/directives/unsafe-html.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/platform-support.ts, packages/lit-html/src/test/lit-html_test.ts, packages/lit-ssr/src/test/lit/render-lit_test.ts
This makes the `nothing` and `noChange` sentinels work across multiple instances of the core library.
=> Change nothing and noChange to global Symbols

packages/lit-html/src/directives/cache.ts, packages/lit-html/src/test/directives/cache_test.ts
The cache tests has a wayward `test.only` in them, hiding some failures. The directive wasn't clearing the container part at the right times, and was setting the container part's value wrong when restoring from cache. The fix should read a bit better now.
=> [lit-html] Fix cache() directive

CONTRIBUTING.md, packages/labs/rollup.config.js, packages/lit-element/rollup.config.js, packages/lit-element/src/lit-element.ts, packages/lit-html/rollup.config.js, packages/lit-html/src/directive.ts, packages/lit-html/src/disconnectable-directive.ts, packages/lit-html/src/lit-html.ts, packages/lit-ssr/src/lib/render-lit-html.ts, packages/reactive-element/rollup.config.js, packages/reactive-element/src/reactive-element.ts, rollup-common.js
We determined that our exported classes intended for user subclassing are susceptible to mangling collision if the user subclass is subsequently mangled using similar settings. This occurred in practice between our `LitElement` and `ReactiveElement` classes, but could theoretically occur with in-the-wild subclasses.
As such, this PR introduces a new convention where fields on user-subclassable base classes use a double-underscore `__` prefix. We then modify the seeded nameCache to prefix the chosen mangled name for these with a unique unicode prefix per package, which should ensure we get the benefit of minifying private class fields while minimizing the risk of collision.
=> [lit-next] Use __ for class properties and add mangling prefix

.eslintignore, .prettierignore, packages/benchmarks/reactive-element/list/index.ts, packages/lit-element/src/test/lit-element_test.ts, packages/lit-html/CHANGELOG.md, packages/lit-html/src/directives/ref.ts, packages/lit-html/src/disconnectable-directive.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts, packages/reactive-element/.gitignore, packages/reactive-element/CHANGELOG.md, packages/reactive-element/rollup.config.js, packages/reactive-element/src/controller.ts, packages/reactive-element/src/reactive-controller.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element-controllers_test.ts, packages/reactive-element/src/test/reactive-element_test.ts
- Rename Controller to ReactiveController
- Introduce ReactiveControllerHost interface
- Move controller interfaces to `reactive-controller.ts`
- Remove "Callback" suffix from connectedCallback, disconnectedCallback & reconnectedCallback
- Remove `requestUpdate()` methods from ReactiveController
- Type `ReactiveElement.updateComplete` as `Promise<boolean>`
=> Controller and DisconnectableDirective API changes

packages/lit-element/src/test/platform-support/lit-element-sd-ce-cp_test.html, packages/lit-element/src/test/platform-support/lit-element-sd-ce_test.html, packages/lit-element/src/test/platform-support/lit-element-sd_test.html, packages/lit-element/src/test/platform-support/lit-element_test.html, packages/lit-html/src/test/platform-support/lit-html-apply_test.html, packages/lit-html/src/test/platform-support/lit-html-no-wc_test.html, packages/lit-html/src/test/platform-support/lit-html-scoping-shim_test.html, packages/lit-html/src/test/platform-support/lit-html_test.html, packages/reactive-element/src/test/platform-support/reactive-element-sd-ce-cp_test.html, packages/reactive-element/src/test/platform-support/reactive-element-sd-ce_test.html, packages/reactive-element/src/test/platform-support/reactive-element-sd_test.html, packages/reactive-element/src/test/platform-support/reactive-element_test.html, packages/tests/web-test-runner.config.js
Always inject wcjs polyfill, unless <meta> opt-out is found. All .html tests use this mechanism to manually load the polyfills; avoids double polyfill loading, which was leading to errors on IE.
=> [lit-next] Fix failing IE tests

packages/lit-html/src/hydrate.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/private-ssr-support.ts, packages/lit-html/src/test/lit-html_test.ts, packages/lit-ssr/src/lib/render-lit-html.ts, packages/lit-ssr/src/test/integration/tests/basic.ts
Fix `ElementPart` when IE reorders attributes. The `attrNames` array now holds `undefined` for `ElementPart`s, and uses the same logic as `AttributePart` to ensure parts are created in the original order, despite bound attributes possibly being re-ordered.
Also adds SSR support for `ElementPart`, and adds belated SSR adds tests for `ElementPart`, `DisconnectableDirective`, and nested directives also.
Uncompressed code size when up a tad but gzip/brotli went down:
```
Name                            Size       Minified   Gzipped    Brotli    
---------------------------------------------------------------------------
lit-html.js                     6.086 KB   6.078 KB   2.759 KB   2.501 KB
lit-html.js                     6.101 KB   6.093 KB   2.758 KB   2.488 KB  
```
Fixes #1537
=> Fix ElementPart when IE reorders attrs. Fixes #1537

packages/lit-element/src/test/lit-element_test.ts, packages/reactive-element/CHANGELOG.md, packages/reactive-element/src/reactive-controller.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element-controllers_test.ts
Fixes #1539. Note, please review with `w=1` option to ignore whitespace changes.
* added to `ReactiveController` interface
* implemented in `ReactiveElement`
* also adds a test to `LitElement` for a controller directive
=> [lit-next] Adds `removeController`

packages/labs/package.json, packages/lit-element/package.json, packages/lit-html/package.json, packages/lit/package.json, packages/reactive-element/package.json
Removes the `tsconfig.tsbuildinfo` when doing `clean`. This makes repeated builds work correctly.
=> [lit-next] Fix builds by removing `.tsbuildinfo` files

packages/lit-html/CHANGELOG.md
The entry for the breaking change done by #1463 was incorrectly located under `0.13.0`, let's fix that.
=> Fix CHANGELOG entry for eventContext renaming

packages/lit-element/src/hydrate-support.ts, packages/reactive-element/src/polyfill-support.ts, packages/reactive-element/src/reactive-element.ts
`this` must always be typed.
static fields must be `@nocollapse` to behave per spec
requestUpdate logically returns a void, even if in dev mode we return an object that warns if you try to use it as a promise
the first comment in a file must be followed with two newlines before another comment may begin (yes this is silly, but 🤷‍♂️)
=> More minor compilability improvements.

packages/lit-element/.babelrc, packages/lit-element/package.json, packages/reactive-element/.babelrc, packages/reactive-element/CHANGELOG.md, packages/reactive-element/package-lock.json, packages/reactive-element/package.json, packages/reactive-element/src/decorators/query.ts, packages/reactive-element/src/test/decorators/property_test.ts, packages/reactive-element/src/test/decorators/queryAsync_test.ts, packages/reactive-element/src/test/decorators/query_test.ts
Fixes #1584, #1572.
This PR also re-enables testing under Babel compilation. This is now done in ReactiveElement and not LitElement.
=> [lit-next] Fixes `@query` with cache setting when Babel compilation is used

packages/lit-element/src/polyfill-support.ts
Internal tooling needs this. Yes this is silly.
=> Add newline after license comment

packages/lit-element/src/lit-element.ts, packages/lit-element/tsconfig.json, packages/lit-html/src/directive.ts, packages/lit-html/tsconfig.json, packages/reactive-element/tsconfig.json
This means that we won't emit declarations in .d.ts files for things annotated with @internal.
I believe this is desirable, to make it clearer to users which fields they can count on existing and which we're free to change.
This also aligns with the internal tsconfig.
=> Enable stripInternal in tsconfig

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts, packages/tests/web-test-runner.config.js
Fixes #1594 and adds support for bindings like:
```ts
html`<input .value=${v}/>`
```
=> Fix for bindings before end of self-closing tags

.eslintignore, .eslintignore-sync, .prettierignore, .prettierignore-sync, package-lock.json, package.json
The last version of ignore-sync allows global patterns.
=> [lit-next] Use new global patterns at ignore-sync

.eslintignore, .github/workflows/benchmarks.yml, .github/workflows/tests.yml, .prettierignore, .vscode/terminals.json, packages/lit-html/CHANGELOG.md, packages/lit-html/src/async-directive.ts, packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/directive.ts, packages/lit-html/src/directives/render-light.ts, packages/lit-html/src/hydrate.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/private-ssr-support.ts, packages/lit-html/src/test/directive-helpers_test.ts, packages/lit-ssr/.gitignore, packages/lit-ssr/package.json, packages/lit-ssr/src/demo/app-client.ts, packages/lit-ssr/src/demo/module.ts, packages/lit-ssr/src/lib/import-module.ts, packages/lit-ssr/src/lib/lit-element-renderer.ts, packages/lit-ssr/src/lib/render-lit-html.ts, packages/lit-ssr/src/test/integration/client/basic_test.ts, packages/lit-ssr/src/test/integration/tests/basic.ts, packages/lit-ssr/src/test/integration/tests/ssr-test.ts, packages/lit-ssr/src/test/test-files/render-test-module.ts, rollup-common.js
The main issue was that `patchDirectiveResolve` in `lit-html/private-ssr-support.ts` was patching `_resolve`, despite the fact that directives may possibly come from any version of the library.  So `_$resolve` is now in `stableProperties`.
However, it also pointed out that `lit-ssr` was directly importing `Directive` from `lit-html` and patching it, and relying on that to affect all directive instances. This is only a safe assumption if lit-ssr is only seeing Directives created with the exact same version of the library that it is importing. Although the `import-module.ts` does force module resolution for user code to use the same version, we don't necessarily want the VM-sandbox to be the _only_ environment where you can run SSR.
For this reason, this change makes lit-ssr no longer …
=> [lit-ssr] Fix usage of non-stable properties in private-ssr-support

.eslintignore, .eslintignore-sync, .prettierignore, .prettierignore-sync
Also changes the glob just to look in the top level of packages, so that it doesn't unnecessarily recurse into node_modules
=> [lit-starter-ts/js] Fix .pretterignore syncing with lit-starter templates

.github/workflows/tests.yml, packages/tests/package-lock.json, packages/tests/package.json, packages/tests/web-test-runner.config.js
Updates `@web/test-runner-saucelabs` (among other dependencies) to pull in https://github.com/modernweb-dev/web/pull/1232 (fix for https://github.com/modernweb-dev/web/issues/1216), which hopefully fixes flaky Safari tests noted in https://github.com/Polymer/lit-html/issues/1550 and https://github.com/modernweb-dev/web/pull/1258, which hopefully fixes IE11 flaky tests.
Fixes #1550.
=> [tests] Bump testing dependencies

packages/lit-html/CHANGELOG.md, packages/lit-html/README.md, packages/lit-html/rollup.config.js, packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/directives/async-append.ts, packages/lit-html/src/directives/async-replace.ts, packages/lit-html/src/directives/until.ts, packages/lit-html/src/test/directives/async-append_test.ts, packages/lit-html/src/test/directives/async-replace_test.ts, packages/lit-html/src/test/directives/test-async-iterable.ts, packages/lit/rollup.config.js, packages/lit/src/directives/async-append.ts, packages/lit/src/directives/async-replace.ts
Port from 1.x, tests are wholly unchanged apart from adding test.
Also fixes `until` to be more idiomatic by using class fields for state (noticed when comparing code).
Fixes #1610
=> [lit-html] Add asyncAppend and asyncReplace

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Replaces `\0-\x1F\x7F-\x9F ` with `\s` in the regexp that is used to match attribute names.
- Smaller is good
- Doesn't include `\0`, so Terser minification to a null byte is no longer an issue
- Doesn't regress any use-cases we can think of
See https://github.com/Polymer/lit-html/issues/1633 for discussion
=> [lit-next] Simplify lit-html attribute name regexp with \s

packages/tests/web-test-runner.config.js
This doesn't actually seem to be affecting anything. I tried out calling `querySelector` with a similarly 'broken' selector and returns the element you'd expect if the `]` was there.
=> Fix a selector that determines if the polyfills are injected into tests.

packages/lit-html/src/test/directives/async-replace_test.ts
When running in the wtr sauce iframe runner, the `delay(30)` appears to not be long enough to wait on IE11 to ensure the stacking asyncs that occur through the generators and async directives have completed. Doesn't seem to be flaky outside of the iframe runner, so probably related to setTimeout/setImmediate throttling or something.
The change in test maintains the spirit of waiting until both promises have resolved and then ensuring that the faster one was not overwritten by the slower one (which should have been discarded).
=> [lit-html] Fix IE11 asyncReplace test race condition

README.md
when running `npm run install` you'll get the following error:
```
npm ERR! missing script: install
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anthonymittaz/.npm/_logs/2021-03-08T02_05_41_926Z-debug.log
```
=> chore: npm run install isn't a valid command, update README

packages/reactive-element/CHANGELOG.md, packages/reactive-element/src/reactive-element.ts
This makes Terser inline JSCompiler_renameProperty, removing it's cost completely.
Closure will have to compile form the development build, or after a custom TypeScript build.
Also added `JSCompiler_renameProperty()` to wrap `enabledWarnings`.
Fixes #1655 by not introducing a redeclared _global_ block-scoped variable.
=> [reactive-element] Make JSCompiler_renameProperty block scoped

packages/lit-element/package.json
Fixes https://github.com/Polymer/lit-element/issues/1164
=> [lit-next] Fix typings to match module/main

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
This PR exposes the start and end marker nodes of `ChildPart` through `startNode` and `endNode` getters, like `NodePart` in Lit 1.
Fixes #1641.
=> Reintroduce `startNode` and `endNode` on `ChildPart`.

packages/lit-html/src/directive.ts
This enables us to add a forward-compatible directive.js module in lit-html 1.x
also type => interface per request of @rictic
=> [lit-html] Export Part classes from directive.js

README.md, packages/labs/task/CHANGELOG.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Adds deps and result types to Task making `.value` and `render()` a little easier to use. Also adds a `initialState` sentinel value that a task function can return to rest the task status to INITIAL.
=> [labs/task] Better typing for Task and initialState

packages/lit-html/src/directives/render-light.ts
The unescaped `<x-story>` doesn't render in the docs. 
Other formatting changes here are optional but match our style elsewhere.
=> Fix formatting of API docs

packages/reactive-element/CHANGELOG.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
=> [reactive-element] The `createRenderRoot` method is now called only once.

packages/lit-ssr/package-lock.json, packages/lit-ssr/package.json, packages/lit-ssr/src/demo/app-server.ts, packages/lit-ssr/src/test/integration/client/basic_test.ts
The tests still use the module version, but switched the demo to use the minified / legacy script version to sanity check (worked fine).
=> Update to released template-shadow-root

packages/lit-html/src/hydrate.ts, packages/lit-html/src/lit-html.ts, rollup-common.js
The expando put on the reference node was changed from `$lit$` to `_$litPart` in https://github.com/Polymer/lit-html/commit/e587a130b0bb395e6a688baaa4f64ba22b295497, causing it to be renamed to a short letter. We need to make sure that expando doesn't easily collide with user properties, so it should go in `reservedProperties`.
I added the trailing `$` to match the existing convention of reserved properties.
Fixes #1615
=> [lit-html] Add `_$litPart$` to reservedProperties and match convention

packages/lit-html/src/directives/style-map.ts, packages/lit-html/src/test/directives/style-map_test.ts
Fixes some test regressions on IE11 that snuck in with https://github.com/Polymer/lit-html/pull/1665:
* Assert `style.cssText === ''` rather than `style.getAttribute('style') === ''` since IE doesn't serialize an empty string to `style` when calling `setAttribute('style', '')`
* Reset css properties using empty string `''` rather than `null`, due to differing behavior on IE: https://developer.mozilla.org/en-US/docs/Web/API/ElementCSSInlineStyle/style#setting_styles
=> Fixes for styleMap tests on IE11

packages/lit-html/src/directives/repeat.ts
@aomarks this should allow for better API docs by declaring the overrides explicitly. We might even want to hide the actual signature which is a not-so-useful union of the other two.
=> [lit-html] Fix up repeat() signature

packages/lit-html/src/directives/if-defined.ts
This change allows the input type to propagate through to the return type. I noticed this because one our internal linters (probably lit-analyzer?) was complaining about binding `unknown` to an attribute, in a situation that looked like this:
```javascript
html`<example-element some-attribute="${ifDefined(someBoolean)}"></example-element>`
```
=> Make `isDefined` generic, rather than using `unknown`.

.gitignore, src/async-directive.ts, src/directive-helpers.ts, src/directive.ts, src/test/directives/migration-directives_test.ts, test/index.html
Add forwards compatibility for Lit 1 directives. This will allow users to write with the Lit 2 directive class syntax and also adds some files so that the we can migrate users to the new import targets and then switch them to Lit 2 rather than those changes being atomic.
Notable changes:
* `directive` can now take a `DirectiveClass` as an argument in `lit-html/directives`
* The API of the lit 2 `[a-zA-Z]+Part`s have added to `lit-html/directives`
* creation of root level:
* `async-directive.ts`
* `directive.ts`
* creation of `ChildPart`
Note: this seems to have broken lit-analyzer 1.1.9 internally, but i could not reproduce those errors externally. This seems to work just fine in lit-analyzer 1.2.0.
Additionally, usage of `ChildPart` in a directive may cause lit-analyzer to not detect …
=> [lit-html] add Lit 2 directive syntax to Lit 1

docs/guide/07-concepts.md
Grammar correction-- change "current" -> "currently" in the third paragraph of the "Javascript modules" section of the "concepts" page in the docs.
=> Correct evasive typo

packages/reactive-element/CHANGELOG.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element-controllers_test.ts
* Fixes #1731. Previously if an element adding a controller in its constructor was upgraded, the controller's `hostConnected` would be called 2x. This was because `addController` called `hostConnected` if `isConnected` was true. Now it does so only if the element `isConnected` and the `connectedCallback` has already run (noted by checking existence of `renderRoot`).
* Also fixes test for adding a controller after element boot up.
=> Ensures `hostConnected` is called only once for element upgrade or late added controllers

packages/labs/scoped-registry-mixin/package.json
Was trying to use this new package from typescript and I wasn't able to find typings for it and had a look at what was published on npm for `@lit-labs/scoped-registry-mixin` and `index.d.ts` is definitely not there. The good news is that we are publishing the `.d.ts` but under a different file name.
=> [lit-next] scoped registries typings (wrong path)

packages/lit-element/src/decorators.ts, packages/reactive-element/src/decorators.ts
I ran into this because one internal user had `import {Constructor} from 'lit-element';`. ~I also made the lit-element decorators.ts a proxy to the one in reactive-element, since they seem to be exporting the same things.~ _(Reverted. I'd rather just propose the minimal change, but could add this back in if requested.)_
=> [reactive-element] Add '@lit/reactive-element/decorators/base.js' to the grouped decorator exports.

packages/labs/scoped-registry-mixin/package.json
As per the exports map
see https://github.com/Polymer/lit-html/issues/1728
Exports points to a development scoped-registry-mixin.js but it's missing from published npm package.
```
"exports": {
".": {
"development": "./development/scoped-registry-mixin.js",
"default": "./scoped-registry-mixin.js"
}
},
````
1.0.0-pre.1
Could not load /Users/anthonymittaz/Projects/DesignSystems/mono/node_modules/@lit-labs/scoped-registry-mixin/development/scoped-registry-mixin.j
=> [labs] When publishing we also need to include some files form the development folder

.eslintignore, .eslintrc.json, .prettierignore, packages/lit-html/.gitignore, packages/lit-html/package.json, packages/lit-html/rollup-version-stability-test.config.js, packages/lit-html/rollup.config.js, packages/lit-html/src/test/version-stability_test.js, rollup-common.js
Adds a `version-stability-build` using a special rollup config that adds a `VERSION_TEST_` prefix to all non-stable mangled properties, and adds a `version-stability_test.js` that imports the normal `prod` build as well as the `version-stability-build` into the same test file, and tests various known stability-sensitive operations:
* `TemplateResult` passed to different-version `render`
* `nothing` & `noChange` passed to different-version `render`
* `Directive` passed to different-version `render`
* `Directive` passed to different version `Directive` (nested directives)
* `AsyncDirective` (with `disconnect`/`reconnect`) passed into a different-version `render`
* `repeat` directive (which makes its own parts using `directive-helpers`) passed into different-version `render`
* …
=> [lit-html] Add version-stability test

packages/lit-element/src/test/lit-element_styling_apply_test.ts, packages/lit-html/CHANGELOG.md, packages/lit-html/src/polyfill-support.ts, packages/lit-html/src/test/polyfill-support/lit-html-apply-force-polyfill_test.html, packages/lit-html/src/test/polyfill-support/lit-html-apply_html-test.ts
Under native Shadow DOM, it's critical that any ShadyCSS modified style (this is done only for @apply) be moved to the end of the template so it doesn't disturb part indices.
=> Fixes #1739

packages/lit-html/src/lit-html.ts
As there is a matching one for SVGTemplateResult, it wouldn't hurt consistency to add one for HTMLTemplateResult
This would prevent having to define types like `export declare const html: (strings: TemplateStringsArray, ...values: unknown[]) => TemplateResult<1>;`
=> [lit-html] Add and export type HTMLTemplateResult

packages/reactive-element/src/decorators/custom-element.ts
The example didn't extend LitElement or HTMLElement
=> [reactive-element] Fix @customElement() jsdoc example

packages/labs/scoped-registry-mixin/package.json, packages/labs/scoped-registry-mixin/src/scoped-registry-mixin.ts, packages/labs/scoped-registry-mixin/src/test/scoped-registry-mixin_test.ts
As the adoption of styles is done by the method createShadowRoot of ReactiveElement, we must also adopt them inside the method createShadowRoot of ScopedRegistryMixin. Otherwise, components using this mixin are not going to have the styles adopted.
=> [scoped-registry-mixin] adopt styles

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Discovered `bindingIndex` wasn't read when working on #1759
=> [lit-html] Remove unneeded bindingIndex variable

README.md, packages/lit/README.md
Slight messaging / presentation tweaks in preparation for launch, since this will be what people see when they look up `lit` on npm.
* Removed version number from heading (I couldn't find any comparable packages that included a version number)
* Grabbed the more official tagline and 1-phrase description from the monorepo
* Lightly edited intro text to de-emphasize the identity of `lit-html` as a separate thing, though resisted the temptation to make more edits further down for now
=> README tweaks

packages/labs/ssr/src/lib/render-lit-html.ts, packages/lit-html/CHANGELOG.md, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
When running in a browser that supports [TrustedTypes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types) this will create a lit-html policy and use it for blessing the content of tagged template literals before we hand it off to HTMLTemplateElement#innerHTML for parsing.
=> Add TrustedTypes support to lit-next

packages/labs/motion/CHANGELOG.md, packages/labs/motion/package.json
=> [@lit-labs/motion] Fix package.json's files section to include flip-controller.

packages/reactive-element/src/decorators/base.ts, packages/reactive-element/src/test/decorators/queryAssignedNodes_test.ts
Fixes #1789
- update argument type to `PropertyKey`
- extended decorators test to include usage
=> [reactive-element] update "name" type to "PropertyKey"

packages/labs/task/CHANGELOG.md, packages/labs/task/package.json
=> [labs/task] Add task.js to package exports

packages/labs/react/src/create-component.ts, packages/labs/react/src/test/create-component_test.tsx, packages/labs/react/tsconfig.json
=> [labs/react] Omit 'children' from element type in props

packages/localize-tools/CHANGELOG.md, packages/localize-tools/src/messages.ts, packages/localize-tools/src/modes/runtime.ts, packages/localize-tools/src/modes/transform.ts, packages/localize-tools/src/program-analysis.ts, packages/localize-tools/testdata/build-runtime-xlb/goldens/tsout/es-419.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/es-419.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/zh_CN.ts
Non-html strings with expressions need to be tagged with the `str` function. However, we had a bug where we weren't including this `str` function in the generated output, so variable substitution was not occurring in those cases.
=> [localize] Fix missing `str` tag in generated output

packages/lit-element/CHANGELOG.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
Fixes #1835.
Improves support for customizing `observedAttributes` by ensuring that `ReactiveElement.observedAttributes` is callable, allowing mixins to directly reference it.
=> Improves support for customizing `observedAttributes`

packages/reactive-element/CHANGELOG.md, packages/reactive-element/src/reactive-element.ts
`Warnings` should have been named as a singular noun phrase.
I kept the old name too, though we might want to get rid of it as the number of people relying on it is probably close to 0.
Also added some docs.
=> [reactive-element] Rename Warnings type to WarningKind. Add docs.

packages/reactive-element/src/css-tag.ts, packages/reactive-element/src/test/css-tag_test.ts, packages/reactive-element/src/test/reactive-element_styling_test.ts
Fixes #1846
Also adds a test that `unsafeCSS()` is a valid top-level style. This means that the recommended pattern for including external CSS text can be `static styles = unsafeCSS(cssText)`, without using the `css` tag.
The PR also updates the `css` tag caching to have a fast path for strings with no interpolations.
=> [reactive-element] Make unsafeCSS() use the CSSResult cache

packages/lit-html/src/test/polyfill-support/lit-html-apply-force-polyfill_test.html, packages/lit-html/src/test/polyfill-support/lit-html-apply_html-test.ts
Fixes #1777.
* Makes test call `styleElement`, which is required.
* Also removes a skipped test that is no longer supported.
=> Fix @apply tests when running under css custom properties shim.

packages/localize-tools/CHANGELOG.md, packages/localize-tools/src/modes/runtime.ts, packages/localize-tools/src/program-analysis.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/foo.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/es-419.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/zh_CN.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/build-runtime-xliff/input/foo.ts, packages/localize-tools/testdata/build-runtime-xliff/input/xliff/es-419.xlf
Fixes two bugs relating to localized template values:
1. When we generated localized templates, we replace expressions with numbers, representing the position of that value in the source template, to account for the possibility of expressions changing position (see https://github.com/lit/lit/pull/1625 for more details). However, we were incorrectly indexing using the position of the `<ph>` placeholder that *contained* the expression, instead of the index of the expression itself (note that a `<ph>` can contain any combination of HTML and zero or more placehlders). So the offsets could be wrong, and were sometimes duplicated.
2. We use the special string `_START_LIT_LOCALIZE_EXPR_${RANDOM}_` as a delimiter during internal template decomposition, but a `replace` operation was accidentally …
=> [localize] Fix duplicate and out-of-order localized template values

packages/localize-tools/CHANGELOG.md, packages/localize-tools/package.json, packages/localize/CHANGELOG.md, packages/localize/package.json
I forgot that an earlier refactoring requires an updated import from `localize-tools` to `localize`.
=> [localize] Release tools 0.3.4 and localize 0.10.2

packages/labs/motion/src/test/flip_test.ts, packages/reactive-element/CHANGELOG.md, packages/reactive-element/src/css-tag.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/css-tag_test.ts, packages/reactive-element/src/test/reactive-element_styling_test.ts
Fixes #1894
Also removes a couple of unnecessary type aliases, mainly just so we're not required to support those exports publicly.
=> [reactive-element] Change css template tag to return CSSResult

packages/reactive-element/src/css-tag.ts, packages/reactive-element/src/test/css-tag_test.ts
This might have a small perf and memory overhead improvement by not hitting a cache for small values that will just be interpolated as strings into larger CSSResults. Instead we cache just the heavy-to-compute object, the CSSStyleSheet itself.
=> [reactive-element] Don't cache CSSResults, cache style sheets

packages/lit-html/src/directive.ts
This PR is to match the new `PropertyPart` in lit-html 1.x that's being added in #1869.
=> [lit-html] Re-export `PropertyPart` from 'directive.ts'

src/directive.ts, src/test/directive_test.ts, test/index.html
This PR separates `PropertyPart` from `AttributePart` in the forward-compatible directive API. `PropertyPart` and `AttributePart` are separate types in both [1.x](https://github.com/lit/lit/blob/39a00486fee64277a630666fde08cddc9a2402c9/src/lib/parts.ts#L448) and [2.x](https://github.com/lit/lit/blob/f50dff4d9066c91cbca12c3b746dd8f7d3fb21e5/packages/lit-html/src/lit-html.ts#L1336).
=> [lit-html] Add `PropertyPart` to directives forward-compat file.

packages/reactive-element/src/decorators/custom-element.ts, packages/reactive-element/src/test/decorators/customElement_test.ts
In typescript, users can specify a private constructor to prevent
subclassing
```ts
class XFoo extends HTMLElement {
private constructor() {
super();
}
}
```
In order to support this construction with `@customElement`, we have to
switch from using `Constructor<HTMLElement>` to `Omit<typeof
HTMLElement, 'new'>`.
=> Add support for "private" custom elements

packages/benchmarks/package-lock.json, packages/benchmarks/package.json, packages/labs/motion/rollup.config.js, packages/labs/react/rollup.config.js, packages/labs/scoped-registry-mixin/rollup.config.js, packages/labs/ssr-client/rollup.config.js, packages/labs/task/rollup.config.js, packages/lit-element/rollup.config.js, packages/lit-html/rollup.config.js, packages/lit/rollup.config.js, packages/reactive-element/rollup.config.js, rollup-common.js
Add prefix to stable properties to avoid collisions with short user properties.
Also centralizes per-package class prefixes to validate prefixes aren't duplicated since the rollup configs tend to be copy/pasted and it'd be easy to forget to choose a new unique prefix for a new package.
Fixes #1925
=> Add prefix to stable properties to avoid collisions with short user properties

.changeset/beige-rules-kneel.md, packages/lit-html/src/polyfill-support.ts, packages/lit-html/src/test/polyfill-support/lit-html_html-test.ts, packages/reactive-element/src/polyfill-support.ts, packages/reactive-element/src/test/reactive-element_styling_test.ts, packages/reactive-element/src/test/test-helpers.ts
Fixes #2000: ShadyCSS's styleElement is now called before firstUpdate/update so that code in these methods can properly assume styling (including shimmed custom properties) has fully applied.
Fixes #2001: Late added styles are now retained in templates. This behavior is consistent with what happened in Lit 1 and we're electing not to change it so that users that may be relying on this (admittedly weird and not well supported) behavior are not broken.
=> Correct polyfill-support styling issues

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
=> Add a dev mode warning for templates with octal escape sequences

packages/localize-tools/CHANGELOG.md, packages/localize-tools/src/locales.ts, packages/localize-tools/src/modes/runtime.ts, packages/localize-tools/src/modes/transform.ts, packages/localize-tools/src/typescript.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/foo.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/es-419.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/zh_CN.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/build-runtime-xliff/input/foo.ts, packages/localize-tools/testdata/build-runtime-xliff/input/xliff/es-419.xlf, packages/localize-tools/testdata/build-transform-xliff/goldens/foo.ts, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/en/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/es-419/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/zh_CN/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/build-transform-xliff/input/foo.ts, packages/localize-tools/testdata/build-transform-xliff/input/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/zh_CN.xlf, packages/localize-tools/testdata/extract-xliff-fresh/goldens/foo.ts, packages/localize-tools/testdata/extract-xliff-fresh/input/foo.ts
Fixes a bug where we were not escaping `<`, `>`, and `&` characters to HTML entities when generating HTML text content in both runtime and transform mode.
cc @fetherston
=> [localize] Escape markup characters when generating HTML text content

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Change this behavior so that it removes nodes only to the given `renderBefore` node.
This should match the Lit1 behavior since `renderBefore` was not supported. Additionally, it's compatible with ReactiveElement's shimming of adoptedStyleSheets with `<style>` elements in the shadowRoot prior to rendering.
=> Change `clearContainerForLit2MigrationOnly` behavior

.changeset/cool-brooms-enjoy.md, packages/reactive-element/src/decorators/state.ts
Setting `attribute:false` is unnecessary in the `state` decorator because `ReactiveElement` itself already sets it to `false` when `state` is `true`: https://github.com/lit/lit/blob/main/packages/reactive-element/src/reactive-element.ts#L468
=> Remove unnecessary `attribute:false` assignment in `state` decorator

packages/lit-html/src/directives/cache.ts, packages/lit-html/src/directives/live.ts, packages/lit-html/src/directives/ref.ts, packages/lit-html/src/directives/until.ts, packages/reactive-element/src/decorators/custom-element.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts, packages/reactive-element/src/reactive-element.ts
Lit.dev pulls the API documentation out of the jsDoc comments. While auditing lit.dev I found some examples that aren't rendering correctly. Some of these examples also don't render correctly in the IDE. This is a small cleanup PR that unifies the example syntax.
Fixes some example code in the jsDocs on both lit.dev and hover IDE documentation, i.e.
There is two kinds of example syntax I could identify in the codebase. Inline triple backticks with a language annotation, and the `@example` attribute.
Currently lit.dev doesn't render the `@example` attribute (Filed: https://github.com/lit/lit.dev/issues/434), but does render inline code fences. Updated docs to use code fences with language declaration.
Tested manually in VS code by hovering over the properties and eyeballing the tooltips. …
=> Fix documentation examples so they have syntax highlighting

.changeset/four-pianos-marry.md, packages/lit-element/src/env.d.ts, packages/lit-element/src/polyfill-support.ts, packages/lit-element/src/test/lit-element_styling_test.ts, packages/lit-element/src/test/lit-element_test.ts, packages/lit-element/src/test/test-helpers.ts, packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/env.d.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/polyfill-support.ts, packages/lit-html/src/test/polyfill-support/lit-html-apply_html-test.ts, packages/lit-html/src/test/polyfill-support/lit-html-scoping-shim_html-test.ts, packages/lit-html/src/test/polyfill-support/lit-html_html-test.ts, packages/lit-html/src/test/test-utils/shadow-root.ts, packages/reactive-element/src/css-tag.ts, packages/reactive-element/src/env.d.ts, packages/reactive-element/src/polyfill-support.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/decorators/queryAssignedNodes_test.ts, packages/reactive-element/src/test/reactive-element_dev_mode_test.ts, packages/reactive-element/src/test/reactive-element_styling_test.ts, packages/reactive-element/src/test/test-helpers.ts
In this PR, I've removed as many declarations as I could from the `.d.ts` files as well as reverted (w/ conflict resolution) https://github.com/lit/lit/pull/1904. I think in https://github.com/lit/lit/pull/1904 I was trying to work around collisions with the polyfills' JS externs internally but, now that that is fixed, I think it was a mistake to not leave the other types (`litHtmlPlatformSupport`, etc.) on the global `Window` interface.
=> Remove unused type declarations and remove `LitExtendedWindow` and `LitExtraGlobals`.

packages/lit-html/src/directives/ref.ts, packages/reactive-element/src/decorators/event-options.ts, packages/reactive-element/src/decorators/property.ts, packages/reactive-element/src/decorators/query-all.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts, packages/reactive-element/src/decorators/query-async.ts, packages/reactive-element/src/decorators/query.ts
Issue: https://github.com/lit/lit.dev/issues/434
Lit.dev uses TypeDoc to generate documentation. While cleaning up the documentation in https://github.com/lit/lit/pull/2050 I noticed a few examples are annotated with `@example`. Unfortunately this attribute isn't understood by TypeDoc, and their documentation recommends using code blocks: https://typedoc.org/guides/doccomments/#code-blocks
Thus this PR removes the `@example` annotation which unifies our documentation to only use code fences. The vs code hover experience remains the same, but now the documentation appears on the lit.dev API pages where it was previously not rendered.
Examples appear on lit.dev and get indexed in the lit.dev search. VS code example hover experience remains the same.
Can be compared using the temporary …
=> Unify code examples by removing @example attribute.

.changeset/twelve-moons-reply.md, packages/reactive-element/src/decorators/query-all.ts, packages/reactive-element/src/decorators/query.ts, packages/reactive-element/src/test/decorators/queryAll_test.ts, packages/reactive-element/src/test/decorators/query_test.ts
Fixes #2062. To match Lit1 behavior, the `@query` decorator returns `null` (rather than `undefined`) if a decorated property is accessed before first update. Note, when the `cache` option is used, the first result is always cached and it must be either `null` or the found element. Likewise, a `@queryAll` decorated property returns `[]` rather than `undefined`.
=> @query and @queryAll return null or [] before first update

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Issues a DEV_MODE warning if a ChildPart cannot accept values because its marker nodes have been ejected from the part's `parentNode`.
Fixes #2063
=> [lit-html] Issue a DEV_MODE warning for setValue on a disconnected ChildPart

.github/workflows/tests.yml, packages/lit-html/README.md
Adds enforcing that all PR's need changesets, to streamline releases.
=> [monorepo] Add changeset to checks

.changeset/ten-jeans-hug.md, packages/lit-element/src/lit-element.ts, packages/lit-element/src/test/lit-element_test.ts, packages/lit-element/src/test/polyfill-support/lit-element-ce-sd-noPatch_test.html, packages/lit-element/src/test/polyfill-support/lit-element-sd-ce-cp_test.html, packages/lit-element/src/test/polyfill-support/lit-element-sd-ce_test.html, packages/lit-element/src/test/polyfill-support/lit-element-sd_test.html, packages/lit-element/src/test/polyfill-support/lit-element_test.html, packages/lit-html/src/directives/live.ts, packages/lit-html/src/directives/repeat.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/directives/template-content_test.ts, packages/lit-html/src/test/polyfill-support/lit-html-apply-force-polyfill_test.html, packages/lit-html/src/test/polyfill-support/lit-html-apply_test.html, packages/lit-html/src/test/polyfill-support/lit-html-no-wc_test.html, packages/lit-html/src/test/polyfill-support/lit-html-noPatch_test.html, packages/lit-html/src/test/polyfill-support/lit-html-scoping-shim_test.html, packages/lit-html/src/test/polyfill-support/lit-html_test.html, packages/lit/src/test/lit-element-bundle_test.html, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/polyfill-support/reactive-element-ce-sd-noPatch_test.html, packages/reactive-element/src/test/polyfill-support/reactive-element-sd-ce-cp_test.html, packages/reactive-element/src/test/polyfill-support/reactive-element-sd-ce_test.html, packages/reactive-element/src/test/polyfill-support/reactive-element-sd_test.html, packages/reactive-element/src/test/polyfill-support/reactive-element_test.html
In preparation for Lit 2 GA release, this PR cleans up old TODOs after an IRL scrub of them. 
The TODOs remove here were either things that are no longer applicable (i.e. bugs that were fixed), notes that should just be comments (notes to reader, but do not require follow-up action), or ideas we decided against doing/changing.
=> [all] Cleanup obsolete TODOs

.changeset/bright-keys-kick.md, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts, rollup-common.js
When we update a ChildPart for the very first time, the DOM is still in the DocumentFragment cloned from the template. However, sine we know where the fragment will be inserted, we can associate this information with the fragment so that the `parentNode` getter can look there instead.
Fixes #2032
=> Fix ChildPart parentNode for top-level parts

packages/ts-transformers/README.md, packages/ts-transformers/src/idiomatic/query-all.ts, packages/ts-transformers/src/idiomatic/query-assigned-nodes.ts, packages/ts-transformers/src/idiomatic/query.ts, packages/ts-transformers/src/lit-transformer.ts, packages/ts-transformers/src/tests/idiomatic-test.ts
Aligns transformer behavior to https://github.com/lit/lit/pull/2065 and https://github.com/lit/lit/pull/1980 by making the `@query`, `@queryAll`, and `@queryAssignedNodes` decorator return `null` / `[]` / `[]` respectively before first update, instead of `undefined`.
Also includes a fix where we were removing no-binding imports that already existed in the source. We only want to remove imports that we actually modified.
=> [ts-transformers] Return null or [] on query decorators before first update

.changeset/real-ants-notice.md, packages/lit-html/src/lit-html.ts
This is easier for users to understand what's going on and where the problem is. Upstreaming cl/369366746
=> Throw instead of rendering error on security issue

packages/ts-transformers/src/tests/constructor-cleanup-test.ts, packages/ts-transformers/src/tests/idiomatic-test.ts
This undoes the change to the ts-transformer tests in https://github.com/lit/lit/pull/2060 that enabled standard class field emit, because they are incompatible with Lit. TypeScript 3.5.X changed the default for `useDefineForClassFields` from `false` to `true` when `target: ESNext`.
=> [ts-transformers] Disable standard class fields in tests

packages/ts-transformers/src/constructor-cleanup.ts, packages/ts-transformers/src/idiomatic/custom-element.ts, packages/ts-transformers/src/idiomatic/event-options.ts, packages/ts-transformers/src/idiomatic/property.ts, packages/ts-transformers/src/idiomatic/query-all.ts, packages/ts-transformers/src/idiomatic/query-assigned-nodes.ts, packages/ts-transformers/src/idiomatic/query-async.ts, packages/ts-transformers/src/idiomatic/query.ts, packages/ts-transformers/src/idiomatic/state.ts, packages/ts-transformers/src/lit-class-context.ts, packages/ts-transformers/src/lit-file-context.ts, packages/ts-transformers/src/lit-transformer.ts, packages/ts-transformers/src/tests/constructor-cleanup-test.ts, packages/ts-transformers/src/tests/idiomatic-test.ts
**Note to reviewer**: I recommend looking at each commit separately, I tried to break it up for readability.
Transforms `@property` decorated class fields into `constructor` assignments, ***even when `useDefineForClassFields` is enabled***.
Standard class fields are not compatible with Lit, because they are defined as own-properties on the instance, which shadow the getters/setters defined on the prototype by `ReactiveElement`.
When the TypeScript `useDefineForClassFields` compiler option is `true`, these standard class field semantics are emitted, instead of the legacy behavior where class fields were emitted as `constructor` assignments. Additionally, in TypeScript 4.4, `useDefineForClassFields` became the default when `target: ESNext`.
This PR gets in front of the standard TypeScript …
=> [ts-transformers] Transform reactive properties to constructor assignments even with `useDefineForClassFields`

packages/ts-transformers/package.json, packages/ts-transformers/src/idiomatic.ts, packages/ts-transformers/src/idiomatic/localized.ts, packages/ts-transformers/src/lit-transformer.ts, packages/ts-transformers/src/tests/idiomatic-test.ts, packages/ts-transformers/src/visitor.ts
**Note to reviewer**: I recommend looking at each commit separately. There's a little refactoring here too.
Transforms:
```ts
import {LitElement} from 'lit';
import {localized} from '@lit/localize';
@localized()
class MyElement extends LitElement {
}
```
Into:
```ts
import {LitElement} from 'lit';
import {updateWhenLocaleChanges} from '@lit/localize';
class MyElement extends LitElement {
constructor() {
super(...arguments);
updateWhenLocaleChanges(this);
}
}
```
=> [ts-transformers] Transform `@localized` decorator to `updateWhenLocaleChanges()`

packages/ts-transformers/src/constructor-cleanup.ts, packages/ts-transformers/src/tests/constructor-cleanup-test.ts, packages/ts-transformers/src/tests/idiomatic-test.ts, packages/ts-transformers/src/util.ts
When synthesizing a subclass constructor, TypeScript always includes a `super(...arguments)` call.
However, it is often unnecessary to include the `...arguments` argument.
This PR updates the `constructor-cleanup` transformer to remove the `...arguments` argument when none of the ancestor classes have any parameters in their constructor.
Note this is not 100% safe, since an ancestor constructor could directly use `arguments` in its body (which we may not be able to detect because we don't have access to bodies via `.d.ts` files) but that should be fairly rare. For the main use case we're targeting (generating lit.dev samples), it seems like a reasonable readability/correctness tradeoff.
=> [ts-transformers] Clean up unnecessary `super(...arguments)` calls

.changeset/light-feet-tickle.md, packages/lit-element/src/index.ts, packages/lit-element/src/lit-element.ts, packages/lit-html/src/lit-html.ts, packages/reactive-element/src/reactive-element.ts
Adds a ` See https://lit.dev/msg/<code> for more information.` string to all warnings logged by Lit's dev mode.
Half of https://github.com/lit/lit/issues/2078. Other half is at https://github.com/lit/lit.dev/pull/465.
=> Add lit.dev short links to dev mode warnings

.changeset/khaki-grapes-shave.md, packages/labs/ssr/src/lib/dom-shim.ts
This means that `globalThis.global` will retain its Node built-ins, and `globalThis.global === globalThis` will hold, whereas before it would lose anything we didn't explicitly set on `window`, so something like `global.Promise` would be `undefined`.
This `window.global` assignment seems to have been done for compatibility with `node-fetch`, but I tried a `fetch` from the `demo/global/module.js` module, and the fetch seemed to work fine. Not sure if there is another invocation path I missed, but it seems ok?
Fixes https://github.com/lit/lit/issues/2118
cc @fetherston
=> [ssr] Don't assign DOM shim window.global to window

packages/lit-html/src/async-directive.ts
In the documentation for AsyncDirective the `part.setDirectiveConnection` method is mentioned, but in the source code, including the tests, I only see `part.setConnected`. Is that correct?
=> Fix wrong method name in docs

.changeset/hungry-shrimps-listen.md, packages/labs/react/src/create-component.ts, packages/labs/react/src/test/create-component_test.tsx
Fixes #2026
The React.HTMLAttributes type contains the built-in properties and event handlers and such, including the `onFoo` synthetic event handlers.
=> [react] Add React.HTMLAttributes to component props

packages/ts-transformers/src/constructor-cleanup.ts, packages/ts-transformers/src/lit-transformer.ts, packages/ts-transformers/src/tests/idiomatic-test.ts, packages/ts-transformers/src/util.ts
1. Updates the transformers so that we emit `static properties = { ... }` instead of `static get properties() { return { ... }; }`.
2. If there is an existing `static properties` field *or* getter, then we will augment whatever is already there with new properties, without changing the syntax.
3. Found and fixed a new weird bug that only cropped up after this change for some reason, relating to the difference between `class.decorators = []` and `class.decorators = undefined`. When `decorators` is an empty array, there is sometimes some no-op decorator transform cruft left around by the transform, like this:
```ts
MyElement = __decorate([], MyElement)
```
I believe this is due to some conditionals in the built-in transform like `if (class.decorators)` as opposed to `if (class.decorators && …
=> [ts-transformers] Emit static properties as class fields

packages/ts-transformers/src/idiomatic/property.ts, packages/ts-transformers/src/idiomatic/query-all.ts, packages/ts-transformers/src/idiomatic/query-assigned-nodes.ts, packages/ts-transformers/src/idiomatic/query-async.ts, packages/ts-transformers/src/idiomatic/query.ts, packages/ts-transformers/src/lit-file-context.ts, packages/ts-transformers/src/preserve-blank-lines.ts, packages/ts-transformers/src/tests/idiomatic-test.ts
Previously, we lost all comments attached to all decorated fields during transformation, as well as their positions within the class. Now we preserve both. For reactive properties, the comment moves to the constructor initializer, which mirrors the standard TypeScript behavior.
=> [ts-transformers] Preserve comments and position of transformed class fields

.github/workflows/benchmarks.yml, .github/workflows/tests.yml
Our CI dependency caching hasn't been working recently, because the cache got too large, so it never actually uploads, and we're wasting 10 minutes creating the cache archive. This is because we're caching all `**/node_modules` directories:
Now we just cache the `~/.npm` directory instead, using the new automatic caching setting available in `actions/setup-node@v2` (https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies).
`~/.npm` will contain all of the de-duplicated NPM package tarballs, instead of all of the duplicated extracted files. Also, even when caching was working before, we were probably wasting a lot of bandwidth downloading and uploading duplicated install directory files, plus a lot of cycles archiving and compressing all of …
=> [all] Cache ~/.npm instead of **/node_modules

.changeset/twelve-squids-appear.md, packages/lit-html/src/test/lit-html_test.ts
Fixes #1541 
This is just some assurance that `setValue()` works synchronously as well, since we don't want to add code to prevent it .
=> [lit-html] Add test for sync AsyncDirective.setValue() call

.changeset/hip-badgers-tan.md, packages/labs/ssr/LICENSE, packages/lit-html/LICENSE
This adds a `LICENSE` file to the `lit-html` and `@lit-labs/ssr` packages. I think when the repo was originally changed from a single package to multiple packages (#1206), the license for `lit-html` was left at the root, so I copied it back down with the same date. I've added a new one for `@lit-labs/ssr` using 2021.
Fixes #2089.
=> Add licenses for `lit-html` and `@lit-labs/ssr`.

.changeset/pretty-hotels-taste.md, packages/benchmarks/package-lock.json, packages/benchmarks/package.json, packages/lit-element/src/env.d.ts, packages/lit-element/src/lit-element.ts, packages/lit-element/src/polyfill-support.ts, packages/lit-element/src/test/polyfill-support/lit-element-ce-sd-noPatch_test.html, packages/lit-element/src/test/test-helpers.ts, packages/lit-html/src/env.d.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/polyfill-support.ts, packages/lit-html/src/test/polyfill-support/lit-html-noPatch_test.html, packages/reactive-element/src/env.d.ts, packages/reactive-element/src/polyfill-support.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_dev_mode_test.ts, packages/reactive-element/src/test/test-helpers.ts, rollup-common.js
Fixes #2142. Allows users to a dev and prod versions of Lit that both support `polyfill-support` via loading dev and prod versions of `polyfill-support`. Previously only 1 `polyfill-support` was allowed.
Note, this also changes the globals used from the older `PlatformSupport` to `PolyfillSupport`.
=> Add dev mode specific versions of `polyfill-support`

.changeset/great-walls-clap.md, packages/lit-element/src/lit-element.ts, packages/reactive-element/src/reactive-element.ts
Add some documentation for some public undocumented methods in lit-element and reactive-element. Addresses github issue: https://github.com/lit/lit/issues/1883
Used lit.dev documentation to guide the jsdocs, and addressed some class members that had no documentation on the lit.dev/docs/api pages.
Added some documentation for previously undocumented:
- `LitElement.connectedCallback()`
- `LitElement.disconnectedCallback()`
- `ReactiveElement.hasUpdated`
- `ReactiveElement.addController`
- `ReactiveElement.removeController`
Tested with mouse over in VsCode.
Thank you!
=> Expand jsdoc documentation for reactive-element and lit-element.

packages/lit-html/src/lit-html.ts
Addresses github issue: https://github.com/lit/lit/issues/1883
Documenting lit-html's `html` and `nothing`. The API documentation is sparse so I've borrowed heavily from the original [lit-html polymer website](https://lit-html.polymer-project.org/guide/writing-templates).
Let me know if there is too much (especially in the `html` tag case) and if we only want to keep a smaller amount or something different. Intent was to share that there isn't string concatenation going on under the hood.
Identified as currently on lit.dev there is minimal documentation and they are heavily used in Lit: https://lit.dev/docs/api/templates/
Tested with mouse over in VsCode.
Thank you!
=> Additional documentation for `html` and `nothing`

.changeset/strange-experts-do.md, .eslintignore, .prettierignore, packages/labs/motion/.gitignore, packages/labs/motion/package.json
* Fixes #2184 by ensuring `*.d.ts` files are included in the production output.
* Makes `package.json` similar to other `@lit-labs` packages.
=> [@lit-labs/motion] Ensure `*.d.ts` files are included with production output

.changeset/spicy-shirts-repair.md, packages/lit-element/src/lit-element.ts, packages/lit-element/src/polyfill-support.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/polyfill-support.ts, packages/reactive-element/src/polyfill-support.ts, packages/reactive-element/src/reactive-element.ts
These dynamic lookups cause their expression to have an implicit `any` type, which is disallowed internally.
=> Remove dynamic naming for `DEV_MODE` polyfill support functions.

.github/workflows/release.yaml
Hopefully this fixes the error in the release workflow.
Husky docs: https://typicode.github.io/husky/#/?id=bypass-hooks
=> Skip Husky in the release workflow

.github/workflows/release.yaml, package.json, packages/lit-element/src/lit-element.ts, packages/lit-html/src/lit-html.ts, packages/reactive-element/src/reactive-element.ts, scripts/update-version-variables.js
Part of #2178
This script runs after `changeset version` and copies the new versions into the source files that have these global version variables.
=> Add script to update global version variables

.changeset/tasty-zebras-double.md, packages/labs/ssr/src/lib/render-lit-html.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
This allows callers to see what tags are rendered as they are streamed. An important use case is to enable on-demand bundling of just the modules required to hydrate the page or a subset of the page.
=> [ssr] Add customElementRendered callback

.changeset/metal-news-sin.md, packages/lit-starter-js/index.html, packages/lit-starter-js/web-dev-server.config.js, packages/lit-starter-ts/index.html, packages/lit-starter-ts/web-dev-server.config.js
Currently you cannot serve your component from the starter kit. You always get the generated docs.
This change makes it so when you run `npm run serve`, you get your component. Docs are still available via the `nom run docs:serve` command.
Currently: `npm run serve` and `npm run docs:serve` give you the same output.
Because it's confusing and has resulted in the following efforts to fix:
- https://github.com/lit/lit-element-starter-ts/issues/58
- In the linked video: https://www.youtube.com/watch?v=86tet76u0uk&ab_channel=MiklosNemeth , they are unable to figure out how to serve their component. This is fixed by this change.
- This PR on the original repo: https://github.com/lit/lit-element-starter-ts/pull/57 fixes the serve command explicitly.
1. Make a new template based on the starter …
=> [starter-kits] Fix starter kits so `npm run serve` isn't `npm run docs:serve`

.changeset/empty-cobras-lick.md, packages/reactive-element/src/reactive-element.ts
Changed `willUpdate()` to be `protected`, same as related hooks: `update()`, `updated()` and `firstUpdated()`.
Fixes #2266 
Main question: should we consider this change safe for a patch release? It might break someone's code 🤔
=> fix: make willUpdate lifecycle hook protected

package-lock.json, package.json, src/test/lib/shady-render_test.ts, tsconfig.json
Part of getting the lit 1.x API docs running on the new site. We will analyze the lit-html-1.x branch from the lit.dev repo using a more recent version of TypeScript, so we need it to compile with no errors.
- Exceptions are `unknown` instead of `any` since 4.4 (https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables). Fixed with some casts.
- `document.createTreeWalker` interface changed (https://github.com/microsoft/TypeScript/issues/33462). Fixed by installing `@types/web-ie11` which adds the legacy signature back.
=> [lit-html-1.x] Type fixes for TypeScript 4.4

.changeset/red-cows-trade.md, .eslintignore, .gitignore, .prettierignore, packages/lit-html/src/lit-html.ts, packages/lit-html/src/static.ts, packages/lit-html/src/test/lit-html_test.ts
This makes it much harder for untrusted values in a databinding to masquerade as internal lit types. Specifically, this ensures that a template result value can't be obtained from JSON.parse.
Fixes #2306
=> Add an additional template object check

.changeset/famous-feet-kneel.md, packages/labs/ssr/package.json, packages/lit-element/package.json, packages/lit-element/src/decorators.ts, packages/lit-element/src/decorators/query-assigned-elements.ts, packages/lit/package.json, packages/lit/src/decorators.ts, packages/lit/src/decorators/query-assigned-elements.ts, packages/reactive-element/package.json, packages/reactive-element/src/decorators.ts, packages/reactive-element/src/decorators/query-assigned-elements.ts, packages/reactive-element/src/test/decorators/queryAssignedElements_test.ts, packages/ts-transformers/README.md, packages/ts-transformers/src/idiomatic-decorators.ts, packages/ts-transformers/src/internal/decorators/query-assigned-elements.ts, packages/ts-transformers/src/tests/idiomatic-decorators-test.ts
Fixes: https://github.com/lit/lit/issues/2292
Adds `queryAssignedElements` decorator and tests (that similarly match the `queryAssignedNodes` tests).
This change proposes a new options bag API which lets us avoid needing to use and empty string if targeting an unnamed slot.
Note that there is temporarily an asymmetry between this decorator and `queryAssignedNodes` which will be addressed with https://github.com/lit/lit/issues/2332.
- The first commit introduces the new decorator, with tests matching closely what the `queryAssignedNodes` tests. In fact the fixture is almost identical.
- Then I add the imports closely following the `query-assigned-nodes` references in the codebase.
- Finally I updated the ts-transformer such that it can transform queryAssignedElements into JS.
Change is …
=> [reactive-element] Add queryAssignedElements decorator

.changeset/khaki-squids-join.md, packages/labs/ssr/src/lib/element-renderer.ts, packages/labs/ssr/src/lib/render-lit-html.ts, packages/labs/ssr/src/test/integration/tests/basic.ts
Fixes a bug where static attributes on custom elements would not render if the custom element was unregistered or did not have a renderer.
I considered a few ways to solve this and picked [2]. Open to switching to [1] or doing something else:
1. Don't emit `custom-element-*` opcodes at all for un-renderable elements. However, this would make `getTemplateOpcodes` dependent on `renderInfo`, and it seemed kind of nice to preserve the feature of `getTemplateOpcodes` being only a function of the template. If we did this, seems like we'd want to add the renderer `instance` to the `custom-element-open` opcode, so that we don't look up the renderer twice.
2. Add a new `FallbackRenderer` class which just tracks and renders attributes. **This is what I picked**, since it seemed pretty undisprutive, …
=> [ssr] Fix unknown element attribute rendering

.changeset/famous-cows-shout.md, packages/lit-html/src/directives/keyed.ts
This file is missing a license header.
=> Add a license header to the `keyed` directive.

.changeset/hot-penguins-behave.md, packages/reactive-element/src/decorators/query-assigned-elements.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts, packages/reactive-element/src/test/decorators/queryAssignedNodes_test.ts, packages/ts-transformers/src/internal/decorators/query-assigned-elements.ts, packages/ts-transformers/src/internal/decorators/query-assigned-nodes.ts, packages/ts-transformers/src/tests/idiomatic-decorators-test.ts
Addresses: https://github.com/lit/lit/issues/2332 and https://github.com/lit/lit/issues/2171
Following the inclusion of [queryAssignedElements](https://github.com/lit/lit/pull/2327), this change adds a new API and deprecates the old `@queryAssignedNodes` API.
Note the new `queryAssignedNodes` options does not include `selector`.  If using `selector` please use `@queryAssignedElements`. `@queryAssignedNodes('', false, '.item')` is functionally identical to `@queryAssignedElements({slot: '', flatten: false, selector: '.item'})` or `@queryAssignedElements({selector: '.item'})`.
- Updated the interface in both TypeScript and jsdocs to deprecate the previous API, and document the new API. The deprecated API contains information about upgrading to use the new API and also mentions …
=> [reactive-element] New queryAssignedNodes API and deprecate current API

.changeset/fresh-eggs-check.md, packages/labs/ssr/package-lock.json, packages/labs/ssr/package.json, packages/labs/ssr/src/lib/element-renderer.ts, packages/labs/ssr/src/lib/render-lit-html.ts, packages/labs/ssr/src/lib/util/escape-html.ts
The `escape-html` package is not an ES module, and it's a pretty trivial function to just write ourselves. See https://unpkg.com/browse/escape-html@1.0.3/index.js for reference. This new implementation should have the exact same output.
Advantages: getting rid of the only non-esm dependency helps with running SSR in deno and service-workers, and drops our dependency surface area and package size.
Fixes https://github.com/lit/lit/issues/1998
=> [ssr] Replace escape-html dependency with our own version

.changeset/smooth-tigers-train.md, .changeset/thick-tips-serve.md, packages/labs/task/README.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes #2323 and #2317.
* Tasks automatically run whenever their arguments change. A task with no arguments does not run; a task with an empty array of arguments runs once; otherwise tasks runs when its arguments array members differs from is previous arguments. 
* The automatic running of tasks based on arguments can be disabled by setting `autoRun` to `false`. This can be done via the task config or by setting the property on the task itself.
* Call `run()` (optionally specifying task arguments) to explicitly run the task.
=> [@lit-labs/task] Refines when tasks are run

.changeset/brave-planes-juggle.md, packages/reactive-element/src/decorators/query-assigned-elements.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts
Raised in https://github.com/lit/lit.dev/pull/623
This change makes the link to the options object clearer for both queryAssignedElements and queryAssignedNodes.
Initially wanted to link from the `@param options` jsdoc, but it's not yet supported on Lit.dev.
It's easier to document this currently with the TypeScript types and a link in the description documentation. Once https://github.com/lit/lit.dev/issues/503 is addressed we can update this with `@link` and `@param` providing the best of both worlds. 
Tested manually with lit.dev api generation.
This now shows up like so and the link can be clicked. Information is de-duped:
=> Improve docs to more clearly link to the options interface for queryAssignedNodes

.changeset/brown-swans-flow.md, packages/lit-element/rollup.config.js, packages/lit/rollup.config.js, packages/reactive-element/rollup.config.js
We forgot to update the `rollup.config.js` files to include the new `query-assigned-elements.js` decorator file in the NPM packages.
May help with https://github.com/lit/lit/issues/2383, but I think this is a new problem on top of an existing Deno-related problem with Skypack.
=> Fix missing decorators/query-assigned-elements.js file

.changeset/twelve-yaks-hide.md, packages/labs/ssr/package.json
Not sure why this was pinned to 1.1.0 -- it should use a ^ range like everything else.
=> Add missing caret to SSR's reactive-element dependency range

.changeset/chilly-buckets-rescue.md, packages/lit-html/src/directives/choose.ts
Fix missing html tagged template literals in the choose example code.
Mirrors: https://github.com/lit/lit.dev/pull/640.
=> Fix choose directive jsdoc example code

.changeset/stupid-rockets-deliver.md, packages/reactive-element/src/decorators/query-assigned-elements.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts
Internally queryAssignedElements was using the newer `HTMLSlotElement.assignedElements` method. This newer method doesn't have ShadyDOM polyfill support, but would still leave some browsers unsupported if it did have polyfill support.
Using [Modern browser breakdown](https://lit.dev/docs/tools/requirements/#modern-browser-breakdown) as a guide, `assignedElements` is not supported until Firefox 66. This leaves Firefox versions 64 and 65 without support.
tl;dr `queryAssignedElements` doesn't work on older browsers.
Gracefully fallback on `assignedNodes` if required.  The behavior of the decorator remains unchanged.
This is a private implementation change, so the existing unit tests should cover this. No functional changes.
Also testing via cl/420366110
Size of decorators before changes (on …
=> Improve queryAssignedElements decorator browser compatibility

.eslintignore, .github/workflows/release.yaml, .gitignore, .prettierignore, package.json, scripts/extract-published-lit-version.js
This PR adds a couple new steps to the release workflow which will push bundles to the [lit/bundles](https://github.com/lit/bundles) repo. New bundles are pushed whenever `lit` appears in [the `publishedPackages` output of `changesets/action`](https://github.com/changesets/action#outputs). lit/bundles currently contains a single empty commit with tag `empty`; the new steps check out the repo at that commit, copy in the bundles and their source maps, and then create and push a new commit tagged with the version of `lit` that was published.
[lit/bundles](https://github.com/lit/bundles) is currently private in case we need to trash the entire repo and try again. Also, this PR should finish the work for #2272, but I don't want to give GitHub the actual auto-close-on-merge phrase since we …
=> Push bundles to lit/bundles during release.

.github/workflows/add-issues-to-project.yml
Adds a GitHub action that automatically adds newly filed issues to the Lit project. See https://github.com/peter-evans/create-or-update-project-card for documentation.
=> Add GitHub action that auto adds new issues to Lit project

.github/workflows/add-issues-to-project.yml
I've created a new https://github.com/lit-robot account and added a personal access token (PAT) to the Lit org's secrets. We can use this for other general purpose automation too if needed. 
This is required for the action that automatically adds newly filed issues to the Lit project board because the default `GITHUB_TOKEN` token only has permission for this repo, not for the whole org, but our project board is org-scoped.
=> Use new lit-robot PAT for automating adding issues to Lit project

.github/workflows/add-issues-to-project.yml
Turns out https://github.com/peter-evans/create-or-update-project-card doesn't support the new beta versions of projects. I found a similar library that does: https://github.com/leonsteinhaeuser/project-beta-automations. Switching to that.
=> Use a different GitHub action for project issue automation

.github/workflows/release.yaml
I think that inserting a completely blank line in an indented YAML block requires explicitly filling in the indentation at the front with leading spaces for each blank line, which I didn't do when originally adding these workflow steps. In this PR, I've opted to remove them instead of adding whitespace because whitespace-only lines are not obvious without configuring your editor and they were only used before comments, which already provide some separation on their own.
Another point for Team Significant Whitespace Is Bad.
=> Remove completely blank lines in YAML blocks in workflows.

.github/workflows/add-issues-to-project.yml
The workflow I was trying from https://github.com/leonsteinhaeuser/project-beta-automations didn't work (filed https://github.com/leonsteinhaeuser/project-beta-automations/issues/27).
But I realized we could use the graphql API directly to get more control here. This new action is based on the example at https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#example-workflow-authenticating-with-a-personal-access-token, just slightly modified and simplified.
I've tested this in my personal repo and it works, so hopefully it will work for us too.
=> Use graphql API directly to automate adding issues to project

packages/lit/src/index.all.ts
The polyfill support module is only useful in contexts where this ES2019 bundle won't work and the decorators are very unergonomic without TypeScript and have JS equivalents.
=> Remove the polyfill support module and decorators from the 'all' bundle.

packages/benchmarks/package-lock.json, packages/benchmarks/package.json
Our benchmarks CI has recently broken as the chrome version has exceeded the chrome driver.
I.e. see example error: https://github.com/lit/lit/runs/4899938143?check_suite_focus=true#step:12:41
Error pasted: `SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 95`
Reproduced the error locally, and fixed by updating package.json and package-lock.json.
Expect this PR to fix the Benchmarks/benchmarks github action.
Internal dev dependency update for benchmarking. Risk should be low.
This is an internal tooling update - I don't think this needs a changelog.
=> [chore] Fix package/benchmarks by updating chromedriver and package-lock

.changeset/wise-taxis-refuse.md, packages/lit-element/src/lit-element.ts, packages/reactive-element/src/css-tag.ts, packages/reactive-element/src/decorators/property.ts, packages/reactive-element/src/decorators/query-assigned-elements.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts, packages/reactive-element/src/reactive-element.ts
Currently we support [[`symbol`]] in our documentation to create an automated hyperlink in our generated lit.dev API documentation. However [[`symbol`]] isn't recognized by VS code and ends up being rendered directly into the documentation.
Instead if we use `{@link symbol}` or `{@linkcode symbol}` then we get automatic hyperlinks and jump to definition in the IDE hover documentation if the linked symbol is in scope. If the symbol is not in scope the IDE experience is similar to currently where the link text is directly printed into the documentation.
This change should follow lit.dev's change https://github.com/lit/lit.dev/pull/629 which adds logic to handle transforming `@link` and `@linkcode`.
This was tested manually by hovering over the symbols, and using this PR to generate Lit.dev …
=> Replace jsdoc symbol links with @linkcode instead of square brackets

.changeset/many-singers-complain.md, .changeset/modern-seas-jog.md, packages/localize-tools/src/formatters/xlb.ts, packages/localize-tools/src/formatters/xliff.ts, packages/localize-tools/src/messages.ts, packages/localize-tools/src/modes/runtime.ts, packages/localize-tools/src/modes/transform.ts, packages/localize-tools/src/program-analysis.ts, packages/localize-tools/src/tests/analysis.unit.test.ts, packages/localize-tools/src/tests/transform.unit.test.ts, packages/localize-tools/src/typescript.ts, packages/localize-tools/testdata/build-runtime-xlb/goldens/xlb/es-419.xlb, packages/localize-tools/testdata/build-runtime-xlb/input/xlb/es-419.xlb, packages/localize-tools/testdata/build-runtime-xliff/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/build-runtime-xliff/input/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xlb-fresh/goldens/xlb/en.xlb
Fixes #2140 and #1897.
- For messages to be considered same:
- No longer check for expressions to be identical.
- Do check that desc be identical.
- Display a more helpful aggregate error message for all messages with the same id.
- For XLB format, add placeholder index to `name` attribute of `<ph>` tags.
- Utilize the placeholder indexes embedded in tags for determining placeholder locations during transform mode.
=> [localize-tools] Improve handling of duplicate msg id

.github/workflows/release.yaml
Add step in release workflow to remove old version of prettier to fallback to our version.
The old version of prettier handles formatting of nested javascript differently.
=> Add step to remove old version of prettier during release

.changeset/eight-falcons-rhyme.md, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Fixes #2441
I didn't add an SSR-specific test because it's evident that the problem is with `<title>` elements in general and the test for `<title>` was broken before the fix was applied.
=> Fix bug with bindings inside of <title> elements

packages/lit/rollup.config.js, rollup-common.js
By default, the paths in the source map are relative paths from the bundle to the included sources as they were on disk at the time the bundle was generated. This causes the developer tools to display the original sources at seemingly unrelated locations. This PR transforms them so that the original locations appear to be in a single directory with the same name as the bundle with the same structure as the `packages` directory.
For example, rather than the source map for `lit.min.js` saying that the main `lit-html` entrypoint is located at `../lit-html/src/lit-html.ts`:
```
+ lit-html (generated by source map)
| + src
|   + lit-html.ts
+ lit-element (generated by source map)
| + ...
+ dir-with-bundle
+ lit.min.js
```
It will say that it is at `./lit.min.js/lit-html/src/lit.html.ts` …
=> Provide better paths for sources in the bundles' source maps.

.github/workflows/release.yaml
This way we don't have to worry about name conflicts if we end up wanting to make the static, unbundled builds we were thinking about later.
=> Put each bundle into separate folders.

.github/workflows/release.yaml
Update changesets to use the new `lit-robot` account instead of the default github actions account. This should fix CLA problems.
Fixes https://github.com/lit/lit/issues/2452
=> Use lit-robot for changesets commits

.changeset/mighty-birds-jog.md, packages/reactive-element/src/decorators/query-assigned-nodes.ts
Fixes issue: https://github.com/lit/lit.dev/issues/670
Documentation only change.
=> [reactive-element] Fix type signature in queryAssignedNodes JSDoc code example.

.changeset/sweet-emus-run.md, packages/reactive-element/src/decorators/event-options.ts, packages/reactive-element/src/decorators/query-assigned-elements.ts, packages/reactive-element/src/decorators/query-assigned-nodes.ts, packages/reactive-element/src/reactive-element.ts
Part of https://github.com/lit/lit/issues/1883#issuecomment-1018777254
This PR was originally to make some minor fixes to the reactive-element code samples, but I expanded it slightly to also include documentation for `willUpdate`, `firstUpdated`, and the `attributeChangedCallback`.
The documentation updates are scoped to the reactive-element package.
=> [reactive-element] Expand jsdoc documentation, and misc code sample syntax fixes.

packages/labs/router/src/test/router_test.ts
Fixes https://github.com/lit/lit/issues/2468
There are currently 3 red router tests on ie11 breaking our sauce-ie11 tests.
Fixed by skipping labs/router tests on ie11. I don't know if we run the ie11 router tests with shadydom polyfill.
This change is a test only change and should result in an sauce-ie11 green run.
=> [labs/router] Skip tests on ie11

packages/labs/router/README.md
Just saw that `length` was written `langth` while reading the readme :)
=> [@lit-labs/router] Fix typo in readme

packages/lit/src/index.all.ts
This makes the case consistent between these two items renamed on re-export and matches the convention used in `static.ts`:
https://github.com/lit/lit/blob/cdc9ee3117fe015b036c6592970e250d724f85a1/packages/lit-html/src/static.ts#L10
=> [bundles] Update `staticSvg` case to match `staticHtml`.

packages/labs/eleventy-plugin-lit/demo/_js/package.json, packages/labs/eleventy-plugin-lit/src/index.ts, packages/labs/eleventy-plugin-lit/src/test/eleventy-plugin-test.ts
Trims Lit SSR `` and `<?>` marker comments before and after the top-level synthetic template that is rendered for each Eleventy HTML file. I believe these serve no purpose, since the top-level template that we synthetically render could never be hydrated.
This also avoids the problem of marker comments appearing before `<!doctype>` declarations, which I think may have been why we had some special handling around trying to detect or synthesize `<body>` tags previously. So I was able to remove this part of the code as well.
Also includes some miscellaneous minor cleanup.
Part of https://github.com/lit/lit/issues/2352
=> [@lit-labs/eleventy-plugin-lit] Remove unnecessary marker comments

.changeset/hip-buses-allow.md, packages/labs/eleventy-plugin-lit/README.md, packages/labs/eleventy-plugin-lit/src/index.ts, packages/labs/eleventy-plugin-lit/src/test/eleventy-plugin-test.ts, packages/labs/ssr/src/lib/module-loader.ts, packages/labs/ssr/src/lib/render-module.ts
- Switches from global rendering to isolated VM modules.
- This allows Eleventy `--watch` mode to work. Fixes https://github.com/lit/lit/issues/2476
- Fixes a bug in `ModuleLoader` where we would fail to resolve lit-related modules because of the use of a ` file://` URL where a path was required. Refactored variable names to make this clearer.
- Switch to `fileURLToPath` and `pathToFileURL` instead of manual `file://` string manipulation in `ModuleLoader` to convert between paths and file URLs, because those functions handle escaping correctly.
- Refactored to use `eleventyConfig.on('eleventy.before')` to de-duplicate work that can be done per-build versus per-html-file.
=> [@lit-labs/eleventy-plugin-lit] Use VM modules and fix path vs url bug

.changeset/silly-donuts-sit.md, packages/lit-html/src/lit-html.ts
Addresses issue: https://github.com/lit/lit.dev/issues/652
Also addresses generated docs for `svg`: https://github.com/lit/lit/issues/1883#issuecomment-1018777254
This is a documentation only change to guide correct usage of the svg tagged template literal. Currently it's easy to reach for this whenever anything svg related comes up.
Instead of going into the implementation details for how the `svg` TTL copies the fragment into an `<svg>` element and then copies that fragment over, I've instead focussed on correct usage and provided an example that shows both an svg fragment and complete svg element.
Test of the code example: [Lit Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgc3ZnfSBmcm9tICdsa …
=> [lit-html] Add svg tagged template literal documentation

.changeset/friendly-llamas-laugh.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
Fixes #2481 
This is technically a breaking change in that:
```ts
class E extends LitElement {
declare foo: number;
update(changedProperties: PropertyValues<this>) {
changedProperties.get('bar'); // Error
}
}
```
This should be an ok breaking change as it catches a legitimate problem. The thing to look out for here is whether this causes unexpected breaks. I don't quite understand what the conditional type was doing here, but since one branch was `never`, removing that should't cause any new errors.
=> Better types for PropertyValues<T>

.changeset/curvy-candles-drum.md, packages/lit-html/src/lit-html.ts
Include Justin's feedback on https://github.com/lit/lit/pull/2479.
Link to feedback: https://github.com/lit/lit/pull/2479#discussion_r799829808
Replace 'rare' with 'invalid' and reflow markdown
=> [lit-html] svg tag function JSDoc replace 'rare' with 'invalid'

.github/workflows/release.yaml
Starting to look into https://github.com/changesets/action/issues/149. One thing I noticed is that release is running on Node 14, whereas our other actions run on 16.
=> [meta] Upgrade release workflow to Node 16

.github/workflows/release.yaml
As suggested in https://github.com/changesets/action/issues/149#issuecomment-1032005802
=> [meta] Use changesets/action@v1 instead of master

.eslintignore, .github/workflows/release.yaml, .prettierignore, packages/lit/.gitignore, packages/lit/rollup.config.js
When I copied the `cp ...` lines used to import the bundles, I didn't add the `.map` suffix to the lines that copy the source maps, so they overwrote the bundles. This PR copies both using their original names but also causes them to be emitted initially with the final names, which fixes another bug where the simple renaming would have broken the association with the source map.
=> Fix a bug in the bundle release script. Rename bundles properly.

.github/workflows/release.yaml
For some surprising reason, changing the `id` of the changesets step in our release workflow from `"changesets"` to *anything else* (I picked `"cs"`) fixes the problem where the step is invisible from the list of steps in the GitHub UI.
See https://github.com/changesets/action/issues/149
=> [meta] Fix invisible changeset step in release action by changing its id

.changeset/silent-carrots-sneeze.md, packages/labs/ssr/src/lib/dom-shim.ts
Addresses part of the problem surfaced by #2393.
The proxy was causing unexpected behavior when attempting to assign to `window.global` after the shim is installed. Making `globalThis.window` a reference to `globalThis` should achieve the same thing the proxy was meant to handle.
=> [ssr] Replace window proxy in global DOM shim

.github/workflows/release.yaml
I assumed this output was a boolean, but it seems like it's actually a string, which caused these steps to run more often than necessary.
https://github.com/lit/lit/runs/5097992845?check_suite_focus=true#step:8:21
Fixes #2514.
=> The `published` output of the changesets action is the string 'false'.

.changeset/dull-hotels-brake.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
Fixes https://github.com/lit/lit/issues/2513
This still preserves the new behavior of strongly-typed Maps when the type parameter is specified, so there still could be some breaks for cases where people use `PropertyValues<this>` but then access keys that are not in the type. These _should_ be invalid uses that we want to catch, but we need to be on the lookout for unexpected breaks or ones that aren't easily fixable.
=> Fix PropertyValues<any> to be compatible with Map<string, string> and subtyping

.github/workflows/add-issues-to-project.yml, .github/workflows/benchmarks.yml, .github/workflows/release.yaml, .github/workflows/sauce-ie11.yaml, .github/workflows/sauce.yaml
Our fork-disabling logic didn't work in most places, and was missing entirely in one. Use a simpler and more effective approach consistently.
=> [meta] Disable actions on forks more effectively

.github/workflows/release.yaml
Apparently, `working-directory` is only applicable to jobs that use `run` and not those that specify an action with `uses`. Fortunately, changesets/action supports [a `cwd` input](https://github.com/changesets/action#inputs) for the same purpose.
Here's where `working-directory` is mentioned in the docs:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrun
=> `working-directory` only works for steps with `run`. Use `with.cwd` instead for `changesets/action`.

.changeset/shy-grapes-stare.md, packages/lit-starter-js/README.md, packages/lit-starter-ts/README.md
I'm going to transfer all of the issues in the starter kit repos to this one and then disable issues. These links should help people find the original repo so they know where to file issues if they need to.
Part of #2536.
=> [starter-kits] Add a link to the starter templates so users will know where they should file issues.

.github/workflows/release.yaml
`changesets/action@v1` has a bug where it attempts to set the git user info locally before changing to the directory specified with `cwd`.[^1] This means that it will fail at this step if the root directory is not a git repo. To work around this, this PR initializes a new git repo in the root directory and sets Lit Robot's git user info globally.
Fixes #2539.
[^1]: https://github.com/changesets/action/blob/898d125cee6ba00c6a11b6cadca512752c6c910c/src/index.ts#L19-L34
=> Work around a `changesets/action` bug with its `cwd` option.

.github/workflows/release.yaml, package.json
This also removes the `extract-published-lit-version` from the repo's npm scripts and adds an explicit exit code to the `exit`.
=> The bundle push step no longer runs in the `lit` repo, so this script needs to be called directly.

.changeset/few-books-exist.md, packages/labs/eleventy-plugin-lit/package-lock.json, packages/labs/eleventy-plugin-lit/src/index.ts, packages/labs/eleventy-plugin-lit/src/test/eleventy-plugin-test.ts, packages/labs/ssr/package-lock.json
There is some underlying issue in our ModuleLoader class whereby
loading multiple modules concurrently can cause errors like:
```
"request for '@lit/reactive-element' is not yet fulfilled
```
There is likely some kind of race condition there, but I haven't
yet identified it. Tracking at https://github.com/lit/lit/issues/2549.
To address this problem for the Eleventy plugin in the short term,
this temporarily makes module loading serial instead of concurrent.
=> [@lit-labs/eleventy-plugin-lit] Temporary fix for ModuleLoader concurrency issue

.changeset/chilly-spies-brush.md, .changeset/perfect-pens-itch.md, packages/lit-element/src/lit-element.ts, packages/lit-html/src/lit-html.ts, packages/reactive-element/src/reactive-element.ts
When running Lit in dev mode, and when window.emitLitDebugLogEvents is true, we will emit 'lit-debug' events on window. These events will be fired during rendering and as part of the ReactiveElement update lifecycle, giving internal information about rendering that may be useful for debug tools and visualizers.
Production builds will not be affected, all of the devlog code is compiled out when DEV_MODE is false.
Note that this is an unstable API which may change or even be removed in the future, even on patch releases.
=> Add a devlog events system

.changeset/curly-points-flash.md, packages/localize-tools/src/formatters/xliff.ts, packages/localize-tools/testdata/extract-xliff-fresh-js/goldens/data/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-fresh-js/goldens/data/xliff/zh_CN.xlf, packages/localize-tools/testdata/extract-xliff-fresh-ph/goldens/data/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-fresh-ph/goldens/data/xliff/zh_CN.xlf, packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/zh_CN.xlf, packages/localize-tools/testdata/extract-xliff-merge/goldens/xliff/es-419.xlf
Fixes #2560 
- Reorder xliff generation so `<note>` elements to follow `<source>` and `<target>` elements.
- Update test goldens to account for reordering
=> [localize-tools] Fix xliff note element ordering

.github/workflows/starter-kits.yaml
The starter kit repos were not pushed after merging #2496 because the checked out repos are shallow: https://github.com/lit/lit/runs/5415481001?check_suite_focus=true#step:5:28
=> Fetch all history for the starter kit repos during checkout in the sync workflow.

.github/workflows/starter-kits.yaml
The source repo needs to not be shallow for the fetch to succeed without [`--update-shallow`](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---update-shallow) ([`.git/shallow` docs here](https://git-scm.com/docs/shallow)). I think this likely means that #2597 wasn't necessary, but I'm not inclined to revert it since I'm worried it would affect the push.
=> Set `fetch-depth: 0` on all repos when syncing the starter kits.

.github/workflows/tests.yml
Fixes https://github.com/lit/lit/issues/2544
This check was added in https://github.com/lit/lit/pull/2061 and ensures that changes to packages require a changeset file. See docs on the command: https://github.com/changesets/changesets/blob/main/packages/cli/README.md#status
However in the case of an automated release PR, we create a situation which fails this check. This is because the release PR deletes all changeset files, and also modifies packages by bumping version numbers and updating the CHANGELOG.md files (reference PR: https://github.com/lit/lit/pull/2565/files).
Thus this check will (and does) always fail in a release PR.
Skip this check if `lit-robot` authored the PR.
We could create an empty changeset file as part of the automated release PR. I opted for this route as I think …
=> [meta] Fix changeset action failing on release PR

.github/workflows/starter-kits.yaml
Changes to the starter kits are currently being pushed to the `release-automation-test-main` branch of each repo. This PR starts pushing changes to `main` instead.
Here are the current diffs with the `release-automation-test-main` branch in each repo:
- https://github.com/lit/lit-element-starter-ts/compare/release-automation-test-main
- https://github.com/lit/lit-element-starter-js/compare/release-automation-test-main
Here's the run where the first successful push happened (which commits in the diffs above):
- https://github.com/lit/lit/runs/5416539896?check_suite_focus=true
Here's a later run with no changes, where nothing was pushed:
- https://github.com/lit/lit/runs/5416801484?check_suite_focus=true
Closes #2248.
=> Push starter kit changes to the individual repos' `main` branches.

README.md
This section of the readme is no longer relevant given that this now happens automatically on any push to `main`.
Fixes #2537.
=> Remove outdated starter kit export docs.

README.md
These links are currently pointing to the folder within this repo, which are already referenced by a link right before each. This PR updates them to point to the separate template repos.
=> Fix links to the starter kit repos in the README.

packages/reactive-element/src/test/reactive-element_test.ts
This unused variable is intentional because the assignment's type error is used to check the type of the expression, but the lint warning appears at the end of every PR's diff because it isn't handled.
=> [@lit/reactive-element] Fix a lint warning in the tests.

.changeset/weak-feet-invent.md, lit-next.code-workspace, packages/lit-html/src/lit-html.ts, packages/reactive-element/src/reactive-element.ts
Integrations that need to clone nodes can do so themselves
Fixes #2632
=> Don't clone nodes as part of the debug event logger

.changeset/young-cups-develop.md, packages/lit-html/src/lit-html.ts
Expands on the error message for a missing 'raw' property on a TemplateResult's strings to call out that this is part of Lit's security system.
=> Forging TSAs is a security bug

.changeset/heavy-carrots-thank.md, packages/lit-html/src/directives/style-map.ts, packages/lit-html/src/test/directives/style-map_test.ts
The `StyleInfo` interface which `styleMap` takes as an argument was marked as readonly making the following case (without explicit types) valid:
```ts
render() {
const styles = {color: 'red'};
styles.color = 'blue';
return html`<p style="${styleMap(styles)}">Hello!</p>`;
}
```
but the explicitly typed version invalid:
```ts
render() {
const styles: StyleInfo = {color: 'red'};
styles.color = 'blue';
return html`<p style="${styleMap(styles)}">Hello!</p>`;
}
```
[Playground repro](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgc3RhdGV9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7c3R5bGVNYXAsIFN0eWxlSW5mb30gZnJvbSAnbGl0L2RpcmVjdGl2ZXMvc3R5bGUtbWFwLmpzJztcblxuQ …
=> Remove readonly restriction from StyleInfo interface

.changeset/seven-bottles-sing.md, packages/lit-html/src/static.ts, packages/lit-html/src/test/static_test.ts
=> Add an additional security brand check to StaticValues

.changeset/light-candles-yell.md, packages/labs/ssr/src/lib/dom-shim.ts, packages/labs/ssr/src/test/all-tests.ts, packages/labs/ssr/src/test/lib/dom-shim_test.ts
This PR implements a public readonly property, `shadowRoot`, on the `HTMLElement` class defined in the dom-shim. This property will evaluate to the object created and returned by `attachShadow()` when `attachShadow()` is invoked with an open shadow root mode (`host.attachShadow({mode: "open"}`). Otherwise, `shadowRoot` will evaluate to `null`. This behavior is intended to match the DOM behavior defined [here](https://dom.spec.whatwg.org/#dom-element-attachshadow).
Let me know if changes are need; I'm happy to make any updates. I've also added one question inline that should probably get attention before merging. Thanks in advance!
Fixes #2652
=> [@lit-labs/ssr] Implement HTMLElement.shadowRoot

.changeset/light-jobs-retire.md, packages/labs/react/README.md, packages/labs/react/src/create-component.ts, packages/labs/react/src/test/create-component_test.tsx
This PR is a retcon of PR #2445 
- users explicitly define event types in event callbacks
- default event type expected from a PropName map is `(e: Event) => void`
- user can declare a event map interface like `{propName: EventType, ...}`
- will be expressed as `{prop: (e: EventType) => void, ...}` in the React Component Props
- user prop type is used despite existing or expected React Type
- example: `{'onChange': Event}` will eclipse `React.FormEvent<HTMLInputElement>` with a DOM `Event` 
This should allow clients to explicitly define event types in react event callbacks like the example below:
```Typescript
interface MyElementEvents {
onClick: MouseEvent;  
onKeyDown: KeyboardEvent;
}
const myElementPropNames = {
onClick: 'click', // (e: MouseEvent) => void
onKeyDown: 'keydown',  // …
```
=> [@labs/react] type event callbacks

.changeset/short-cooks-deliver.md, packages/lit-html/src/directives/ref.ts, packages/lit-html/src/test/directives/ref_test.ts
The `WeakMap` used to store the last element called to a given callback is keyed on the callback function. Since unbound LitElement class methods passed as callbacks will all have the same references between class instances, this will result in incorrect tracking of the last element per unique callback, given that callbacks called on different context's should be considered unique.
The change here uses nested WeakMaps to effectively double-key the lookup on both function _and_ context.
Fixes #2677.
=> [lit-html] Fix `ref` bug when auto-bound class method used as as callback

.changeset/tender-bobcats-greet.md, packages/localize-tools/src/modes/transform.ts, packages/localize-tools/src/tests/transform.unit.test.ts, packages/localize-tools/testdata/build-transform-xliff/goldens/foo.ts, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/en/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/es-419/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/zh_CN/foo.js, packages/localize-tools/testdata/build-transform-xliff/input/foo.ts
Fixes #2574
No longer subsume expressions into text if they follow a `=` with the assumption being they are placed as a value of a html attribute, allowing `lit-html` to parse them properly.
This PR also corrects an oversight from #2405 where we were returning the old `template` rather than `newTemplate` if we had a simple string literal after applying translation.
=> [localize-tools] Keep expressions in attribute values for transform mode

.changeset/honest-hats-explode.md, packages/labs/react/src/create-component.ts, packages/labs/react/src/test/create-component_test.tsx
Currently our react wrapper will attach the '__forwardedRef' react component property to the referenced element itself.
This PR:
- creates a property sieve (i'm assuming there might be other rogue properties in the future)
- skips over properties in the property sieve, doesn't pass sieve props to element
- add tests to confirm sieve properties aren't added
solves issue:
#2593
=> [@lit-labs/react] - remove renegade properties

.changeset/rude-jokes-fetch.md, packages/reactive-element/src/decorators/query-all.ts, packages/reactive-element/src/decorators/query-async.ts, packages/reactive-element/src/decorators/query.ts
Add explicit types to the code samples showing example usage of `query`, `queryAll`, and `queryAsync`.
=> [reactive-element] Add types to query, query-async, and queryAll jsdoc code examples

.changeset/early-horses-smile.md, .eslintignore, .eslintignore-sync, .eslintrc.json, package-lock.json, package.json, packages/labs/analyzer/src/test/analyzer_test.ts, packages/labs/eleventy-plugin-lit/src/test/eleventy-plugin-test.ts, packages/labs/motion/src/test/animate_test.ts, packages/labs/observers/src/test/intersection_controller_test.ts, packages/labs/observers/src/test/mutation_controller_test.ts, packages/labs/observers/src/test/performance_controller_test.ts, packages/labs/observers/src/test/resize_controller_test.ts, packages/labs/scoped-registry-mixin/src/test/scoped-registry-mixin_test.ts, packages/labs/ssr/src/test/integration/server/server.ts, packages/labs/ssr/src/test/lib/dom-shim_test.ts, packages/labs/ssr/src/test/lib/module-loader_test.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/task/src/test/task_test.ts, packages/lit-html/src/directive.ts, packages/localize-tools/src/tests/analysis.unit.test.ts, packages/localize-tools/src/tests/e2e/e2e-goldens-test.ts, packages/localize-tools/src/tests/ssr.unit.test.ts, packages/localize-tools/src/tests/transform.unit.test.ts, packages/localize-tools/src/types/config.d.ts, packages/ts-transformers/src/tests/constructor-cleanup-test.ts, packages/ts-transformers/src/tests/idiomatic-decorators-test.ts, packages/ts-transformers/src/tests/preserve-blank-lines-test.ts
Fixes #2644 and adds an eslint plugin to enforce extensions going forward.
=> Enforce use of file extensions in imports

.github/workflows/sauce-ie11.yaml, .github/workflows/sauce.yaml
Currently, tests are run in our sauce related github actions that do not involve sauce. Removing them greatly cuts down on our total github action usage.
This change points the `sauce` and `sauce-ie11` github actions to the `tests` package to run tests. Reason being, some tests like localize are not run as saucelabs tests. Others don't test in a browser.
As we gather more tests for saucelabs, they can be included in `web-test-runner.config.js`. If they're more involved or require a more complex setup, they can be added in a more itemized way for future jobs
For instance, SSR is a little involved. So we could add it to saucelabs tests with:
```
- name: Test SSR
run: |
cd packages/labs/ssr
npm run test:integration
```
=> [@tests] only run remote tests in sauce actions

.github/workflows/sauce-ie11.yaml, .github/workflows/sauce.yaml
Playwright is not used for saucelabs testing and does not need to be installed in the saucelabs github action.
This PR removes both the `playwright` job and the `lint` job. Neither are necessary for saucelabs runs
=> [@tests] remove playwright install for remote tests

.changeset/thick-hotels-admire.md, packages/ts-transformers/src/internal/decorators/property.ts, packages/ts-transformers/src/tests/idiomatic-decorators-test.ts
Adds support for
```ts
import {LitElement} from 'lit';
import {property} from 'lit/decorators.js';
class MyElement extends LitElement {
@property({type: Boolean})
get reactiveGetter() {
return false;
}
}
```
transforming into:
```ts
import {LitElement} from 'lit';
class MyElement extends LitElement {
static properties = {
reactiveGetter: {type: Boolean},
};
get reactiveGetter() {
return false;
}
}
```
=> ts-transformers can support reactive getters

.changeset/thin-ducks-camp.md, packages/labs/context/src/lib/context-root.ts, packages/labs/context/src/test/late-provider_test.ts
@justinfagnani realised this was using WeakRef unnecessarily.
The `ContextRoot` should only handle those requests which are intended to be subscribers to updates. Otherwise the semantics are somewhat lost of a one-time context request. By making ContextRoot only work for those context requests which intend to subscribe to future updates, we can remove WeakRef usage as the connected components will clean themselves up through disconnection. This also broadens browser support!
=> [labs/context] Removes use of WeakRef

.changeset/large-hounds-exist.md, packages/labs/cli/package-lock.json, packages/labs/context/package-lock.json, packages/labs/eleventy-plugin-lit/package.json
Fixes #2795 
The `worker/worker.js` file included in the package needed to be run as ES module but would not by default since it was being loaded from the `index.js` written in commonjs to work with eleventy.
This worked during local testing because there is a `worker/package.json` file with `"type": "module"` but this was not included in the package so the npm distributed package would not work. Fixed by including this in the package. Tested locally by running `npm pack` and installing from tarball in test project.
Includes changes to `package-lock.json`s from having run `npm run nuke`.
=> [@lit-labs/eleventy-plugin-lit] Fix worker script to run in ESM

.changeset/dull-panthers-burn.md, packages/labs/analyzer/src/lib/analyzer.ts, packages/labs/analyzer/src/lib/model.ts, packages/labs/analyzer/src/test/analyzer_test.ts, packages/labs/analyzer/test-files/basic-elements/src/class-a.ts, packages/labs/analyzer/test-files/basic-elements/src/default-element.ts
This only supports getting the tag name from the `customElement` decorator. I added a TODO for finding `customElement.define()` calls. I want to mirror the custom elements manifest approach of allowing these to be separate, where the `customElement.define()` calls are considered a type of "export" so that you could have more than one, but for many cases it'll be very useful to understand that a class is intended to have a single specific tag name.
=> [analyzer] Initial support for finding LitElement declarations

.changeset/perfect-jokes-brush.md, .changeset/thin-ducks-camp.md, packages/labs/context/package-lock.json, packages/labs/context/package.json
- Remove cli changeset so it doesn't get version bumped.
- Remove extra patch note for labs/context so we just have a single "initial release" line.
=> Changeset cleanup

.changeset/swift-months-double.md, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts, rollup-common.js
While migrating internal to Lit 2, we had these additional options to change how the `render` function behaved. However these are no longer required as they are not referenced internally.
Tested internally with a TGP using the same change, and checking for all references of `INTERNAL` and `clearContainerForLit2MigrationOnly`. Manually checked that copy.bara wouldn't need changes.
I also removed a unit test that was testing the `INTERNAL` and `clearContainerForLit2MigrationOnly` option behavior.
=> Remove private Lit 2 migration helpers

.changeset/giant-timers-bathe.md, packages/labs/router/package-lock.json, packages/labs/router/package.json, packages/labs/router/src/routes.ts, packages/labs/router/src/test/router_test_code.ts, packages/labs/router/tsconfig.json
Fixes issue https://github.com/lit/lit/issues/2697
This PR includes two changes. I ran `npm upgrade` on the router, with `urlpattern-polyfill` updated.
This type only update also required updating some types.
The return type change is required due to:
- [urlpattern should return undefined for optional groups that do not match](https://github.com/kenchris/urlpattern-polyfill/issues/66)
- https://github.com/WICG/urlpattern/issues/162#issuecomment-1026014789.
=> [@lit-labs/router] Use new version of URLPattern polyfill

rollup-common.js
This removes the error:
```
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
```
=> [infra] Set preventAssignment for rollup-replace

.changeset/fluffy-zebras-sniff.md, packages/labs/router/src/routes.ts, packages/labs/router/src/test/router_test.ts, packages/labs/router/src/test/router_test_code.ts
Fixes: https://github.com/lit/lit/issues/2833
For dynamically adding routes, we previously needed to push the new route prior to the last one (if the last one is a fallback route).
To make pushing routes dynamically easier, we can instead pass and use a `fallbackRoute` option.
Tested by slightly expanding the existing tests. I mostly added assertions to ensure that the dynamic route is added correctly, and that the fallback route is reachable.
=> [@lit-labs/router] API for a fallback route

.changeset/famous-dots-dance.md, packages/labs/context/tsconfig.json
Fixes #2839
I tried using the context API.
One problem I met is that there are optional chaining operators in the code (?.) which fails at runtime in environments that do not support it.
Since lit is transpiled to es2019, I lowered `@lit-labs/context` to the same version. This ensures tha the dependency won't require additional transpiling step.
=> [@lit-labs/context]: fix(#2839): lower target version

.changeset/orange-snakes-happen.md, packages/tests/web-test-runner.config.js
Currently we run 3 browsers with a max default concurrency of 2.
To avoid leaving a browser hanging, all three should run.
During saucelabs runs this becomes more important due to latency.
This PR increases the default concurrency to 3.
=> [@tests] increase default concurrent browsers to 3

.changeset/breezy-days-prove.md, packages/labs/motion/src/test/animate_test.ts, packages/labs/motion/src/test/test-helpers.ts, packages/tests/web-test-runner.config.js
Some non-ideal workarounds for browser quirks:
* Introduces `closeTo` for numbers that are slightly off and
* adds a sleep to let Safari assert ok.
Fixes https://github.com/lit/lit/issues/2009
=> Fix motion tests

.changeset/angry-masks-reply.md, .changeset/little-ligers-roll.md, .changeset/orange-snakes-happen.md, .changeset/shiny-houses-jog.md, .changeset/tidy-shirts-sparkle.md, .changeset/wise-coins-wave.md
Fixes: https://github.com/lit/lit/pull/2912
This PR enforces the rule : "We only want changesets for things a user would care about reading in our changelog." ~  @aomarks
For changes to our in-progress cli or test package we have commit history.
Remove all changeset files that reference private packages.
=> Remove changeset md files for private unpublished packages.

.changeset/tasty-eyes-end.md, packages/labs/router/src/routes.ts
Addresses: https://github.com/lit/lit/issues/2925
Currently we have a [rollup renaming rule](https://github.com/lit/lit/blob/main/rollup-common.js#L239-L241) that renames properties prefixed with `_`.
The renaming is incompatible with subclassing.
Make the underscored properties private, and expose getters for public/protected endpoints.
For example, `_currentParams` has a public API: `params`.
We can add a public API as we better understand what is required.
=> [@lit-labs/router] Make _ prefixed class members private fixing renaming.

.changeset/modern-parrots-talk.md, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts, packages/lit-html/src/experimental-hydrate.ts
In SSR, when an element has an attribute binding, we insert a `` comment to tell `hydrate()` about the attribute binding.
However, if that element was a *void* element, such as `<input>` or anything from [this](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) list, then when the HTML parser encounters it, all of the children it has will be hoisted up as siblings.
For example:
```ts
render() {
return html`<input max=${this.maxLen}>`;
}
```
Is SSR'd as:
```html
<input max="42"></input>
```
But parsed by the browser as:
```html
<input max="42" />
```
This means when `hydrate()` encounters a case like this, we need to check `previousSibling` instead of `parentElement`, to find the element to receive the attribute binding.
We already accounted for void elements where we …
=> [ssr] Fix hydration bug with attribute bindings on void elements

.changeset/lovely-months-agree.md, .changeset/modern-parrots-talk.md
Found in https://github.com/lit/lit/pull/2954
- Delete `@lit-labs/gen-wrapper-angular` changeset, because it's not released.
- Also bump `lit`, should have been included in https://github.com/lit/lit/pull/2952.
=> Fix a couple of release issues

.changeset/hungry-deers-hang.md, packages/localize/src/internal/runtime-msg.ts, packages/localize/src/tests/runtime.test.ts
Fixes #2971 
We were previously reusing the localized template result object mapped by id for every runtime `msg` call and mutating the values property on it. When multiple `msg` call with template strings that result in the same id were present, it would have the same, latest assigned, value. Changed to return a new object, with the value replaced for each invocation of `msg`.
=> [localize] Fix multiple runtime msg call with same template but different expressions

.changeset/slimy-comics-study.md, packages/labs/context/README.md, packages/labs/context/src/lib/decorators/context-provider.ts, packages/labs/context/src/test/context-provider_test.ts
* Fixes #2964: @contextProvider now uses a WeakMap to find the controller associated with the given element. This was previously not looked up by element and therefore all setters would find the controller for the last instantiated instance
* Fixes #2965: Changes incorrect references to `@contextRequest` to the proper name `@contextProvided`.
=> [labs/context] Fixes #2964 and #2965

packages/labs/context/src/lib/controllers/context-provider.ts, packages/labs/context/src/test/provider-and-consumer_test.ts
Prevent an element to add callback to itself in case it is a consumer and a provider of the same context. 
Should address #2843
=> [context] Prevent context-request event to listen to itself.

.github/workflows/tests.yml
The latest patch version of node apparently ships with a version of npm that causes our windows-tools test to fail. (It logs deprecation warnings with every npm script run that messes up our cli test assertions). The latest npm version fixes that. https://github.com/npm/cli/issues/4980
However, updating npm for Windows isn't as simple as `npm i -g npm@latest` https://docs.npmjs.com/try-the-latest-stable-version-of-npm#upgrading-on-windows
It seems easier to just pin the version of node for the windows-tools test to one that shipped with working npm and unpin later once the latest v16 of node includes that.
=> [infra] Pin node version for windows-tools test

package.json
When the changeset action runs, it runs `npm run version` as it creates the Version Release PR as specified here: https://github.com/lit/lit/blob/0594bd8345371cc8fa7a2a1cee65c2debc67a95c/.github/workflows/release.yaml#L60
While this bumps the versions of updated packages in `package.json`, it does not update them in `package-lock.json` which necessitated PRs like this https://github.com/lit/lit/pull/2918
Running `lerna bootstrap` passing in the `--package-lock-only` flag documented here https://docs.npmjs.com/cli/v8/commands/npm-install, it will also update the `package-lock.json` files with the proper versions based on the updated `package.json`.
Tested this locally by creating a new changeset for a package and running `npm run version` which resulted in an updated `package.json`, …
=> [infra] Update version script to also update package-lock

.changeset/modern-mangos-complain.md, .changeset/thirty-cobras-clap.md, packages/labs/vue-utils/package.json
Fixes for the release PR https://github.com/lit/lit/pull/3028
1. Removes the private package change.
2. Add a changeset for the labs/context change added in https://github.com/lit/lit/pull/2858. Related to issues https://github.com/lit/lit/issues/2966, and https://github.com/lit/lit/issues/2843
3. Add `"private": true` to `packages/labs/vue-utils`
=> [meta] Fix release changesets

.changeset/eleven-zebras-crash.md, packages/labs/router/rollup.config.js, packages/tests/src/wtr-config.ts, rollup-common.js
Fixes issue https://github.com/lit/lit/issues/3031
Our labs packages have `test:prod` commands, however they do not have a remapping to the production bundle. This results in the `test:prod` command being a duplicate of the dev mode test.
After fixing the `test:prod` commands, it reproduced the bug in the linked issue, as well as a property mangling failure in labs/React.
An investigation found that the name cache system was tree shaking out the imports, which then meant terser didn't have any context for what property names were in the bundle. Without the name cache terser would rename different subclass properties to the same name.
By adding `console.log` statements for each import in the name cache file, it prevents tree shaking and dead code elimination of the classes. This correctly …
=> [infra] Test labs production builds and fix class property name mangling collisions

.changeset/khaki-coats-bow.md, packages/labs/ssr/package.json, packages/labs/ssr/src/lib/dom-shim.ts, packages/labs/ssr/src/lib/render-lit-html.ts, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/labs/ssr/src/test/integration/tests/ssr-test.ts
Previously, when our SSR DOM shim for `setAttribute` received a value, it just assumed it was a string and assigned it to its internal attribute map as-is. Later, when trying to serialize an attribute to HTML, we pass it through an escape function, which crashes if the value is not a string.
In browsers, the value passed to `setAttribute` is always cast to a string. So `42` becomes `"42"`. We now mirror this behavior.
This specifically came up in https://github.com/lit/lit/issues/2633 because in `ReactiveElement`, when a property has `{type: Number}`, we do not cast the value to a string ourselves, since we assume the browser will do that automatically (in fact, we don't handle `Number` at all, since the default behavior is correct …
=> [ssr] Cast setAttribute values to string in SSR DOM shim

.changeset/fuzzy-lobsters-pretend.md
Since we don't need changelogs to be updated for yet to be released packages.
=> [chore] Remove changeset for private packages

.changeset/thin-bees-build.md, packages/labs/react/src/create-component.ts
This PR removes the `StringValued` type.
It can be replaced by the `Events` type.
=> [labs/react] remove StringValued type

.changeset/dirty-rocks-happen.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
This makes type inference work better when are are mixed types because we can cast them as `as const` to make them a tuple type, not an array of unions.
```ts
new Task(
this,
([a, b]) => [a * 2, b.split('')],
() => [1, 'b'] as const
);
```
Without the `as const` the args array would be inferred as `(string | number)[]`, so we'd have to write a type annotation on the args in the task function. Now we can just put `as const`, the args array is inferred as a tuple, and the args to the task function are inferred correctly without any annotations.
To allow that I made the generics `ReadonlyArray<unknown>`. There were a couple of places where `[...unknown[]]` was used, but I'm not sure why.
=> Allow task args to be readonly

.changeset/small-doors-develop.md, packages/internal-scripts/src/release-image.ts
Part of https://github.com/lit/lit/issues/2503
Previously the release-image tool could only take one single CHANGELOG and an optional version. This PR extends the tool to concatenate multiple CHANGELOG files and versions making the tool more flexible. This will allow generating a single image for a release.
- CLI can now take multiple files and versions with the following pattern: `release-image (-f CHANGELOG_PATH [-v VERSION])...`. If the same changelog is provided multiple times with different versions, the image contains those versions.
- The packge/release notes are added to the image in the order of the CLI arguments.
For example: `release-image lit-html/CHANGELOG.md -v 2.2.2 -f lit-html/CHANGELOG.md -v 2.2.1` generates the following image:
If the versions are omitted, the most …
=> Update release-image such that it can accept multiple packages and versions

.changeset/fifty-shirts-flash.md, packages/labs/ssr/tsconfig.json
Fixes #2645 
tsconfig was missing `inlineSources` option for labs/ssr package.
~~Alternative fix would be to actually include the source ts files in the npm package. Since this package is meant for server/node use only, would that potentially be preferable?~~
Will stick with inline sourcemap to be consistent with the rest of our packages.
=> [labs/ssr] Inline source in source maps

packages/labs/ssr/README.md
Hey, I just tried the examples and the ponyfill is broken because `hasNativeDeclarativeShadowRoots` is actually a function.
https://github.com/webcomponents/template-shadowroot/blob/62ca5560c757a26e3425dd4c97dc48acd2591e01/src/_implementation/feature_detect.ts#L18
=> Fix example with `hasNativeDeclarativeShadowRoots`

.changeset/four-rocks-pretend.md, package.json, packages/labs/testing/src/lib/lit-ssr-plugin.ts
Fixes #3165 
In Mac/Linux, `process.cwd()` returns an absolute file path starting with `/`.
But in Windows, it returns a path starting with `C:\` which Node's import thinks is specifying some invalid protocol. Converting the absolute file paths to file URLs fixes this as it'll always begin with `file://`.
I also added the test for this package to `windows-tools` test job.
=> [labs/testing] Pass module file urls to worker for Windows compatibility

.changeset/hip-eels-ring.md, packages/lit-html/src/static.ts, packages/lit/src/index.all.ts
Class properties initialized with a literal are implicitly typed as
`any` because `StaticValue` is not exported.
=> Export StaticValue from lit-html/static

.changeset/mean-toes-cry.md, packages/labs/ssr/src/lib/dom-shim.ts
Fixes #3168
Adds `URL` and `URLSearchParams` class to the global that's provided to the VM context when instantiating `ModuleLoader`.
=> [labs/ssr] Add URL and URLSearchParams to VM module global

.changeset/dry-months-accept.md, .changeset/old-tables-own.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
=> Bind this to custom attribute converter methods

.changeset/forty-bobcats-sneeze.md, packages/lit-html/src/lit-html.ts
Most commonly this would happen when rendering `${this}` in a LitElement's template, which has the counterintuitive behavior of removing the element from the DOM, because when rendering the element's template we attach it into its own shadow root, which removes it from the DOM, causing it simply disappear. This is especially problematic with a fast HMR system.
=> In DEV_MODE, render a warning instead of rendering a template's host in the template.

.changeset/shy-wasps-exercise.md, packages/labs/eleventy-plugin-lit/src/index.ts
Fixes #3059 
Due to module file paths having `C:\` for Windows, the imports fail due to unrecognized protocol. Converting them to file URLs fixes that.
Note:
This makes eleventy-plugin-lit now work in `worker` (default) mode for Windows users.
In `vm` mode, it still breaks due to an issue with `ModuleLoader` noted here https://github.com/lit/lit/issues/3202
I was also unable run the eleventy-plugin-lit package test suite in Windows as the testing rig has issues somewhere with the filesystem symlinking, writing, reading.
I did, however, manually test it by running the example eleventy project on a Windows machine and confirmed `worker` mode runs.
=> [labs/eleventy-plugin-lit] Use file URLs for resolved module paths

.changeset/wild-ladybugs-flash.md, packages/labs/ssr/src/lib/module-loader.ts
Fixes #3202 
This will allow SSR with VM modules on Windows machines.
Along with #3203, this should fix `eleventy-plugin-lit` running in `vm` mode for Windows users as well.
=> [labs/ssr] Use url module to convert file url to path

.github/workflows/release-image.yaml
This way it will run not only when a release PR is opened, but also when it's updated.
=> Also re-run release image generator on pushes

.changeset/happy-badgers-watch.md, packages/labs/virtualizer/src/lit-virtualizer.ts, packages/labs/virtualizer/src/test/scenarios/main-module.test.ts
Per https://github.com/lit/lit/issues/3051#issuecomment-1163649651 we are exporting the events from the main module to facilitate users (re-)emitting them for certain use-cases.
=> [labs/virtualizer] Added RangeChangedEvent/VisibilityChangedEvent to main module exports

.changeset/fifty-monkeys-shop.md, packages/lit-element/src/test/node-imports.ts, packages/reactive-element/src/css-tag.ts, packages/reactive-element/src/test/node-imports.ts
The recently added `node` build would crash when importing a component that had both `static styles` and used the `@property` decorator. That's because the `@property` decorator causes Lit class initialization at module load time, which ran an `instanceof CSSStyleSheet` check before this PR. Since `CSSStyleSheet` is not defined by default, the error would occur.
This PR fixes that by not assuming `CSSStyleSheet` will be defined when in Node mode.
Fixes https://github.com/lit/lit/issues/3218
=> [core] Fix `CSSStyleSheet is not defined` error in Node build

.changeset/selfish-lobsters-cheat.md, packages/lit-html/src/lit-html.ts
In Node builds, use the existing `document` if found.
This should allow node builds running in an environment with DOM emulation loaded to still function, like in a node test runner.
Fixes #3216
=> [lit-html] Use existing `document` in Node build

.changeset/mighty-yaks-compete.md, packages/labs/cli/README.md, packages/labs/cli/package.json, packages/labs/cli/src/lib/commands/labs.ts, packages/labs/gen-utils/package.json, packages/labs/gen-wrapper-react/package.json, packages/labs/gen-wrapper-vue/package.json
- Remove `private` and add a changeset, so that the next deploy should release `0.1.0` of everything (because they are all currently `0.0.1`).
- Add disclaimer to README about this being an early release.
- Document the `labs gen` command and its flags in the README.
- Mention that `vue` is also supported in the `help` command text.
=> [cli] Prepare for CLI 0.1.0 release

.changeset/tidy-lobsters-press.md, packages/labs/cli/package.json, packages/labs/gen-utils/package.json, packages/labs/gen-wrapper-angular/package.json, packages/labs/gen-wrapper-react/package.json, packages/labs/gen-wrapper-vue/package.json, packages/labs/vue-utils/package.json
- I forgot `@lit-labs/vue-utils` in https://github.com/lit/lit/pull/3225, so that's now `private` and has a changeset so that the next publish will release it as `0.1.0`.
- Removed a couple of prod `dependencies` on `@lit-internal/tests`, which should have been `devDependencies`.
- Add missing `publishConfig.access` to new packages `package.json` files.
=> [cli] Prepare vue-utils for release, remove test prod deps, add publishConfig.access

packages/labs/cli/README.md
`localize` got mixed up with `labs` on the paragraph about the `labs gen` usage.
=> Typo fix in @labs/cli README.md

.changeset/gorgeous-ducks-walk.md, packages/labs/gen-wrapper-vue/package.json
The `lit labs gen` command with `--framework=vue` was not working due to missing lib files. This fix adds those to the npm package.
I've only included the `.js` files inline with the existing `index.js` and omission of declaration and sourcemaps.
=> [labs/gen-wrapper-vue] Add lib files to npm package

.changeset/friendly-squids-perform.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes #2945
Task will no longer reset its value or error on pending. This allows us to start chaining tasks e.g.
```ts
const a = new Task(this, async ([url]) => await fetch(url), () => [this.url]);
const b = new Task(this, async ([value]) => {/* This is not thrashed */}, () => [a.value]);
```
=> Task: Do not reset task value or error on pending

.changeset/modern-turtles-judge.md, packages/labs/observers/src/intersection_controller.ts, packages/labs/observers/src/mutation_controller.ts, packages/labs/observers/src/performance_controller.ts, packages/labs/observers/src/resize_controller.ts, packages/labs/observers/src/test/intersection_controller_test.ts, packages/labs/observers/src/test/mutation_controller_test.ts, packages/labs/observers/src/test/performance_controller_test.ts, packages/labs/observers/src/test/resize_controller_test.ts
Issue: https://github.com/lit/lit/issues/3147
When `host.addController(this)` is called on a ReactiveElement that is already connected, the controllers `hostConnected` method is called synchronously. Because in each exported controller `addController` is called before a `_target` is set, the following `hostConnected` logic is executed with an undefined `_target`:
```
if (this._target) {
this.observe(this._target);
}
```
This problem reproduces if the observer is initialized in `firstUpdated`.
Move the `addController` call to the end of the constructor after all the initial variables have been initialized.
Tested by adding a unit test for each controller - which failed prior to the controller being updated.
=> [labs/observers] Fix controllers not observing changes if initialized after host connected

.changeset/red-jars-float.md, packages/lit/package.json
I noticed build failing in pipeline like this https://github.com/lit/lit/actions/runs/3148045621/jobs/5118162175#step:7:67
Module self reference wasn't working during TypeScript build due to missing "types" export condition for the `lit` package.
Add "types" field. This needed to point to `./development/...` for the module self reference to work during TypeScript build as that is the specified output directory, so this PR also adds `development/` directory to the published package, as well as the "development" export condition. This particular package doesn't really need a "development" export condition at the moment but added those for consistency with our other packages and since the package published to npm would now be including those files anyway.
This also has the benefit of …
=> [lit] Add "types" to package exports

.changeset/seven-fireants-wonder.md, packages/labs/observers/src/intersection_controller.ts, packages/labs/observers/src/mutation_controller.ts, packages/labs/observers/src/performance_controller.ts, packages/labs/observers/src/resize_controller.ts, packages/labs/observers/src/test/intersection_controller_test.ts, packages/labs/observers/src/test/mutation_controller_test.ts, packages/labs/observers/src/test/performance_controller_test.ts, packages/labs/observers/src/test/resize_controller_test.ts
Issue: https://github.com/lit/lit/issues/2350
The `value` property was typed as unknown.
```
const resizeController = new ResizeController(host, {callback: () => true});
resizeController.value // Type is unknown.
```
After this change:
```
const resizeController = new ResizeController(host, {callback: () => true});
resizeController.value // Type is `boolean | undefined`.
```
Impact is that using `value` will no longer require unsafe type assertions. Instead the type of `value` is now always `T | undefined`, where `T` is the return type of the user provided `callback`.
- The generic type does not need to be provided and is unknown by default (for backwards compatibility).
- [**BREAKING**] The callback `() => true` is no longer defined by default. Instead the callback is `undefined` unless …
=> [labs/observers] Improve controllers value type

.changeset/spotty-kangaroos-shout.md, packages/labs/observers/src/intersection_controller.ts, packages/labs/observers/src/mutation_controller.ts, packages/labs/observers/src/resize_controller.ts, packages/labs/observers/src/test/intersection_controller_test.ts, packages/labs/observers/src/test/mutation_controller_test.ts, packages/labs/observers/src/test/resize_controller_test.ts
Fixes: https://github.com/lit/lit/issues/2902
Previously we would only track a single `_target` that was assigned in the constructor. This `_target` would be re-connected on `hostConnected`. Unfortunately this resulted in imperatively added targets via `observe(target)` to not be re-observed.
This is a light lift fix where we now store a set of the observed targets. This means any targets that are observed imperatively get re-observed after host is re-connected.
Note this change only impacts: ResizeController, IntersectionController, and MutationController which accept a `target` to observe.
This PR makes it very simple to support an "unobserve" public API (https://github.com/lit/lit/issues/3237) which is coming in a followup PR.
Tested via unit tests.
=> [labs/observers] observed targets are now re-observed when the host is reconnected

.changeset/big-files-attack.md, .changeset/clean-parents-doubt.md, .changeset/friendly-squids-perform.md, packages/labs/cli-localize/package.json
Some tidying up of changesets before the next release.
Changes
- Remove `@lit-labs/ssr` from analyzer changes
- Replace `@lit/localize-tools` with `@lit-labs/cli-localize` for lazy loading localize cli changes
- Prepare `@lit-labs/cli-localize`'s package.json for public release
- Add more info on `@lit-labs/task` changelog for the breaking change
=> [infra] Update changesets and package for release

.changeset/famous-dolls-cheer.md, .changeset/moody-colts-trade.md
`@lit-labs/cli` doesn't have a command for generating angular wrapper yet so no point in bumping `@lit-labs/gen-wrapper-angular`
=> [infra] Remove gen-wrapper-angular from changesets

.github/workflows/tests.yml
Resolves #3022 
The latest version of npm shipping in the Github actions runners no longer have the original issue.
=> [infra] Unpin Node version for windows-tools test

.changeset/blue-olives-fetch.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
=> Initializers are copied but separate from superclass initializers

.github/workflows/add-issues-to-project.yml
The workflow that adds all newly opened issue to the project board started failing due to the deprecation of the graphql object `projectNext` we were using, replaced by `projectV2` object.
Announcement: https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/
Doc for objects: [ProjectV2](https://docs.github.com/en/graphql/reference/objects#projectv2) is a field on [Organization](https://docs.github.com/en/graphql/reference/objects#organization)
Doc for mutation: [addProjectV2ItemById](https://docs.github.com/en/graphql/reference/mutations#addprojectv2itembyid)
Failing workflow: https://github.com/lit/lit/actions/runs/3382150362/jobs/5616777917
The updated query/mutation was tested by running the `gh api graphql` command locally with the issue that failed in the …
=> [infra] Use new projectV2 object in issue workflow

.changeset/moody-singers-doubt.md, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/test/scenarios/sizing-and-styling.test.ts
The fix here for #3400 was @graynorton's but it took a while to come up with a reliable test for a number of weird reasons.  In the end I opted for a simple test to show where virtualizer would choose to place an item in grid layout.  This was the easiest test case to reason about and it remains now essentially as a regression test.
=> [labs/virtualizer] Fix width inheritance calculation (issue #3400)

.changeset/dull-months-prove.md, packages/labs/analyzer/src/index.ts, packages/labs/analyzer/src/lib/analyze-package.ts, packages/labs/analyzer/src/lib/javascript/classes.ts, packages/labs/analyzer/src/lib/javascript/jsdoc.ts, packages/labs/analyzer/src/lib/javascript/modules.ts, packages/labs/analyzer/src/lib/javascript/variables.ts, packages/labs/analyzer/src/lib/lit-element/events.ts, packages/labs/analyzer/src/lib/lit-element/lit-element.ts, packages/labs/analyzer/src/lib/model.ts, packages/labs/analyzer/src/lib/references.ts, packages/labs/analyzer/src/lib/types.ts, packages/labs/analyzer/src/test/javascript/exports_test.ts, packages/labs/analyzer/src/test/lit-element/jsdoc_test.ts, packages/labs/analyzer/test-files/js/jsdoc/element-a.js, packages/labs/analyzer/test-files/js/jsdoc/package.json, packages/labs/analyzer/test-files/ts/jsdoc/package.json, packages/labs/analyzer/test-files/ts/jsdoc/src/element-a.ts, packages/labs/analyzer/test-files/ts/jsdoc/tsconfig.json, packages/labs/gen-manifest/goldens/test-element-a/custom-elements.json, packages/labs/gen-manifest/package.json, packages/labs/gen-manifest/src/index.ts, packages/labs/test-projects/test-element-a/src/element-a.ts
* **Adds `exports` to manifest generator** - [5d7d3b4](https://github.com/lit/lit/pull/3464/commits/5d7d3b433b2457532e721e2b50494d6cbc67ab56) - Also fixes a few bugs in analyzer logic around symbol renaming on the import side and export side, and adds tests for all of that which was woefully missing.
* **Add `@slot`, `@cssProp`, and `@cssPart` to manifest generator** - b5c3f5a
* **Fix config to make JS program analysis faster.** - dbe8189 - JS program analysis (specifically the call to `getSemanticDiagnostics()` that we do to make sure the program isn't broken before analyzing the AST) was suuuuper slow, as a result of the `allowJs` setting causing TypeScript to automatically include every `.d.ts` file under `node_modules/@types`, which doesn't happen when `allowJs` is false. Seems …
=> [labs/gen-manifest] Adds `exports` and more metadata to manifest generator

.changeset/early-eggs-doubt.md, packages/labs/ssr/src/lib/element-renderer.ts, packages/labs/ssr/src/lib/lit-element-renderer.ts, packages/labs/ssr/src/lib/render-lit-html.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
This PR adds a `shadowRootOptions` getter to `ElementRenderer` and uses it to configure the declarative shadow root attributes when `renderShadow` is defined. Only `mode` and `delegatesFocus` seem to have some amount of agreement around an attribute name at the moment, so `slotAssignment` isn't implemented.
Maybe `shadowRootOptions` on `ElementRenderer` should be renamed to `shadowRootInit` since `ElementRenderer` isn't meant to be specific to Lit?
Fixes #3483.
=> [labs/ssr] Render DSD attributes based on `shadowRootOptions`.

.eslintignore, .prettierignore, packages/labs/virtualizer/.gitignore
This file popped up in the untracked list after building recently.
=> [labs/virtualizer] Add `/events.js.map` to `.gitignore`.

.changeset/slow-mugs-battle.md, packages/labs/virtualizer/src/LitVirtualizer.ts, packages/labs/virtualizer/src/test/layouts/flow.test.ts
Added an equivalent `LitVirtualizer#scrollToIndex()` method to preserve the API that existed prior to latest merge of #3183 which removed it.
=> [labs/virtualizer] add scrollToIndex shim for SemVer backwards compatibility to 0.x

.changeset/fuzzy-gorillas-wait.md, package-lock.json, packages/labs/ssr/package.json, packages/labs/ssr/src/lib/module-loader.ts, packages/labs/ssr/src/test/lib/module-loader_test.ts, packages/labs/ssr/src/test/test-files/module-loader/lit-import-from-root.js, packages/labs/ssr/src/test/test-files/module-loader/lit-import.js
The resolve package doesn't support package exports and various other more modern resolution features. It seems `enhanced-resolve` (from webpack) introduces this support.
Fixes #3270 
@justinfagnani can you or someone on the team help me figure out the right way to add a test for this? the current module loader tests don't test bare specifiers it seems, so i don't have any examples to work from.
until then im not 100% sure it fixes 3270, so do want to get that added
=> fix (labs/ssr): move to enhanced-resolve for package exports support

package-lock.json, package.json
One of the benefits for updating for the monorepo is
> Added graceful recovery from ECONNRESET and other connection errors when using GitHub Actions caching.
=> [chore] Update wireit

.changeset/thirty-knives-hunt.md, packages/labs/virtualizer/package.json
Fixes missing sourcemap file in package.json.
=> [labs/virtualizer] Added missing events.js.map sourcemap file to package.json

.changeset/config.json, .github/workflows/release.yaml
Adds `@lit-labs/ssr` and packages that depend on it to the ignore list for changeset and use my fork of the changeset action https://github.com/augustjk/changesets-action/tree/test for the next release.
This should be reverted after the next release as packages in the ignore list cannot be selected in the changeset cli to add a new changeset entry.
=> [infra] Skip labs/ssr for next release

.changeset/config.json, .github/workflows/release.yaml
Reverts lit/lit#3530
The commits in the original PR were intended as a temporary workaround to make releasing a single package through the changesets action possible.  Reverting these changes to resume standard behavior.
thanks again @augustjk 🤘
=> Revert "[infra] Skip labs/ssr for next release"

.changeset/friendly-papayas-glow.md, packages/lit-html/package.json, packages/lit/package.json, packages/reactive-element/package.json, rollup-common.js
In a next.js environent this line was throwing because `window` is undefined. This module was imported transitively via a component importing the ref directive, which in turn imports async-directive, which in turn imports the file where the fix was added.
Related #3156 
I notice [there are tests](https://github.com/lit/lit/pull/3156/files#diff-1b9f30d8d53005f52e428cbb9c40a8b467742740f50445af9050f67c11944c43R23) for `lit-html` in that PR which import the ref directive, so i'm not sure how they pass (or conversely how it is not working for me)
=> disabled shadydom in node dev build

.changeset/thick-wasps-love.md, .changeset/tidy-lamps-rest.md, package-lock.json, package.json, packages/lit-starter-js/package.json, packages/lit-starter-ts/package.json, packages/reactive-element/package.json, packages/reactive-element/src/test/node-dom-shim.ts, packages/reactive-element/src/test/node-imports.ts, packages/reactive-element/src/test/node-shim-html-element.ts, rollup-common.js
Fixes #3559 
The replace of `extends HTMLElement` with `extends (globalThis.HTMLElement ?? HTMLElement)` was not happening due to the `includes` option for `@rollup/plugin-replace` not working properly. Updating the version fixes this.
Note: To keep a single version of the plugin in the monorepo, the version was also updated for the starter kits.
Now the outputs look like:
Dev Node build:
```js
class ReactiveElement
extends (globalThis.HTMLElement ?? HTMLElement) {
```
Prod Node build:
```js
class v extends(globalThis.HTMLElement??i)
```
I added another test in the vein of the node-import tests. It feels like there are a lot of scripts for the node tests now but unsure if there's a better way to do this.
=> [reactive-element] Fix Node build auto-shimming of `HTMLElement` to respect existing global shim

.changeset/flat-readers-brush.md, packages/localize-tools/src/formatters/xliff.ts, packages/localize-tools/testdata/extract-xliff-merge/goldens/foo.ts, packages/localize-tools/testdata/extract-xliff-merge/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-merge/input/foo.ts, packages/localize-tools/testdata/extract-xliff-merge/input/xliff/es-419.xlf
Fixes a bug introduced in https://github.com/lit/lit/pull/3514 where we were not correctly updating XLIFF messages that contained placeholders, because of an index-invalidation bug in the way we were deleting the contents of existing nodes.
Fixes https://github.com/lit/lit/issues/3569
=> [localize] Fix XLIFF serialization regression

.changeset/tough-beans-marry.md, packages/labs/ssr/src/lib/element-renderer.ts
This lets you write mixins against ElementRendererConstructor without errors that you're not implementing abstract members.
For example, mixins are useful for modifying existing renderers:
```ts
const excludeElements = (
renderer: ElementRendererConstructor,
excludedTagNames: Array<string>
) => {
return class ExcludeElementRenderer extends renderer {
static matchesClass(
ceClass: typeof HTMLElement,
tagName: string,
attributes: Map<string, string>
) {
return !excludedTagNames.includes(tagName) && super.matchesClass(ceClass, tagName, attributes);
}
};
};
```
=> Remove abstract from members of ElementRendererConstructor type

.changeset/slimy-mails-clean.md, packages/labs/virtualizer/src/layouts/shared/SizeGapPaddingBaseLayout.ts
fixes #3285
Ensure that the layout for the Virtualizer is updated when a new `padding` value is provided.
=> [labs/virtualizer] Trigger reflow after padding is set

.changeset/wild-turtles-rush.md, packages/labs/virtualizer/src/events.ts, packages/labs/virtualizer/src/test/layouts/flow.test.ts, packages/labs/virtualizer/src/test/scenarios/element-and-directive-parity.test.ts, packages/labs/virtualizer/src/test/scenarios/visibility-changed-events.test.ts, packages/labs/virtualizer/src/virtualize.ts
This PR solves the event behavior differences between RangeChangedEvent and VisibilityChangedEvent per #3051 
Both event types are ensured not to bubble up and must be listened for now on the `<lit-virtualizer>` itself or the host element in the case of `virtualize()` directive.
=> [labs/virtualizer] RangeChangedEvent and VisibilityChangedEvent no longer bubble up

.changeset/happy-apricots-pay.md, packages/labs/context/src/lib/create-context.ts
Small change to get more accurate types. Should be non breaking as the second type parameter has a default and doesn't have to be specified.
cc @benjamind
=> [context] Add type parameter for key to createContext()

.changeset/proud-beans-bake.md, packages/labs/context/README.md, packages/labs/context/src/lib/context-root.ts, packages/labs/context/src/lib/controllers/context-consumer.ts, packages/labs/context/src/test/late-provider_test.ts, packages/tests/src/web-test-runner.config.ts
Fixes https://github.com/lit/lit/issues/2765
This deduplicates context requests by element identity and callback identity, so that if an element moves around the DOM, causing it to fire multiple context-request events before a provider is available, its context callback is only called once. This behavior is similar to addEventListener() which will call a callback only once no matter how many times it's added for a single event.
This PR also fixes a potential memory leak by using WeakRefs to hold on to both elements and their context request callbacks. We need WeakRefs because when we receive a context-provider event we need to loop over all element/callback pairs for that context and dispatch events. WeakMaps do not allow iterating over entries.
cc @benjamind
=> Make ContextRoot deduplicate context requests by element and callback identity

.github/workflows/sauce-ie11.yaml, .github/workflows/sauce.yaml
To alleviate ETXTBSY errors or timeouts due to multiple sauce tests being run simultaneously.
=> [infra] Don't run sauce SSR tests in parallel

package-lock.json, package.json
Relevant changelog entries from https://github.com/google/wireit/blob/main/CHANGELOG.md
- Better attribute socket errors, and don't crash when a socket is closed
unexpectedly.
- Fixed infinite loops that could occur in watch mode when a script failed, but
still emitted output that was configured as the input files for another
script.
- Don't clear the console or emit "no-op" style log messages in watch mode for
iterations that don't do anything useful.
- It is now allowed to define a wireit script without a corresponding entry in
the `scripts` section. Such scripts cannot be directly invoked with `npm run
<script>` or similar, but they can still be used as dependencies by other
wireit scripts.
=> [infra] Bump wireit version from 0.9.3 to 0.9.5

.changeset/dry-ravens-drop.md, packages/labs/analyzer/src/lib/types.ts, packages/labs/analyzer/src/test/types_test.ts, packages/labs/analyzer/test-files/js/types/external.js, packages/labs/analyzer/test-files/js/types/module.js, packages/labs/analyzer/test-files/js/types/package.json, packages/labs/analyzer/test-files/ts/types/src/module.ts
TS doesn't consider types provided in JSDoc comments as having any effect in `.ts` files, even though they're still accessible in the AST. This PR updates the analyzer to match this behavior and also copies/ports the type tests to JS to confirm that JSDoc comments still affect the analysis of `.js` files.
This PR is easier to read with [leading whitespace removed](https://github.com/lit/lit/pull/3658/files?w=1).
=> [labs/analyzer] Don't extract JSDoc types in TS. Port type tests to JS.

.changeset/fast-apes-cross.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes #3566 
The fix is to call the initial `host.requestUpdate()` (which is there to get the element to update and see the PENDING state of the task) in a microtask, so that it goes after the change-in-update check.
=> Fix change-in-update warning from Tasks

.github/workflows/release-image.yaml
Closes #3668 
Here is one of the solutions, suggested by the [GIthub Security Guides](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections).
=> Feat: Avoid Script Injection Risks on Github Action Workflows

.changeset/soft-turtles-protect.md, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/lit-html/src/experimental-hydrate.ts
Moves the `` marker for identifying nodes that hydration needs to stop at (to hydrate attribute/property/event/element parts and remove `defer-hydration` attributes) from after the start tag to before it.
This makes it compatible with bindings to the open tag of "raw text elements" (`style`, `script`, `textarea`, `title`) whose child content is parsed as raw text rather than nodes. This requires a quick lookahead in the opcode parsing to note whether the node in question has bindings, and if so write out the node marker before the tag is opened.
This had the side-effect of simplifying the condition around whether to completely finish writing out the open tag or not, since now that condition is only whether the node is a custom element or not.
Fixes #3663
=> [labs/ssr] Emit lit-node marker before node to support raw text nodes.

.changeset/mighty-hornets-explain.md, packages/localize-tools/src/program-analysis.ts, packages/localize-tools/src/tests/transform.unit.test.ts, packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-fresh/goldens/data/xliff/zh_CN.xlf, packages/localize-tools/testdata/extract-xliff-fresh/goldens/foo.ts, packages/localize-tools/testdata/extract-xliff-fresh/input/foo.ts
Fixes handling of nested html-tagged template expressions in lit localize analysis.
For example, the following example was analyzed incorrectly:
```ts
msg(html`Hello <b>${html`<i>World</i>`}</b>!`);
```
We combine runs of HTML markup and expressions so that we have fewer placeholders during translation, so we pass the template through an HTML parser, nested expressions and all. The problem was that if the nested expressions contained HTML, those would get parsed as part of the outer message, which would corrupt the analyzed template. The fix was to replace nested expressions with placeholders (the index) during HTML parsing (because we don't need the HTML parser to see the contents of expressions at all) and then substitute the original expression back after HTML parsing.
Fixes …
=> [localize] Fix handling of nested HTML

package.json
eslint doesn't apply `--ignore-pattern` to any full paths passed to it but lint-staged *only* passes full paths. This replaces the eslint `--ignore-pattern` option with a more specific lint-staged glob.
=> Ignore `/examples/` when lint-staged runs eslint.

.changeset/green-bottles-hear.md, packages/labs/ssr/README.md
Fixes https://github.com/lit/lit/issues/2665
=> Fix a few things in the labs/ssr readme

.github/workflows/benchmarks.yml
Update the condition check to be the same as we use for the Sauce workflows so it'll only run if the head and base repo of the PR are the same, i.e. the lit/lit repo.
=> [infra] Skip benchmarks workflow for forks

.github/workflows/benchmarks.yml, .github/workflows/release-image.yaml, .github/workflows/release.yaml, .github/workflows/sauce-ie11.yaml, .github/workflows/sauce.yaml, .github/workflows/starter-kits.yaml, .github/workflows/tests.yml
Updates `actions/checkout` and `actions/setup-node` to v3. Per their changelog, the only breaking part is the default node version used for the workflow being bumped to node16 instead of node12.
This should fix warnings like below that we get in workflows.
=> [chore] Update github actions

.github/workflows/release.yaml
Release workflow was broken by https://github.com/lit/lit/pull/3724 as it added the `cache` option to the setup-node action but the `package-lock.json` file wasn't available because the repo hadn't been checked out yet.
This fixes the ordering and accounts for the checkout happening in a nested `lit/` directory.
=> [infra] Reorder release workflow actions for npm caching

.changeset/fifty-forks-decide.md, packages/lit-element/src/lit-element.ts, packages/lit-element/src/test/lit-element_dev_mode_test.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_dev_mode_test.ts
These are all dev mode things, but I think it's good to clean this up too so we don't collect cruft over time. Less code is easier to maintain.
=> Remove Lit 1 -> Lit 2 migration warnings

.changeset/healthy-planes-smash.md, .changeset/yellow-starfishes-rush.md, packages/lit-element/src/index.ts, packages/lit-element/src/lit-element.ts, packages/lit-element/src/test/lit-element_test.ts, packages/reactive-element/README.md, packages/ts-transformers/src/tests/idiomatic-decorators-test.ts
This removes `UpdatingElement` from lit-element.ts and decorators from `index.ts`
=> [lit-element] Remove lit-element@2.x back-compat exports

.changeset/popular-shoes-carry.md, .eslintignore, .gitignore, .prettierignore, packages/lit-html/src/directives/style-map.ts, packages/lit-html/src/test/directives/style-map_test.ts
fix: #3767
Added test to verify that issue existed before, and fixed.
The fix is simple - remove the `!important` directive if exists, and set the `priority` argument in the call to `setProperty`
=> [lit-html] styleMap fails when update contains priority directive

packages/labs/ssr-client/src/lib/hydrate-lit-html.ts
I brought in https://github.com/lit/lit/pull/3720 to `3.0` branch by merging in `main` which broke the build step.
This PR brings in the change done in https://github.com/lit/lit/pull/3758 to the copied code in `labs/ssr-client`.
=> [labs/ssr-client] Fix for removing `@types/web-ie11` dep

.changeset/slimy-clouds-roll.md, packages/lit-html/src/directives/style-map.ts, packages/lit-html/src/test/directives/style-map_test.ts, packages/tests/src/web-test-runner.config.ts
=> Allow numbers to be used as values in styleMap()

packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Otherwise binding the value `undefined` to a boolean part would mean `toggle` rather than `false`
=> Coerce toggleAttribute's second arg to boolean

.changeset/angry-rockets-search.md, package-lock.json, packages/localize-tools/package.json, packages/ts-transformers/package.json
Fixes #3739 
By relaxing the typescript version from `~4.7.4` to `^4.7.4`, we allow it to use `4.8` and `4.9` as well. This fixes the problem with localize-tools where it uses typescript 4.7, but the project used 4.8 or 4.9. This breaks because of breaking changes between 4.7 and greater.
Note: so `5.0` is not valid here. I'm not sure whether we want to allow that yet.
=> Relax the typescript version for localize-tools

packages/reactive-element/src/decorators/query.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
=> [reactive-element] Only use symbol keys for properties added as private storage.

.changeset/hip-badgers-burn.md, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/test/scenarios/immediate-sizing.test.ts
Handle uninitialized layout in `_childrenSizeChanged`.
Because the ResizeObserver starts listening very early it is possible that the layout has not been imported and initialized when a children has updated.
Fixes #3726
=> [labs/virtualizer] handle uninitialized layout in _childrenSizeChanged

.changeset/big-ducks-decide.md, packages/reactive-element/src/reactive-element.ts
This makes it much easier to maintain state for an element during HMR because keys stay the same across different versions of the class.
=> Use Symbol.for in dev mode

.changeset/hot-rabbits-promise.md, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/lit-html/src/static.ts, packages/lit-html/src/test/static_test.ts
Fixes #2246 
SSR of static html was erroring due to mismatch of `partIndex` as described in issue above because we were comparing that to the length of the `values` array in `TemplateResult`.
When a static value was the last value of a template, it ended up adding the static value object to the `TemplateResult`. This wasn't an issue if a non-static value was the last value.
i.e.
```js
const tag = literal`p`;
const template = html`<${tag}>Hello, ${this.name}!</${tag}`;
```
resulted in
```js
{
strings: ['<p>Hello, ', '!</p>'],
values: ['World', {_$litStatic$: 'p', r: Symbol()}],
}
```
when it should be
```js
{
strings: ['<p>Hello, ', '!</p>'],
values: ['World'],
}
```
In client rendering this wasn't an issue as we just never accessed that value. In SSR, it was causing the error due to the …
=> [lit-html] Static `html` should not add consumed value to `TemplateResult`

.changeset/silly-gorillas-arrive.md, packages/labs/virtualizer/README.md
Changed the old `scrollElementIntoView()` in the README to use `element(x).scrollIntoView()`
=> [labs/virtualizer] Update README.md

.changeset/mean-elephants-cough.md, packages/labs/context/src/lib/context-root.ts, packages/labs/context/src/test/late-provider_test.ts
Fixes #3833.
ContextRoot now stores the root target (`event.composedPath()[0]`) to avoid issues with event re-targeting.
=> Fixes ContextRoot for requesters in nested shadowRoots

.changeset/cool-bottles-hunt.md, package-lock.json, packages/labs/ssr/src/lib/module-loader.ts, packages/labs/ssr/src/test/lib/module-loader_test.ts, packages/labs/ssr/src/test/test-files/module-loader/module-package-import.js, packages/labs/test-projects/test-module-package/index.import.js, packages/labs/test-projects/test-module-package/index.js, packages/labs/test-projects/test-module-package/index.module.js, packages/labs/test-projects/test-module-package/package.json
This was causing errors in lit.dev repo running eleventy plugin in VM mode.
This was when trying to load `tslib` which has these package exports
```json
"exports": {
".": {
"module": "./tslib.es6.js",
"import": "./modules/index.js",
"default": "./tslib.js"
},
```
and we actually want the "module" export, as the "import" one is causing the error above.
=> [labs/ssr] Add "module" to condition name to resolve for Module Loader

.changeset/modern-numbers-turn.md, packages/labs/analyzer/src/lib/javascript/jsdoc.ts, packages/labs/analyzer/src/lib/model.ts, packages/labs/analyzer/src/test/lit-element/jsdoc_test.ts, packages/labs/analyzer/src/test/vanilla-element/jsdoc_test.ts, packages/labs/analyzer/test-files/js/jsdoc/element-a.js, packages/labs/analyzer/test-files/js/vanilla-jsdoc/element-a.js, packages/labs/analyzer/test-files/ts/jsdoc/src/element-a.ts, packages/labs/analyzer/test-files/ts/vanilla-jsdoc/src/element-a.ts
Closes #3811
```ts
/**
* @license
* Copyright 2022 Google LLC
* SPDX-License-Identifier: BSD-3-Clause
*/
import {LitElement} from 'lit';
import {customElement} from 'lit/decorators.js';
/**
* @cssProperty [--default-no-description=#324fff]
* @cssProperty [--default-with-description=#324fff] Description for --default-with-description
* with wraparound
* @cssProperty [--default-with-description-dash=#324fff] - Description for --default-with-description-dash
*/
@customElement('element-a')
export class ElementA extends LitElement {}
```
```json
{
"cssProperties": [
{ "name": "--default-no-description", "default": "#324fff" },
{ "name": "--default-with-description", "default": "#324fff" },
{
"name": "--default-with-description-dash",
"description": "Description for …
```
=> [labs/analyzer] CSS variable fallbacks

.changeset/funny-peas-try.md, packages/labs/ssr-react/src/lib/node/wrap-create-element.ts, packages/labs/ssr-react/src/test/integration/enable-lit-ssr_test.tsx, packages/labs/ssr-react/src/test/integration/runtime-jsx_test.tsx
Fixes #3823 
The runtime jsx mode were never affected by this as they always get children passed in via the props object.
=> [labs/ssr-react] Handle children passed in via props

.changeset/green-zoos-sleep.md, packages/labs/virtualizer/src/Virtualizer.ts
Internal typescript restrictions highlighted called out a use of innerHTML assignment a couple of types that were not explicit enough in Virtualizer.ts
=> Switch innerHTML to textContent and add some explicit types

.changeset/few-feet-design.md, packages/lit-html/src/lit-html.ts
We weren't resetting the currentNode of the shared TreeWalker after either template prep or template cloning. This caused the TreeWalker to hold on to the last currentNode of the last tree walk.
This should always be after a clone because I can't think of a situation where we prep a template but don't immediately render it. So for the fix I set currentNode after a template clone. You can't set `TreeWalker.currentNode` to `null`, so I set it to the document.
=> Fix a memory leak with the shared TreeWalker

.changeset/clever-kids-mix.md, packages/labs/ssr-client/package.json
Fixes #3899 
This dependency bump ensures users have the needed version of `lit-html` installed for hydration code to work.
=> [labs/ssr-client] Bump `lit-html` dependency version

.changeset/tall-insects-confess.md, packages/reactive-element/src/decorators/state.ts, packages/reactive-element/src/reactive-element.ts
During studying the package I noticed `HasChanged` type could have be used in different locations in the project and it's easier for a new comer to travel and understand the library if they want to contribute.
This change doesn't affect the overall logic (just TypeScript types),  I ran the tests and all passed.
=> [reactive-element] Reusing HasChanged type

.changeset/plenty-wolves-return.md, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
=> [labs/ssr] Allow rendering of non-array iterables

.changeset/eleven-mayflies-ring.md, packages/reactive-element/src/reactive-element.ts
We had reports of problems if users added their own `_initialize()` method.
My initial change was to make the name `__initialize` and make the method private so at TypeScript would error. But I couldn't find any place that actually overrode `_initialize()`, so I inlined it into the constructor. We should run this through google3 as a smoke test.
I also made `static _initializers` private. It was already being renamed in prod.
=> Make _initialize and static _initializers private

.changeset/real-kings-sell.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_dev_mode_test.ts
Adding this warning now lets us remove the return of `this.performUpdate()` from `scheduleUpdate()` in the future. Otherwise async overrides would cause a silent break.
=> Warn on async overrides of performUpdate()

.changeset/heavy-bugs-vanish.md, packages/reactive-element/src/decorators/base.ts
Fixes #3241 
This specifically affected decorators made with `decorateProperty` which also includes the labs/context decorators. This is a workaround until something like https://github.com/microsoft/TypeScript/issues/52119 is implemented.
Manually tested by creating a project with multiple versions of `reactive-element` installed, and replacing the nested version with one built with these changes applied.
=> [reactive-element] Make decorators accept `ReactiveElement` from elsewhere

.changeset/eighty-bananas-drive.md, packages/labs/context/README.md, packages/labs/context/src/lib/decorators/consume.ts, packages/labs/context/src/lib/decorators/provide.ts, packages/labs/context/src/test/context-provider_test.ts, packages/labs/context/src/test/type_check_test.ts
Fixes #3732 
As far as I can tell, the change just works. All tests still pass.
=> [labs/context] Make `@provide` and `@consume` support optional and private properties.

.changeset/changelog-lit.cjs
Update changelog generation to add a thanks with link to the author of a community authored change. Lit team members are filtered out.
For example when I removed `augustine` from the filter, `npm run version` locally generated the following changelog entry:
[#3905](https://github.com/lit/lit/pull/3905) [f8d72859](https://github.com/lit/lit/commit/f8d7285976390bbb35c540eb7b516f3748064d19) Thanks [@augustjk](https://github.com/augustjk)! - Handle non-array iterables including map directive in child parts
Tested changesets that include multiple authors with a lit core member.
```
author:testone
author:testtwo
author:AndrewJakubowicz
```
This will render:
```
- [#3901](https://github.com/lit/lit/pull/3901) [`82e9f370`](https://github.com/lit/lit/commit/82e9f3708973709e916ccbb6d8a450110dea7755) …
```
=> Add thank you to community authored changes.

.changeset/thirty-months-crash.md, .eslintignore, .prettierignore, packages/labs/virtualizer/.gitignore, packages/labs/virtualizer/README.md, packages/labs/virtualizer/package.json, packages/labs/virtualizer/src/support/method-interception.ts, packages/labs/virtualizer/src/support/resize-observer-errors.ts, packages/labs/virtualizer/src/test/helpers.ts, packages/labs/virtualizer/src/test/scenarios/element-and-directive-parity.test.ts, packages/labs/virtualizer/src/test/support/method-interception.test.ts, packages/labs/virtualizer/src/test/support/resize-observer-errors.test.ts
I really struggled to find a coherent way to offer conventional methods to work around the obnoxious "ResizeObserver loop limit exceeeded" class of errors and whether or not to even do this as part of Virtualizer itself.  In the end, I think this provides enough value to warrant its addition to Virtualizer until such time as we might discover a change to Virtualizer itself or find an alternative approach that works just as well.
I factored out what we do in our test helpers into functions exported in support modules so they can be imported by end-users and leveraged in their test and/or live environments.
=> [labs/virtualizer] Add support methods to work around ResizeObserver loop limit exceeded errors

.changeset/eleven-mayflies-ring.md, packages/reactive-element/src/reactive-element.ts
This reverts commit 338e1b1ce49f307f37f91876643bed400e687c6d.
An internal subclass of ReactiveElement still needs to be able to delay calling _initialize until hydration, long after construction.
FYI @justinfagnani
=> Revert "Make _initialize and static _initializers private (#3895)"

.changeset/eighty-gifts-sparkle.md, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/integration/tests/basic.ts
Fixes #3939 
The check for `node.attrs.length > 0` made it so that op code for 'possible-node-marker' was never getting added even for nested custom elements if they had no attributes. Removing that condition check fixes this. There shouldn't be much extra work being done by removing this condition as most of the code in the block are for loops over the derived `attrInfo` array which would be empty if `node.attrs.length` is `0`.
=> [labs/ssr] Fix hydration for nested custom elements without attributes

.changeset/slimy-sloths-prove.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
fixes #3946
Task now will not throw errors unless `taskComplete` is specifically called. In that case the user should catch the error on `taskComplete`.
**GOTCHAS:**
The following case is a gotcha but it's just how promises work:
```ts
taskThatThrowsAnError.taskComplete.catch(() => {});
// this will throw an error. User needs to catch here too or await previous line
await taskThatThrowsAnError.taskComplete;
```
see reproduction of native behavior [here](https://lit.dev/playground/#gist=3c498dfa3f2dc6f066527b561a015a32)
=> Make taskComplete a getter so that errors are only thrown when requested

.changeset/heavy-candles-end.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fix bug with taskComplete not returning a rejected promise if requested on ERROR state
=> taskComplete reject promise if requested in error state

.changeset/thick-mayflies-compete.md, packages/labs/context/src/lib/value-notifier.ts, packages/labs/context/src/test/context-provider_test.ts, packages/labs/context/src/test/test_util.ts
Fixes: https://github.com/lit/lit/issues/3954
The issue is that the `dispose` function was not being passed when adding the callback.
So if the element was removed before receiving any updates, it would never get access to the dispose function and could not remove the callback from the Map resulting in the unbounded leak.
The reason the element does not leak if it received an update is because `updateObservers` passes the `dispose` function:
https://github.com/lit/lit/blob/4f71df99e6df2e5fb31259c53f01f2e87209e3d5/packages/labs/context/src/lib/value-notifier.ts#L47-L51
Tested by adding a memory test (and checking that it fails by a huge amount without fix applied).
=> [lit-labs/context] Fix context memory leak when subscribe is true.

.changeset/nasty-deers-search.md, packages/reactive-element/src/reactive-element.ts, scripts/check-size.js
* Tear off Object methods to allow them to be renamed (not sure if Terser does this though) and to eliminate a dereference at the use site.
* Use logical assignment and chaining in `requestUpdate()` to collapse three property references to one.
* Remove a local variable in `requestUpdate()`
* Replace `notEqual` implementation with `Object.is`. This is the same behavior _except_ with +0 and -0, which are considered not the same with `Object.is`, but are equal under `===`.
I considered using `Object.hasOwn` since we have a lot of `x.hasOwnProperty()` calls, but `Object.hasOwn` is part of ES2022... it is polyfillable though, so maybe we should consider it?
=> Some code golf on ReactiveElement

.changeset/grumpy-stingrays-grab.md, packages/lit-html/src/directives/ref.ts, packages/lit-html/src/test/directives/ref_test.ts
Fixes https://github.com/lit/lit/issues/3965
`ref()` already handled undefined refs correctly, so this is a one-char change.
=> [lit-html] Allow undefined to be passed to the ref() directive

.changeset/smooth-swans-sin.md, packages/lit-html/src/directives/ref.ts
Make `RefOrCallback` generic like `Ref<T>`.
Fixes #3966
=> [lit-html] Make RefOrCallback generic

.changeset/calm-deers-hope.md, packages/labs/react/src/create-component.ts
https://github.com/lit/lit/pull/3977 causes the `suppressHydrationWarning` prop to actually get emitted as an attribute on the host element for wrapped components being server rendered as shown in this test output: https://github.com/lit/lit/actions/runs/5361038597/jobs/9726603547?pr=3977#step:8:443
The `suppressHydrationWarning` only has effect on React components in the client so there's no reason to add it if in node mode.
=> [labs/react] Only add `suppressHydrationWarning` prop in the client

.changeset/weak-roses-laugh.md, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Similar to: https://github.com/lit/lit/pull/2642
Thank you @rictic for proposing this!
**NOTE:** changing technique to a branding tag function.
=> [lit-html] change CompiledTemplate h field to a TemplateStringsArray

.changeset/fresh-dryers-tap.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes https://github.com/lit/lit/issues/3995
This is part one of full task cancellation support. Up next will be a way for an author to either pass in an AbortSignal or manual cancel the task with `task.abort()`.
=> Provide an AbortSignal to task functions

.changeset/flat-pugs-push.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes https://github.com/lit/lit/issues/3997
This makes task cancellation possible, but manual. It's _maybe_ desirable in some cases to somehow allow passing an AbortSignal into the task and composing it with the signal we automatically create, and but the exact requirements and shape of that API aren't clear yet. Chaining tasks is one of the more obvious use cases, but this might be doable already because aborting a task will reject its `taskComplete` promise, which can be passed to downstream tasks.
=> Add a Task.abort() method

README.md
@lit-labs/context was missing from the list of packages in the Labs section of the readme.md
=> Update README.md to include @lit-labs/context

.changeset/heavy-planets-obey.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes #2367 
Supersedes #2836 
This adds an `initialValue` config option. If set, the task is put into the COMPLETE status and `initialValue` is assigned to the current value of the task. Initial args are read off synchronously so that the task won't auto-run until the args change.
This is useful for when an element has the initial data available synchronously (maybe from hydration?) and wants to make the task look like it has completed a first run.
=> [labs/task] Allow tasks to have an initial value

.changeset/chilled-drinks-travel.md, .changeset/five-baboons-speak.md, packages/labs/ssr-client/src/lib/hydrate-lit-html.ts, packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/directives/cache.ts, packages/lit-html/src/experimental-hydrate.ts, packages/lit-html/src/test/directive-helpers_test.ts, packages/lit-html/src/test/directives/cache_test.ts
Change is an independent part of https://github.com/lit/lit/pull/3984
Fix `isTemplateResult` return type to include `CompiledTemplateResult`s, and then fix locations in `lit` that didn't handle `CompiledTemplate`s. Primarily the `cache` directive.
- Fixes the return type of `isTemplateResult` to return the correct type (as per current implementation): a `TemplateResult` or a `CompiledTemplateResult`.
- Fix cache directive to work with both uncompiled and compiled templates using a helper to access the template strings array.
- Made it explicit that `hydration` and `experimental-hydration` do not work with compiled templates by making the check more strict. *Maybe could add a dev mode error?*
- Added compiled template cache directive unit test, and `isTemplateResult` type tests.
I marked …
=> [lit-html][labs/ssr-client] Fix compiled template support

.changeset/spicy-mugs-eat.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes https://github.com/lit/lit/issues/2301
Supersedes https://github.com/lit/lit/pull/2821
=> [labs/task] Infer the return type of Task.render()

.changeset/chilled-jeans-march.md, package-lock.json, packages/labs/task/package.json, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
Fixes https://github.com/lit/lit/issues/4003
Fixes https://github.com/lit/lit/issues/1808 (there were some issues in the jsdoc example)
This is a breaking change.
This also adds `'afterUpdate'` as a valid value for `autoRun`, which preserves the existing timing. That's useful for tasks that need to read state changes in update, such as DOM.
=> [labs/task] Run tasks in update instead of updated

.changeset/thirty-mugs-lay.md, packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-a.ts, packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-events.ts, packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-props.ts, packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-slots.ts, packages/labs/gen-wrapper-react/src/index.ts
It should not emit deprecated syntax.
=> [labs/gen-wrapper-react] Update to emit `createComponent` with option object syntax

.changeset/serious-turkeys-warn.md, packages/reactive-element/src/reactive-element.ts
Rename `ReactiveElement._initialize` to `__initialize`, make it private, and remove the `@internal` annotation. This will help prevent collisions with subclasses that implement their own `_initialize` method, while using development builds.
Thanks for @thepassle for enabling the development export condition by default in Web Dev Server, which highlighted this issue!
=> Rename ReactiveElement._initialize to __initialize

.changeset/green-knives-appear.md, packages/labs/react/src/create-component.ts, packages/labs/react/src/test/create-component_test.tsx
- Refactored to move implementation directly into render function of `forwardRef` rather than creating a class component. This removes an extra React component of the same name showing up in the component tree.
- Removed deprecated old signature taking separate arguments.
- Simplified typings for `WebComponentProps` and `ReactWebComponent` and added jsdoc.
=> [labs/react] Remove deprecated syntax and remove extra class component

.github/workflows/benchmarks-report.yaml
This is the first step in allowing benchmarks to run for PRs from forks.
Approach is taken from https://github.com/andrewiggins/tachometer-reporter-action#working-with-forks
The [`workflow_run` hook](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) for GitHub Actions only works when the workflow file is present in the default branch. This PR is to add this, but looks for workflow named "Benchmarks Test".
Once merged, I'll update this PR https://github.com/lit/lit/pull/4038 to rename the Benchmarks workflow to Benchmarks Test to see if this report result workflow works.
=> [infra] Add benchmarks report workflow

.github/workflows/benchmarks-report.yaml, .github/workflows/benchmarks.yml
Follow up to https://github.com/lit/lit/pull/4041
This renames the workflow name we look for in the reporting workflow to "Benchmarks" instead of "Benchmarks Test" and updates the existing benchmarks workflow to upload report artifacts instead of writing comments directly. This allows the reporting workflow to download and write to comment.
The workflow doesn't work on this PR because the workflow needs to be present in the default branch.
This same code has been merged to a fork and tested in this PR: https://github.com/augustjk/lit/pull/2
See the tachometer benchmark results showing in the comment. This was created with 2 separate "Report Benchmark Results" workflow runs: https://github.com/augustjk/lit/actions
One to create the comment when benchmarks begin, and one to fill in the …
=> [infra] Allow benchmarks workflow in fork PRs

.changeset/seven-fans-sniff.md, packages/labs/react/src/create-component.ts, packages/labs/react/src/test/create-component_test.tsx
Fixes #4060
Using `React.DetailedHTMLProps` includes the optional `ref` prop with a ref that should return the element class itself. This is the same type used for built-in elements in `React.JSX.IntrinsicElements`.
We only need the `React.DetailedHTMLProps` for `WebComponentProps` meant to be used for `IntrinsicElements` whereas the internal type for the component props still just needs the `React.HTMLAttributes` as we did before. So I added a `ElementProps` type that's shared between those.
Test for this could be better but I just added a small build-time check for now.
I want to better refactor the test to really separately test the different parts of `create-component.ts` instead of the single test render harness trying pass props to a div, an x-foo, and the wrapped component like …
=> [labs/react]  Fixes `WebComponentProps` type to accept `ref` prop

.changeset/gentle-pillows-buy.md, packages/labs/context/src/lib/context-request-event.ts, packages/labs/context/src/lib/context-root.ts, packages/labs/context/src/lib/controllers/context-consumer.ts, packages/labs/context/src/lib/controllers/context-provider.ts, packages/labs/context/src/lib/value-notifier.ts, packages/labs/context/src/test/context-provider_test.ts, packages/labs/context/src/test/late-provider_test.ts
When context-provider event is dispatched, and `event.canTakeOverSubscriptions` is true, then parent providers of the same context can create or push to the `event.movedSubscriptions` array to indicate callbacks that they will no longer handle, but that the new provider should.
Fixes https://github.com/lit/lit/issues/2763
=> [labs/context] Late loaded elements can take over the context subscriptions for their children

.changeset/shaggy-dingos-press.md, packages/labs/task/src/task.ts, packages/labs/task/src/test/task_test.ts
In TypeScript:
- `unknown` is the top type: everything can be assigned to `unknown`, and `unknown` can be only assigned to `unknown`.
- `never` is the bottom type: `never` can be assigned to everything, and only `never` can be assigned to `never`.
- Assuming a `Cat` can be assigned to an `Animal`, but not the other way around:
- (read-only) arrays are covariant: a `Cat[]` can be assigned to an `Animal[]`, but not the other way around. In other words, arrays don't change the "order" of types, as expected.
- function arguments are contravariant: a `(x: Animal) => boolean` can be assigned to a `(x: Cat) => boolean`, but not the other way around. In other words, function arguments flip the "order" of types.
The right-hand of the `extends` in `MaybeReturnType` is a `(...args: unknown[]) => ?`. …
=> [labs/task] Fix Task.render()'s return type always being undefined

.changeset/gentle-pillows-buy.md
Since context is still 0.3.3, a breaking change is fine in a minor bump.
=> [labs/context] Change labs/context bump to minor

.changeset/kind-deers-act.md, packages/labs/react/src/create-component.ts, packages/labs/react/src/test/create-component_test.tsx
Fixes #4093 
This was a regression introduced the 2.0.0 update to refactor `createComponent` and simplify types.
Added back the removed `Omit` from `React.HTMLAttributes`
https://github.com/lit/lit/pull/4027/files#diff-70e2e47659157c4129a63acfad45aa00d53e5314c322b4acc9e677cb1cbaf97aL27
and added a build-time type test for this.
=> [labs/react] Prefer provided event handler types over React's built-in type

package-lock.json, packages/ts-transformers/package.json
ts-clone-node now officially supports TypeScript 5.0, reducing duplication of typescript in our node modules.
=> Update ts-clone-node to latest

.changeset/popular-masks-burn.md, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/test/helpers.ts, packages/labs/virtualizer/src/test/scenarios/item-changes.test.ts, packages/labs/virtualizer/src/test/scenarios/sizing-and-styling.test.ts, packages/labs/virtualizer/src/virtualize.ts
Fixes #4080 
Credit to @graynorton for the solution.
The changes to `virtualizer` directive's `update()` method added in https://github.com/lit/lit/pull/3133 to always `return this.render()` created a race/conflict such that the MutationObserver responsible for updating the host element would fire before the correct sizes were calculated by the virtualizer. This change now conditionally returns `noChange` to preserve the fix but also defer to virtualizer handling more updates where possible.
There was still a possibility of race happening between virtualizer state change and the mutation observer, so updated the `_updateDOM()` method on virtualizer to always call `_finishDOMUpdate()`;
Added a test for checking regression.
=> [labs/virtualizer] Enable host to resize when total item size changes

.changeset/nervous-frogs-approve.md, packages/labs/compiler/package.json
Umbrella Issue: https://github.com/lit/lit/issues/189
RFC: https://github.com/lit/rfcs/pull/21
Publish compiler issue: https://github.com/lit/lit/issues/4101
This change is scoped to the 3.0 branch, and makes it so that the compiler can be published/released as a pre-release!
This will make it possible to `npm install @lit-labs/compiler` and use it!
None!
=> [lit-labs/compiler] pre-release compiler on 3.0 branch

.changeset/calm-avocados-end.md, .changeset/lazy-radios-rhyme.md, .changeset/selfish-lions-juggle.md, packages/labs/analyzer/src/lib/custom-elements/custom-elements.ts, packages/labs/analyzer/src/lib/javascript/jsdoc.ts, packages/labs/analyzer/src/lib/model.ts, packages/labs/analyzer/src/test/lit-element/events_test.ts, packages/labs/analyzer/src/test/lit-element/jsdoc_test.ts, packages/labs/analyzer/test-files/js/events/element-a.js, packages/labs/analyzer/test-files/js/jsdoc/element-a.js, packages/labs/analyzer/test-files/ts/events/src/element-a.ts, packages/labs/analyzer/test-files/ts/jsdoc/src/element-a.ts
- adds tests
- support `@cssproperty`, `@cssprop`, `@csspart` (all lowercase)
- support `@fires {Type} event-name - description`
- support `@cssProp {<syntax>} [--name=default] - description`
```js
/**
* @fires event-name
* @fires event-name description
* @fires event-name - description
* @fires event-name: description
* @fires event-name {Type}
* @fires event-name {Type} description
* @fires event-name {Type} - description
* @fires event-name {Type}: description
* @fires {Type} event-name
* @fires {Type} event-name description
* @fires {Type} event-name - description
* @fires {Type} event-name: description
* @slot name
* @slot name description
* @slot name - description
* @slot name: description
* @cssProp [--name=default]
* @cssProp [--name=default] description
* @cssProp …
```
=> fix(analyzer): jsdoc type order, lowercase tags, css syntax

.changeset/analyzer-accessors.md, .changeset/analyzer-constructor-assigned.md, .changeset/analzyer-readonly-jsdoc.md, .changeset/analzyer-readonly-ts.md, packages/labs/analyzer/src/lib/javascript/classes.ts, packages/labs/analyzer/src/lib/model.ts, packages/labs/analyzer/src/lib/utils.ts, packages/labs/analyzer/src/test/lit-element/properties_test.ts, packages/labs/analyzer/test-files/js/properties/element-a.js, packages/labs/analyzer/test-files/ts/properties/src/element-a.ts
=> fix(analyzer): readonly fields

.changeset/silver-flies-agree.md, examples/preact/src/index.tsx, packages/labs/react/src/create-component.ts
Fixes #4138
Content placed in children position in JSX are typed differently depending on whether it's React or Preact project. Children typing in Preact projects were incompatible with `children` prop of our wrapped components as they only accepted `React.ReactNode` which was more restrictive than what Preact considers as valid renderable child.
This PR adds children typing that's compatible with both React and Preact.
~~Testing for this fix working in Preact was done manually in a working branch for https://github.com/lit/lit/pull/4111. I'd be okay with holding off on merging this until I can do the updates to that branch to demonstrate the fix.~~
Mentioned PR has been merged and this branch has been rebased to that.
=> [labs/react] Fix type compatibility with Preact when adding children

packages/labs/context/package.json
`build:ts` output needed to exclude `build:ts:std-decorators-tests` output.
Also took the opportunity to not copy test file types in `build:ts:types` as they're not needed.
=> [labs/context] Fix wireit config

.changeset/thin-apricots-help.md, package-lock.json, packages/labs/ssr/package.json, packages/labs/ssr/src/lib/util/parse5-utils.ts, packages/localize-tools/package.json, packages/localize-tools/src/program-analysis.ts
This just upgrades the parse5 dependency to 7.x which ships its own typescript types amongst various other improvements.
The SSR package has also been updated to import types from the parse5 root as the deep path isn't exported in parse5's `package.json`.
cc @augustjk
=> feat (localize-tools): upgrade parse5 to 7.x

.github/workflows/tests.yml, package-lock.json, package.json
Addressing feedback in https://github.com/google/wireit/pull/850 but I think this is an improvement as is
=> Update wireit, use the new quiet logger in CI testing

.changeset/swift-badgers-suffer.md, package-lock.json, packages/labs/compiler/package.json, packages/labs/ssr/package.json, packages/labs/ssr/src/lib/util/parse5-utils.ts, packages/localize-tools/package.json, packages/localize-tools/src/program-analysis.ts
Bumping `@parse5/tools` up so we can benefit from this easier import:
```ts
// new...
import {Element} from '@parse5/tools';
// previously...
import {DefaultTreeAdapterMap} from 'parse5';
type Element = DefaultTreeAdapterMap['element'];
```
FYI i chose to alias the names just for sake of readability, i.e. a knowing that we're referencing a parse5 `Element` rather than a DOM `Element`
=> chore (labs/compiler, labs/ssr, localize-tools): update parse5/tools

.changeset/sharp-pans-sip.md, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
Fixes #4012
This PR adds the template causing the problem as well as some additional information about why the error might be occurring.
=> fix(labs/ssr): Include template and doc reference in partIndex errors

.changeset/swift-badgers-suffer.md
During release (https://github.com/lit/lit/pull/4189), noticed that there was a compiler version bump. That isn't required yet for a private package.
This change means the compiler will not get version bumped.
Low risk change.
=> chore: remove private labs/compiler package from release notes

package-lock.json
After release we have a manual step to sync our package-lock.
`npm install` from root, and then generate this PR.
=> chore: sync package-lock post release

.changeset/wild-rats-wave.md, packages/labs/context/src/lib/decorators/provide.ts, packages/labs/context/src/test/decorators/provide_test.ts, packages/labs/context/src/test/provider-consumer_test.ts
It might feel like this is working at cross purposes to our standard decorators work, because those all require accessors, but I don't think so. With standard decorators we can use the type system to error out if they're used on a property instead of an accessor. With experimental decorators, they sorta work with properties, in that they do provide values and update them, but reading the value back off the field would always give undefined because we were defining it without a getter.
=> Support @provide with experimental decorators on a property

.changeset/nine-buttons-give.md, .eslintrc.json, package.json, packages/benchmarks/generator/src/index.ts, packages/benchmarks/generator/src/utils.ts, packages/labs/cli/src/lib/lit-cli.ts, packages/labs/context/src/lib/decorators/provide.ts, packages/labs/context/src/lib/value-notifier.ts, packages/labs/motion/src/animate-controller.ts, packages/labs/motion/src/animate.ts, packages/labs/observers/src/intersection-controller.ts, packages/labs/observers/src/mutation-controller.ts, packages/labs/observers/src/resize-controller.ts, packages/labs/react/src/create-component.ts, packages/labs/ssr-dom-shim/src/index.ts, packages/labs/ssr/src/lib/render-value.ts, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/layouts/flexWrap.ts, packages/labs/virtualizer/src/layouts/flow.ts, packages/labs/virtualizer/src/layouts/masonry.ts, packages/labs/virtualizer/src/layouts/shared/SizeCache.ts, packages/labs/virtualizer/src/test/scenarios/element-and-directive-parity.test.ts, packages/lit-html/src/directives/ref.ts, packages/lit-html/src/polyfill-support.ts, packages/lit-html/src/test/directives/test-async-iterable.ts, packages/lit-html/src/test/directives/until_test.ts, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts
These default to overbroad types like `any` and `object`.
Didn't change all tests, nor cases where we're assigning to an existing thing that has a type.
=> Put types on Map, Set, etc constructor calls

package-lock.json
Adds one line, the name of the new context package.
This PR was created by running `npm install`.
=> chore: sync package-lock

.changeset/yellow-waves-pay.md, packages/labs/react/src/create-component.ts
I have the following code to avoid repeating passing React on every `createComponent` call.
```ts
import * as React from 'react';
import { createComponent as createReactComponent } from '@lit-labs/react';
import type { EventName } from '@lit-labs/react';
type EventNames = Record<string, EventName | string>;
type Constructor<T> = new () => T;
export const createComponent = <
I extends HTMLElement,
E extends EventNames = {},
>(options: {
tagName: string;
elementClass: Constructor<I>;
events?: E;
displayName?: string;
}) => {
return createReactComponent<I, E>({ react: React, ...options });
};
```
I want to be able to
```ts
import * as React from 'react';
import { createComponent as createReactComponent } from '@lit-labs/react';
import type { EventName, Options } from '@lit-labs/react';
type …
```
=> feat(labs-react): export Options interface

packages/labs/motion/README.md
Thanks for creating lit motion! It's super helpful!!
When I read the documentation (README), I found the phrase "standard KeyframeAnimationOptions" confusing. The top Google search result is Apple's iOS UIKit developer guide.
Based on the [source code](https://github.com/lit/lit/blob/7175d11aa17abfda4adb75757abae1a6ee5b04ad/packages/labs/motion/src/animate.ts#L374C34-L374C50), I believe the parameter `keyframeOptions` is used as the KeyframeEffect Options to construct `animate()`.  Therefore, I slightly modify the README to point users to the API documentation.
=> Clarify keyframeOptions in motion

packages/labs/motion/README.md
I forgot to run prettier in #4234. This PR fixes the format of README file in labs/motion.
=> Format the README of labs/motion

.changeset/giant-games-drive.md, packages/labs/compiler/README.md
The compiler was released as part of the second pre release.
This is a documentation only change.
=> [lit-labs/compiler] update compiler README

package-lock.json, scripts/check-size.js
After second pre-release, need to sync package-lock as changeset doesn't do it for us.
Note: prior to this change, Node 20 install fails. I used Node 18 to update package-lock. Then verified that it works with Node 20.
=> [infra] sync 3.0 package-lock after second pre-release

packages/labs/react/package.json
The labs/react tests can fail due to missing dependency on the `@lit/react` builds that's necessary for imports to resolve.
This is a bit of a shotgun fix by adding wireit dependency on `packages/react:build` for all labs/react test scripts.
=> [infra] Add wireit build dep for labs/react test scripts

.changeset/hot-apricots-type.md, packages/labs/analyzer/src/lib/custom-elements/custom-elements.ts, packages/labs/analyzer/src/lib/lit-element/lit-element.ts
There are still some places where we use methods available on our imported `ts` rather than from the analyzer's reference (`analyzer.typescript`). This causes various problems with version mismatches and bundling.
These have now been updated to use the analyzer's typescript.
While doing this change, I noticed we generally follow two common signatures for our functions:
- `(node, analyzer)`
- `(ts, node)`
For the latter, it does make a sense from a purist point of view... type guards and what not which operate purely on a given AST node don't need the analyzer in theory, so they accept a typescript lib ref instead.
But it does mean we switch back and forth inconsistently sometimes between these signatures. maybe we want to _always_ pass an analyzer and just pull the typescript from that?
=> fix (labs/analyzer): use analyzer typescript instead of import

packages/lit-element/src/lit-element.ts, packages/reactive-element/src/reactive-element.ts, scripts/check-size.js
To get correct semantics out of it, we need to hide it from closure's instinct to collapse it by using dynamic property access syntax.
=> elementProperties is a static property that's dynamic similarly to finalized

.changeset/lemon-lamps-shave.md, packages/reactive-element/src/decorators/query.ts, packages/reactive-element/src/test/decorators-modern/query_test.ts
Fixes a user-reported issue on Discord where this kind of field produced an error:
```ts
@query('dt-dialog') private accessor dialogDce: DtDialog | undefined;
```
because `DtDialog | undefined` is not assignable to `Element`.
`@query()` can return `null`, not `undefined`, so this PR adds `null` to the field type and the error can be fixed by writing the field like:
```ts
@query('dt-dialog') private accessor dialogDce!: DtDialog | null;
```
Note that the non-null assertion `!` is necessary.
=> Allow @query() decorated fields to be null

.changeset/metal-cougars-brake.md, packages/labs/virtualizer/package.json
Virtualizer should work with both Lit 2 and Lit 3; update `package.json` to reflect this.
=> [labs/virtualizer] Update version range for lit

.changeset/fresh-jobs-admire.md, packages/labs/gen-wrapper-react/goldens/test-element-a/package.json, packages/labs/gen-wrapper-react/src/index.ts
Pre version was added before stable release to make self install tests pass. There's no reason to include this in generated output.
=> [labs/gen-wrapper-react] Don't include pre version of `@lit/react`

.changeset/thick-colts-smile.md, package-lock.json, packages/labs/motion/package.json, packages/labs/observers/package.json, packages/labs/preact-signals/package.json, packages/labs/router/package.json, packages/labs/scoped-registry-mixin/package.json, packages/localize-tools/package.json, packages/localize/package.json
Affected packages:
- '@lit-labs/scoped-registry-mixin': patch
- '@lit-labs/preact-signals': patch
- '@lit-labs/observers': patch
- '@lit/localize-tools': patch
- '@lit-labs/motion': patch
- '@lit-labs/router': patch
- '@lit/localize': patch
I haven't touched SSR and related packages yet as they'll require a more specific range of v2 to work.
I tested that these packages work with the lower version by manually installing `lit@2.0.0` or `@lit/reactive-element@1.0.0` within the package directory and running their tests.
=> Update dependency version range to accept Lit v2

.changeset/friendly-rabbits-arrive.md, .changeset/tender-snakes-marry.md, packages/labs/gen-wrapper-vue/package.json, packages/labs/nextjs/package.json, packages/labs/testing/package.json, packages/lit-element/package.json, packages/reactive-element/package.json
Affected packages:
- '@lit-labs/gen-wrapper-vue': patch
- '@lit/reactive-element': patch
- '@lit-labs/testing': patch
- '@lit-labs/nextjs': patch
- 'lit-element': patch
These packages still had -pre versions as production dependencies seemingly missed by changeset during release. Did them separately from https://github.com/lit/lit/pull/4300 as these would require a version bump so downstream users don't install the prerelease versions.
`@lit-labs/testing` was also missed from https://github.com/lit/lit/pull/4299 in upping the version range.
=> Fix dependencies to use stable instead of pre-release vesrions

.changeset/olive-otters-vanish.md, packages/labs/ssr-client/src/lib/hydrate-lit-html.ts
Fixes https://github.com/lit/lit/issues/4289
While swc did fix this upstream it's not released yet and I don't know how long it takes for that to make it into Next.js's version of swc.
It seems like a tiny lift for us to add this to make it work now.
=> [labs/ssr-client] Avoid nullish logical assignment in hydrate-lit-html

.changeset/eighty-jars-help.md, packages/labs/eleventy-plugin-lit/src/index.ts, packages/labs/ssr/src/lib/module-loader.ts, packages/labs/ssr/src/test/lib/module-loader_test.ts, packages/labs/ssr/src/test/test-files/module-loader/lit-import-from-root.js, packages/labs/ssr/src/test/test-files/module-loader/lit-import.js
Fixes: https://github.com/lit/lit/issues/2549
When the eleventy ssr plugin loads modules concurrently, it would previously fail with an error. Something like:
```
Error: request for '@lit/reactive-element' is not yet fulfilled
at SourceTextModule.link (node:internal/vm/module:198:17)
at ModuleLoader.importModule (/home/aomarks/work/wireit-lit/packages/labs/ssr/src/lib/module-loader.ts:107:7)
at async Promise.all (index 1)
```
Investigating this issue I found:
- Specification of the module methods: https://tc39.es/ecma262/#table-abstract-methods-of-module-records
- Located the error message in the node codebase: https://github.com/nodejs/node/blob/eed33c9deaa336e76c5385a077490107c6110f08/src/module_wrap.cc#L532-L535
Solution is to closer match the spec. `LoadRequestedModules` should …
=> [labs/ssr] fix ModuleLoader failing with multiple concurrent entrypoints

.changeset/clever-jobs-float.md, .changeset/silver-pears-poke.md, package-lock.json, packages/labs/eleventy-plugin-lit/package.json, packages/labs/ssr-client/package.json, packages/labs/ssr-react/package.json, packages/labs/ssr/package.json
Last of the dependency version changes!
Affected packages:
- '@lit-labs/eleventy-plugin-lit': patch
- '@lit-labs/ssr': patch
- '@lit-labs/ssr-client': patch
Minimum versions used:
- [`lit-html`@2.7.0](https://github.com/lit/lit/blob/main/packages/lit-html/CHANGELOG.md#270): Includes https://github.com/lit/lit/pull/3667
- [`lit-element`@3.3.0](https://github.com/lit/lit/blob/main/packages/lit-element/CHANGELOG.md#330): Includes https://github.com/lit/lit/pull/3677, specifically reflected ARIA attribute removal on hydration.
- [`@lit/reactive-element@1.6.1`](https://github.com/lit/lit/blob/main/packages/reactive-element/CHANGELOG.md#161): Includes https://github.com/lit/lit/pull/3561 with auto-shimming Node build
- [`lit@2.7.0`](https://github.com/lit/lit/blob/main/packages/lit/CHANGELOG.md# …
=> Update dependency versions for labs/ssr and related packages

.changeset/chilly-geckos-occur.md, package-lock.json, packages/context/package.json, packages/context/src/lib/controllers/context-consumer.ts, packages/context/src/lib/controllers/context-provider.ts
We had both `lit` and `@lit/reactive-element` listed as dependency but really all we need for the implementation is `@lit/reactive-element` for the types. This would be a good candidate to consider making it a peer dependency as well.
`lit` is moved to dev dependency as it is used for testing.
=> [context] Only depend on `@lit/reactive-element`

.changeset/healthy-dingos-pay.md, package-lock.json, packages/localize/package.json, packages/localize/src/internal/localized-decorator.ts
This alleviates type errors when there's a different version of `reactive-element` that `@lit/localize` is using versus what the user's component is using.
Because `localized` is a class decorator, the standard `Interface` with `Omit` or `Pick` was not usable as there were static properties on it that conflict. I tried `Pick<typeof ReactiveElement, 'addInitializer'>` but the initializer type references `ReactiveElement` directly which breaks because of `renderRoot`.
I also removed the dependency on `@lit/reactive-element` and just import everything from `lit`.
I do wonder though.. `@lit/localize` only uses the `lit` package for types/interfaces. It exports utilities strictly meant to be used with `lit` projects and nothing is standalone. This is a prime candidate for marking `lit` as a …
=> [localize] Loosen type of `@localized()` decorator

.changeset/kind-insects-shake.md, packages/lit-html/src/directives/when.ts
Improve typing for the `when` directive making it more dynamic.
```ts
let user = {name: string} | undefined;
when(
user,
(user) => user.name
)
```
In the trueCase and falseCase functions the condition is correctly type
and we no longer need a non-null assertion.
Fixes #4085
=> feat(lit-html/directives/when.ts): improve typing

.github/workflows/tests.yml
I've been seeing a lot of windows-tools workflow failures like https://github.com/lit/lit/actions/runs/6660895512/job/18102830296
Possibly related issues:
https://github.com/npm/cli/issues/6763
https://github.com/orgs/nodejs/discussions/49784
There's a potential fix https://github.com/nodejs/node/pull/50136 that hasn't made it to latest node 20 that github actions is getting.
So I'm just trying to downgrade to 18 see if it'll help.
=> [infra] Use Node 18 for windows-tools test

.changeset/violet-bugs-return.md, packages/react/src/create-component.ts
I noticed in the case of providing a stable `ref` callback to a wrapped React component, it was invoking it on every render. This is because the internal `ref` is set to an unstable function, with a new reference on every render. This was particularly problematic when using a callback to do some kind of setup/cleanup loop based on connecting/disconnecting to the DOM.
To my knowledge, both React and Lit's `ref` callback functionality is to ensure this only happens on connect/disconnect, or if the reference changes.
E.g.
```ts
const MyComponent = () => {
// Stable ref callback
const onNode = useCallback((node: HTMLElement | null) => {
console.log(node);
if (node) {
// Element is mounted, do some setup
} else {
// Element is unmounted, do some cleanup
}
}, []);
return (
<LitReactComponent …
```
=> Lit/React – Wraps `ref` in a stable callback

.changeset/late-books-draw.md, examples/nextjs/package.json, examples/preact/package.json, packages/labs/context/package.json, packages/labs/react/package.json
Our original intention was to have the labs packages automatically track the first major version of the graduated package so it'll automatically receive updates. This got erroneously pinned to the exact version for initial release as we were moving/exiting pre-release mode.
I also took this opportunity to add `^` dependencies in examples/ projects so they don't get a version bump every release.
=> [context, react] Update dependency on graduated package to `^1.0.0`

.changeset/six-planets-notice.md, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Fixes https://github.com/lit/lit/issues/4332
Given:
```
import { html, render } from 'lit'; // This should be the html imported from 'lit/static-html.js'
import { unsafeStatic } from 'lit/static-html.js';
// Does not throw warning/error, and renders `attribute="[object Object]"`
render(html`<h1 attribute="${unsafeStatic('test')}">test</h1>`, document.body);
```
The example ends up rendering attribute="[object Object]", when it should throw a dev mode warning.
Check that values do not have `_$litStatic$` and raise a dev mode warning if the key is present.
New warning is:
```
Static values 'literal' or 'unsafeStatic' cannot be used as values to non-static templates.
Please use the static 'html' template. See https://lit.dev/docs/templates/expressions/#static-expressions
```
=> [lit-html] Add dev mode warning when static values are detected in non static templates

.changeset/fair-fishes-tell.md, packages/labs/compiler/src/lib/template-transform.ts, packages/labs/compiler/test_files/part_element.golden.js, packages/labs/compiler/test_files/part_element.ts, packages/tests/package.json, packages/tests/src/web-test-runner.config.ts
This PR fixes two issues.
1. The compiled lit_html tests were not running on CI. I only discovered the error via local testing.
2. Element parts were not being handled accurately.
Element parts were being ordered by `realName`, which would prioritize ordering attribute parts first, followed by element parts.
This is also not aligned with how lit-html detects the parts.
Fix is to look at attribute names to detect element vs attribute parts!
Test with golden test and lit_html tests locally.
Then also added the compiled lit_html tests to test config so now it should run in CI.
=> [labs/compiler] Fix elementParts being compiled as attributeParts

.changeset/proud-bulldogs-sin.md, packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/directive-helpers_test.ts, packages/lit-starter-ts/src/test/my-element_test.ts
Adds two new types: `UncompiledTemplateResult` and `MaybeCompiledTemplateResult`. Currently `UncompiledTemplateResult` is the same as `TemplateResult`, and `MaybeCompiledTemplateResult` is the union of the compiled and uncompiled types.
We'd like for code to be able to handle the `html` and `svg` functions returning a MaybeCompiledTemplateResult. Changing that type will be a major breaking change though, and we don't want to do a major version so quickly, but this lays the ground work, and provides future-compatible types that people can use when they want to be explicit about which type they mean, because while TemplateResult will change, MaybeCompiled, Uncompiled, and Compiled will all have the same meanings in the next major version.
=> Improve types for (un)compiled template results

.github/workflows/benchmarks.yml, .github/workflows/sizecheck-report.yaml, .github/workflows/sizecheck.yaml
Fixes https://github.com/lit/lit/issues/4288
I followed a similar pattern as the benchmarks report workflow added here https://github.com/lit/lit/pull/4041
Workflows running on forks can't use actions that write comments on the PR. This moves the size check to its own workflow, and a separate workflow that triggers on the completion of that size check is responsible for writing the comment.
The original size check wrote a markdown file on failure for the comment message so that is added as an artifact, similar to how benchmark results are done.
We won't see this work on this PR as workflows that are triggered by other workflows only run off of a protected main branch for security as these workflows have elevated access. It'll show up for PRs after this is merged to main.
=> [infra] Split out size check workflow from benchmarks

.github/workflows/sizecheck-report.yaml, .github/workflows/sizecheck.yaml
I made an incorrect assumption in https://github.com/lit/lit/pull/4323
The action used for create comments https://github.com/thollander/actions-comment-pull-request does not work from a `workflow_run` triggered action as it can't pull the PR to comment on from the context of the workflow.
This is apparently not straight forward to do purely within GitHub actions.
https://github.com/orgs/community/discussions/45415
https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow
Even GHA's own doc shows using an artifact to pass the PR number to another workflow: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
I cobbled together a solution from digging through above example …
=> [infra] Fix sizecheck actions to save PR number for report

.changeset/brave-moles-check.md, examples/nextjs/src/count-display.ts, examples/nextjs/src/simple-greeter.ts, packages/labs/ssr-react/src/lib/node/render-custom-element.ts, packages/labs/ssr-react/src/test/child-element.ts, packages/labs/ssr-react/src/test/integration/enable-lit-ssr_test.tsx, packages/labs/ssr-react/src/test/integration/runtime-jsx_test.tsx, packages/labs/ssr-react/src/test/parent-element.ts
Fixes https://github.com/lit/lit/issues/4363
I also kept the changes I made to the `nextjs` example to reproduce the error.. It might not be really necessary but also doesn't hurt to keep it around.
Testing for this looks specifically for `defer-hydration` attribute on SSRed string on a child custom element that is rendered by a parent custom element.
The test we had formerly called "nested element" actually tests that a custom element that is  React child in the provided JSX renders properly so I've renamed to "custom element child" instead.
=> [labs/ssr-react] Fix hydration ordering for nested custom elements

.changeset/proud-bulldogs-sin.md
We should add `lit` package as well when bumping `lit-html`.
=> [chore] Update changeset for template result type change

.changeset/tasty-sloths-pump.md, packages/labs/ssr/src/lib/render-result-readable.ts, packages/labs/ssr/src/test/lib/render-result-readable_test.ts
Fix a race condition bug with RenderResultReadable.
The `RenderResultReadable` class lets us efficiently stream synchronous or async iterables. It's architecture is [designed to be as optimal as possible](https://github.com/lit/lit/pull/3467#issuecomment-1319448671), so synchronous streams go fast and have minimal overhead from the async handling.
Our `RenderResultReadable.prototype._read` implementation is async, allowing us to `await` values in the stream.
From [Node.js documentation](https://nodejs.org/api/stream.html#readable_readsize): "`_read()` will be called again after each call to [`this.push(dataChunk)`](https://nodejs.org/api/stream.html#readablepushchunk-encoding) once the stream is ready to accept more data."
This is also the behavior back to [Node.js …
=> [labs/ssr] fix: RenderResultReadable skipping async work

.changeset/pink-maps-exercise.md, .changeset/slow-singers-compare.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element_test.ts, scripts/check-size.js
Fixes #4268. Ensures `renderRoot` exists before first update. It's created upon first connection by default (so that it exists before controllers' `hostConntected`), but this change supports early calls to `performUpdate`/`enableUpdating` without
depending on connection.
=> Ensure renderRoot exists before first update

.changeset/healthy-elephants-itch.md, .changeset/strong-ants-think.md, packages/reactive-element/src/reactive-element.ts, packages/reactive-element/src/test/reactive-element-controllers_test.ts, scripts/check-size.js
Fixes https://github.com/lit/lit/issues/4266. Controllers are maintained via a Set instead of an Arry, allowing them to be iterated stably while being modified.
=> Controllers can be added/removed during lifecycle.

.changeset/brave-frogs-tan.md, packages/lit-html/src/directives/async-replace.ts, packages/lit-html/src/test/directives/async-replace_test.ts
=> async-replace correctly re-renders when value is unchanged

.changeset/odd-buckets-attend.md, packages/reactive-element/src/reactive-element.ts, scripts/check-size.js
I noticed this while re-reading some of the code. This was for distinguishing initial values while we were still trying to not reflect initial values for standard decorators.
=> Remove unused internal parameters to requestUpdate

.changeset/lazy-beans-tap.md, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
Fixes: https://github.com/lit/lit/issues/4417
Server templates reuse a lot of the code paths of non server templates. In the server we convert templates to an HTML ast with parse5's `parseFragment` function.
However, this results in the following:
```html
<script type="module">
import {parseFragment, serialize} from 'https://cdn.jsdelivr.net/npm/parse5@7.1.2/+esm';
console.log(serialize(parseFragment("<html lang='ko'><p>Content</p></html>")));
// → <p>Content</p>
</script>
```
The attribute part thus cannot be added, and a part mismatch error is thrown.
For server templates, use parse5's `parse` function. This handles document tags such as `html`. In fact it puts everything in a document.
```html
<script type="module">
import {parse, serialize} from …
```
=> [labs/ssr] allow binding attributes to html tag when using server templates

.changeset/shaggy-phones-behave.md, packages/labs/gen-manifest/goldens/test-element-a/custom-elements.json, packages/labs/gen-wrapper-angular/goldens/test-element-a/.gitignore, packages/labs/gen-wrapper-angular/goldens/test-element-a/package.json, packages/labs/gen-wrapper-angular/goldens/test-element-a/src/element-a.ts, packages/labs/gen-wrapper-angular/goldens/test-element-a/src/element-events.ts, packages/labs/gen-wrapper-angular/goldens/test-element-a/src/element-props.ts, packages/labs/gen-wrapper-angular/goldens/test-element-a/src/element-slots.ts, packages/labs/gen-wrapper-angular/goldens/test-element-a/src/element-without-props.ts, packages/labs/gen-wrapper-angular/goldens/test-element-a/src/sub/element-sub.ts, packages/labs/gen-wrapper-angular/src/lib/wrapper-module-template.ts, packages/labs/gen-wrapper-react/goldens/test-element-a/.gitignore, packages/labs/gen-wrapper-react/goldens/test-element-a/package.json, packages/labs/gen-wrapper-react/goldens/test-element-a/src/element-without-props.ts, packages/labs/gen-wrapper-vue/goldens/test-element-a/.gitignore, packages/labs/gen-wrapper-vue/goldens/test-element-a/package.json, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementA.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementEvents.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementProps.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementSlots.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementWithoutProps.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/sub/ElementSub.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/vite.config.ts, packages/labs/gen-wrapper-vue/src/lib/wrapper-module-template-sfc.ts, packages/labs/test-projects/test-element-a/src/element-without-props.ts
For each of the wrapper generators, this adds support for elements with no reactive props.
For example:
```ts
class Foo extends LitElement {
render() {
return html`no props!`;
}
}
```
We basically conditionally output the code any reactive property related logic depends on, rather than always outputting it.
When generating vue wrappers, we produce two relevant things:
- a `Props` interface (**empty when no properties exist**)
- a `vDefaults.created` function for setting the defaults of these props
If no props exist, we end up with an empty interface (`{}`), which means `keyof Props` is now `never`, leading to various type problems in `vDefaults.created` (which tries to key into props).
For example:
```ts
interface Props {}
const vueProps = defineProps<Props>();
const defaults = …
```
=> feat(labs): support elements with no reactive props

.changeset/ninety-bananas-sneeze.md, packages/reactive-element/src/reactive-element.ts
This is an uncommon use case to do in real code, but a reasonable thing to try when experimenting and debugging, so we want to help someone out with a warning here.
=> Add a warning when binding this.requestUpdate to an event listener

.changeset/sharp-suns-sing.md, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/test/integration/tests/basic.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
Fixes https://github.com/lit/lit/issues/4478
The attribute index for accessing the generated case sensitive name was erroneously being incremented on element part bindings, causing a shift of attribute names.
=> [labs/ssr] Fix attribute part bindings following element part binding

.changeset/proud-rocks-tap.md, packages/labs/preact-signals/src/lib/signal-watcher.ts, packages/labs/preact-signals/src/test/signal-watcher_test.ts
Fixes: https://github.com/lit/lit/issues/4486
For context see the issue. It is now possible to pass an abstract class to the mixin and have it type check.
Added type and runtime unit tests to ensure that both concrete and abstract classes are watched correctly.
=> [lit-labs/preact-signals] add abstract class support to SignalWatcher

.changeset/funny-files-tease.md, package-lock.json, package.json, packages/internal-scripts/bin/add-browser-exports.js, packages/internal-scripts/package.json, packages/internal-scripts/src/add-browser-exports.ts, packages/labs/react/package.json, packages/labs/ssr-client/package.json, packages/lit-html/package.json, packages/react/package.json, packages/reactive-element/package.json
Fixes: https://github.com/lit/lit/issues/4446
This is a compromise so that testing in Vitest works. As part of this work I explored simplifying the package.json exports using subpath patterns. Unfortunately the [ecosystem doesn't support those very well, so it's been punted](https://github.com/lit/lit/pull/4483).
- First commit contains the script.
- Second commit contains the result of running the script.
Marked this a patch change, as it's a minor "bug fix" workaround for testing in Jest and Vitest.
This script has two modes:
- `test`: won't write any files, but instead checks that no files need to be fixed. Is run as part of our CI.
- `fix`: writes to package.json files.
The prior browser/node entrypoints are tested via our CI.
The script itself is lightly tested via node assertions. …
=> [infra] Add browser export conditions to package.json

.changeset/cold-windows-pretend.md, packages/labs/motion/src/animate.ts
The animate controller should be compatible with any component implementing `ReactiveControllerHost` not only LitElement, see #2197
=> Remove reference to LitElement in lit-labs/motion

.changeset/fresh-fishes-do.md, .eslintignore, .prettierignore, package.json, packages/labs/ssr-dom-shim/.gitignore, packages/labs/ssr-dom-shim/package.json, packages/labs/ssr-dom-shim/src/index.ts, packages/labs/ssr-dom-shim/src/test/element-shim_test.ts
Fixes: https://github.com/lit/lit/issues/4468
This adds [`Element.prototype.toggleAttribute(name, force?)`](https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute) to the SSR ElementShim.
Unit tested in the node environment using `uvu`. Note, the package originally didn't have unit tests, so I've also set up a new `test` rule.
Documenting this as I was going to implement lower-casing of attribute names until I spoke with Augustine.
Ignoring casing is by design in the shim because these shimmed APIs can be used on SVG elements where casing is preserved. I believe the justification is we preserve casing during SSR, and then the browser will lowercase the attributes if in the HTML namespace. E.g. if we SSR `<div cLaSs="example">`, it'll be parsed into `<div …
=> [lit-labs/ssr-dom-shim] shim Element.prototype.toggleAttribute method

.changeset/mean-cars-appear.md, packages/localize-tools/src/formatters/xlb.ts, packages/localize-tools/src/formatters/xliff.ts, packages/localize-tools/testdata/extract-xliff-merge/goldens/foo.ts, packages/localize-tools/testdata/extract-xliff-merge/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/extract-xliff-merge/input/foo.ts, packages/localize-tools/testdata/extract-xliff-merge/input/xliff/es-419.xlf
Fixes https://github.com/lit/lit/issues/4490
Instead of creating a new placeholder index on write which will always be in the order seen, we should use the existing index for untranslatables which could be out of order if they're read from an already translated target.
=> [localize-tools] Preserve existing placeholder id/index on extract

README.md
We had some stale wording and references to the previous major version.
I also added a link to the dev-docs directory, and some missing labs packages, but did not include cli, analyzer, or gen-wrapper-* as they feel more experimental at the moment.
=> [chore] Update monorepo README

.changeset/serious-books-flow.md, packages/labs/motion/src/animate.ts
`ancestorProps` is an array there, so it's always not equal `undefiend`. There should validate its `length`
=> [labs/motion] chore: improve adjustments of ancestor condition check

.changeset/forty-schools-flash.md, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/lit-html_test.ts
Fixes: https://github.com/lit/lit/issues/4194
A lot of the context is in the issue, but in short, if an attribute binding is duplicated, such as in the following example:
```html
<textarea 
?disabled=${this.disabled} 
?disabled=${this.disabled} 
placeholder=${this.placeholder}
></textarea>
```
The result is that Lit parts get out of sync with the values (because attributes are de-duped by the browser).
I've implemented this as a DEV_MODE error, but I'm open to making it a DEV_MODE warning.
The following template: `<input ?disabled=${true} ?disabled=${false}>`, will throw:
```
Detected duplicate attribute bindings of attribute: '?disabled', in the template: `<input ?disabled=${...} ?disabled=${...}>`
```
=> [lit-html] Add DEV_MODE error if duplicate attribute bindings are encountered

.changeset/config.json, .changeset/long-points-deliver.md, packages/labs/ssr/src/lib/render-value.ts, packages/lit-html/src/private-ssr-support.ts
A memory leak was reported in Lit SSR.
Found by testing with https://github.com/lit/lit/pull/4514, and going test by test.
- The `repeat` directive test contained this leak. After this PR the directive test no longer leaks.
So far no other test shows memory leak characteristics.
Because we have a cache of `WeakMap<non patched directive, patched directive>`. This is an issue because we can pull a patched directive off the `value`, and then it won't be found in the WeakMap. Because it's in the value of the WeakMap and not the `key`. Thus the patched directive gets patched again and stored in the WeakMap. This repeats for the number of patch calls resulting in a nested doll of patched directive constructors.
~~I implemented a super simple naive fix. Just flag the patched directive ctor with …
=> [labs/ssr] fix patched directives memory leak

.changeset/mighty-cars-confess.md, packages/localize-tools/src/messages.ts, packages/localize-tools/src/tests/e2e/placeholder-errors.test.ts, packages/localize-tools/testdata/build-runtime-xliff-ph/goldens/foo.ts, packages/localize-tools/testdata/build-runtime-xliff-ph/goldens/tsout/es-419.ts, packages/localize-tools/testdata/build-runtime-xliff-ph/goldens/tsout/zh_CN.ts, packages/localize-tools/testdata/build-runtime-xliff-ph/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/build-runtime-xliff-ph/input/foo.ts, packages/localize-tools/testdata/build-runtime-xliff-ph/input/xliff/es-419.xlf, packages/localize-tools/testdata/build-runtime-xliff/goldens/foo.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/es-419.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/tsout/zh_CN.ts, packages/localize-tools/testdata/build-runtime-xliff/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/build-runtime-xliff/goldens/xliff/zh_CN.xlf, packages/localize-tools/testdata/build-runtime-xliff/input/foo.ts, packages/localize-tools/testdata/build-runtime-xliff/input/xliff/es-419.xlf, packages/localize-tools/testdata/build-runtime-xliff/input/xliff/zh_CN.xlf, packages/localize-tools/testdata/build-transform-xliff/goldens/foo.ts, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/en/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/es-419/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/tsout/zh_CN/foo.js, packages/localize-tools/testdata/build-transform-xliff/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/build-transform-xliff/input/foo.ts, packages/localize-tools/testdata/build-transform-xliff/input/xliff/es-419.xlf, packages/localize-tools/testdata/placeholder-errors/goldens/foo.ts, packages/localize-tools/testdata/placeholder-errors/goldens/xliff/es-419.xlf, packages/localize-tools/testdata/placeholder-errors/input/foo.ts, packages/localize-tools/testdata/placeholder-errors/input/xliff/es-419.xlf
Fixes https://github.com/lit/lit/issues/4502
In the past, the expressions in the translated message placeholder were directly used in generating the output code in transform mode.
```js
msg(str`Hello ${user}!`);
```
```xml
<trans-unit id="s00ad08ebae1e0f74">
<source>Hello <x id="0" equiv-text="${user}"/>!</source>
<target>Hola <x id="0" equiv-text="${user}"/>!</target>
</trans-unit>
```
used the actual `equiv-text="${user}"` value from `<target>` to generate
```js
`Hello ${user}!`;
```
This meant it was possible for faulty or malicious JS expression to be injected to the output if translation placeholders were modified.
```xml
<trans-unit id="s00ad08ebae1e0f74">
<source>Hello <x id="0" equiv-text="${user}"/>!</source>
<target>Hola <x id="0" equiv-text="${alert('evil') || …
```
=> [localize] Make placeholder validation pass with different expressions

.changeset/nice-steaks-hope.md, packages/labs/analyzer/package.json, packages/labs/analyzer/src/lib/lit-html/template.ts, packages/labs/analyzer/src/test/server/lit-html/template_test.ts, packages/labs/analyzer/src/test/server/utils.ts, packages/labs/compiler/package.json, packages/labs/compiler/src/lib/type-checker.ts
Builds on https://github.com/lit/lit/pull/4260 (for use in tests)
This moves the `isLitTaggedTemplateExpression` template utility from the compiler to the analyzer. The analyzer will need these same utilities to detect lit-html template expressions for template analysis.
=> [labs/analyzer] Add template utils to analyzer and use them in the compiler

.changeset/strange-peas-design.md, package.json, packages/react/src/create-component.ts, packages/react/src/test/create-component_test.tsx
Fixes https://github.com/lit/lit/issues/4497
Also related https://github.com/lit/lit/issues/4227
We now collect previous element props in a map and actually check off ones that we update. We then go through any remaining and set them all as `undefined`.
It could be considered a bugfix, or it could even be considered breaking. Or a new "feature" of handling unset properties?
`undefined` feels most correct in terms of semantics of "unsetting", but I wanted to see what React's future custom element support would do and it seems `react-dom@experimental` will actually set the property as `null` if it's missing.
Playground: https://lit.dev/playground/#gist=001005b1cfb39fd03ccb37e841d256e5
(The current value of the property is logged in the console)
We'll include this in a patch release as the …
=> [react] "Unset" missing properties

.changeset/fifty-rats-brush.md, packages/labs/testing/src/lib/fixtures/ssr-fixture.ts
Fixes https://github.com/lit/lit/issues/4539
Confirmed this works by running test with latest webkit which has DSD and `setHTMLUnsafe` support.
=> [labs/testing] Fix DSD feature detection and use setHTMLUnsafe for parsing

.changeset/fluffy-garlics-smash.md, packages/context/src/lib/context-request-event.ts, packages/context/src/test/protocol-types-test.ts, packages/context/src/test/protocol-types.ts
Fixes https://github.com/lit/lit/issues/4609
=> Fix context types to be compatible with WCCG context protocol types.

.changeset/violet-phones-look.md, packages/lit-html/src/directives/ref.ts, packages/lit-html/src/test/directives/ref_test.ts
=> Ensure ref value is always undefined when disconnected

.changeset/thirty-shirts-peel.md, packages/context/src/lib/decorators/consume.ts, packages/context/src/lib/decorators/provide.ts
`target.set` is the correct way to set values in decorators. It supports nested decorators and private fields.
=> [lit/context] Use `target.set` for setting context values

.changeset/lovely-suits-rescue.md, packages/labs/ssr-dom-shim/src/index.ts, packages/labs/ssr-dom-shim/src/test/element-shim_test.ts
This change extends the CustomElementRegistryShim to patch localName and tagName into the web component, when calling define.
This allows instances to call `this.localName` and `this.tagName` accordingly.
Fixes #3375
=> [labs/ssr-dom-shim] Patch localName and tagName with customElements.define call

.changeset/chilly-melons-laugh.md, packages/localize/src/init/install.ts, packages/localize/src/init/reentrant.ts, packages/localize/src/init/runtime.ts, packages/localize/src/init/transform.ts, packages/localize/src/lit-localize.ts
Localize has an import loop because submodules are importing from their root. To resolve the loop, `msg`, `installed` and `_installMsgImplementation` are moved to a new submodule.
Imports to `msg` remain intact, through an explicit export.
=> [localize] Move setup code to own file to resolve import loop

packages/lit-element/src/lit-element.ts, packages/lit-html/src/directive.ts, packages/lit-html/src/directives/class-map.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/static.ts, packages/reactive-element/src/reactive-element.ts
I read though the entire source code of the main `lit*` packages and detected a few minor typos
=> chore: correct typos

.changeset/pretty-papayas-begin.md, packages/context/README.md
Spotted a typo when copy/pasting a code example.
=> Fix syntax typo in code example in the Context README

.changeset/rude-cherries-cover.md, packages/labs/testing/src/lib/fixtures/csr-fixture.ts, packages/labs/testing/src/lib/fixtures/ssr-fixture.ts, packages/labs/testing/src/test/good-element_test.ts
The fixtures currently look for the wtr-session-id query string. This PR adds a fallback, when wtr-session-id is not found, to look for the first URL that does not contain node_modules or the path to the fixture file.
Fixes #4067
=> [labs/testing] Add fallback for call site location detection for webkit

.changeset/chilled-lizards-remain.md, package-lock.json, packages/labs/rollup-plugin-minify-html-literals/package.json, packages/labs/rollup-plugin-minify-html-literals/src/lib/minify-html-literals.ts
Updates various dependencies to the latest version, including rollup to 4.x.
=> chore(labs/rollup-plugin-minify-html-literals): update dependencies

.changeset/tall-dodos-double.md, packages/labs/analyzer/src/lib/javascript/classes.ts, packages/labs/analyzer/src/lib/lit-element/properties.ts, packages/labs/analyzer/test-files/ts/properties/src/element-a.ts
Fixes https://github.com/lit/lit/issues/4745
This change allows private fields to be handled, but because they're not likely to be reactive properties, they're effectively ignored in this code path.
=> [labs/analyzer] Handle class private fields in LitElement analysis

.changeset/fluffy-peaches-appear.md, packages/react/src/create-component.ts
Currently in dev mode of the `@lit/react` package, reserved React properties are checked against the prototype of the given custom elements class. This used to work during SSR, as none of reserved keywords were implemented in the HTMLElement shim.
Now with #4553 `localName` is implemented in the shim, which is one of the reserved keywords, which causes `HTMLElement.prototype` to be evaluated in the code path and crashes during SSR.
This PR removes this check during SSR. Injecting the shim for the `node` exports was considered, but dismissed, as there is a potential difference between properties of the shim and the native Browser HTMLElement instance.
=> [react] Prevent calling HTMLElement.prototype in SSR

.changeset/honest-ties-mix.md, packages/labs/virtualizer/src/Virtualizer.ts, packages/labs/virtualizer/src/test/scenarios/hidden.test.ts, playground/p/issues/4672/_import.info.json, playground/p/issues/4672/index.html, playground/p/issues/4672/package.json, playground/p/issues/4672/simple-list.ts
Fixes #4672.
The math for calculating the portion of a Virtualizer that's currently visible can result in negative dimensions if a hidden Virtualizer has clipping ancestors, and our layout logic doesn't guard against negative dimensions.
After exploring a specific fix that would have specifically tried to detect the observed problem case, I opted to simply constrain the calculated dimensions to be >= 0. There's a chance that this approach will make it somewhat harder to debug some future issue, but I think the simplicity of the fix and its conceptual soundness (there are no circumstances in which negative dimensions make sense) make it a good, pragmatic choice.
Reviewers: to observe the bug, check out the second-to-last commit in detached HEAD state and run the automated tests and/or the …
=> [labs/virtualizer] Fix case where items in a hidden Virtualizer were being rendered

.changeset/smooth-deers-wave.md, packages/labs/testing/src/lib/fixtures/csr-fixture.ts, packages/labs/testing/src/lib/fixtures/ssr-fixture.ts
Currently when running browsers in a container (e.g. playwright), the resolution to localhost will fail.
This PR adds `host.containers.internal`, additionally to `localhost`, to the base resolution regex.
`host.containers.internal` is available per default in [Podman](https://podman.io/) and can easily be added to Docker (`docker run --add-host=host.containers.internal=host-gateway ...`).
=> [labs/testing] Fix fixture base url resolution when running browsers in containers

.changeset/cold-bees-doubt.md, packages/labs/nextjs/src/index.ts
Currently the nextjs config wrapper type mistakenly indicates it returns a NextConfig object. It however returns a callback, which receives and returns a NextConfig object.
=> [labs/nextjs] Fix type of nextjs config wrapper

.changeset/wicked-rules-repeat.md, package-lock.json, package.json, packages/labs/testing/README.md, packages/labs/testing/src/lib/lit-ssr-plugin.ts, packages/labs/testing/src/lib/worker.ts, packages/labs/testing/src/test/init-script-hooks.ts, packages/labs/testing/src/test/init-script.ts, packages/labs/testing/src/test/init-script_test.ts, packages/labs/testing/src/web-test-runner-ssr-plugin.ts, packages/labs/testing/tsconfig.json, packages/labs/testing/web-test-runner.config.js
This PR adds an option to the `litSsrPlugin` to allow defining worker init modules, which are sequentially imported at the start of the SSR worker. This allows registering Node.js hooks (https://nodejs.org/api/module.html#customization-hooks) or general setup.
=> [labs/testing] Add option for init script for ssr worker to allow registering Node.js hooks

.changeset/rare-cherries-bake.md, .changeset/tidy-badgers-drop.md, package-lock.json, packages/labs/ssr-react/package.json, packages/react/package.json
This allows using @lit/react with React 19
For #4857
=> fix: Widen range for React types to include React 19

.changeset/metal-tigers-visit.md, packages/labs/eleventy-plugin-lit/src/index.ts
Pretty conclusive that there is a hefty RegExp performance cost in the Eleventy Lit plugin, in the `trimOuterMarkers` function here: https://github.com/lit/lit/blob/267d243aeec13a6f0e8184420919db4c519b8caf/packages/labs/eleventy-plugin-lit/src/index.ts#L241-L245
Example Node CPU profile here (about 75% of this Eleventy project’s build is spent here):
The regular expressions seem to suggest that markers we’re looking for here are only found at the beginning and end of the content strings so I made some improvements using those assumptions.
Build time dropped significantly with the proposed changes (`20s` -> `~5s`)
cc @KonnorRogers @claviska
=> Improve performance on trimOuterMarkers in Eleventy Lit plugin

.changeset/clever-bobcats-clap.md, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementA.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementEvents.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementMixins.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementProps.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementSlots.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/ElementWithoutProps.vue, packages/labs/gen-wrapper-vue/goldens/test-element-a/src/sub/ElementSub.vue, packages/labs/gen-wrapper-vue/src/lib/wrapper-module-template-sfc.ts
This fixes test failures that started happening recently. https://github.com/lit/lit/actions/runs/12586758426/job/35081270464#step:7:67
I suspect some default tsconfig was changed in the the latest `vue-tsc` minor update that started causing this as we do not have a lockfile for the generated test package.
=> [labs/gen-wrapper-vue] Fix type errors for generated components

.changeset/soft-queens-complain.md, packages/labs/virtualizer/src/support/resize-observer-errors.ts
Virtualizer provides some helpers for ignoring errors during testing. We use these to prevent certain benign `ResizeObserver` errors from causing our tests to fail; we also export them for customers to use in their own tests as needed.
Currently, ignored errors are still logged to the console, however, which can result in noisy test output. By request, this PR adds an option to suppress logging if desired.
=> [labs/virtualizer] Optionally suppress logging of ignored errors

.changeset/rude-pillows-mate.md, packages/labs/ssr/src/lib/render-value.ts
This change mitigates potential memory leaks resulting from server-only templates that improperly use `unsafe`. A similar change was made for Lit HTML itself in https://github.com/lit/lit/pull/1647 to fix https://github.com/lit/lit/issues/1646.
The following code snippet is a minimal reproduction of a memory leak found in Reddit's code when attempting to migrate to Lit SSR -- note the instructions in the comment block:
```
/*
This script re-creates a memory leak when using Lit SSR. Specifically, filling the template cache with a lot of nearly
identical strings due to improper usage of "unsafe". To see this happening, do the following:
1. Open "node_modules/@lit-labs/ssr/lib/render-value.js"
2. Navigate to line 385 (as of the time of this comment)
3. Add "console.log('Adding to cache:', …
```
=> Use a WeakMap for ssr template cache

.changeset/ninety-dogs-dance.md, packages/context/src/lib/context-request-event.ts, packages/context/src/lib/context-root.ts, packages/context/src/lib/controllers/context-consumer.ts, packages/context/src/lib/controllers/context-provider.ts, packages/context/src/test/protocol-types.ts
While profiling some Lit components we noticed that `Event#composedPath()` is in the hot path and that the browser spends a significant amount of time computing it.
For a particular use case (initial render of hundreds of components), ~29% of the time is spent in this function alone. A slight change to the bail out logic reduces this to ~17% (basically don't call it unless absolutely necessary). Keeping manual track of the original source of the event reduces this overhead completely.
Furthermore, this will also slightly reduce memory usage and time spent in garbage collection (for the same use case, Firefox Profiler shows a reduction in memory allocated by this function from ~998KB to ~511KB with the bailout logic and the complete elimination of this allocations with the manual tracking …
=> perf(context): skip expensive computation of Event.composedPath()

.changeset/wild-ways-deliver.md, package-lock.json, package.json, packages/labs/compiler/src/lib/template-transform.ts, packages/lit-html/src/lit-html.ts, packages/tests-typescript/package.json, packages/tests-typescript/src/test-entry.ts
Fixes #4943
Import barrels from trusted-types/lib explicitly for compatibility with modern Node resolution.
I added a minimal test project and cover for a few module/moduleResolution pairs that I think are likely to be used with Lit.
This is related in some ways to
https://github.com/lit/lit/blob/main/CONTRIBUTING.md#typescript.
`trusted-types` was imported as an implicit directory index file (aka barrel), which is not supported with the module resolution algorithm of NodeJS (w/ ESM): https://nodejs.org/api/esm.html#mandatory-file-extensions.
=> fix(lit-html): import `trusted-types/lib` barrel explicitly.

.changeset/soft-ways-wink.md, packages/lit-html/src/directive-helpers.ts, packages/lit-html/src/lit-html.ts, packages/lit-html/src/test/directive-helpers_test.ts, scripts/check-size.js
Also fixes a directive-helpers test that was incorrectly constructing its test case.
I noticed that `removePart()` was almost the same as `ChildPart.$_clear()` with the exception of removing the start node. I also optimized `ChildPart.$_clear()` a little and noticed that the `insertPart()` test was wrong.
=> [lit-html] Remove some redundant code from removePart()

.changeset/rare-dryers-jump.md, packages/labs/ssr-dom-shim/src/index.ts
This improves fidelity, and by making the class a declaration rather than an expression, and explicitly implementing the real interface we're able to better cooperate with JSCompiler's renaming.
=> Implement the full CustomElementRegistry type for the ssr shim.

.changeset/lovely-mangos-deny.md, .changeset/witty-masks-begin.md, packages/internal-scripts/src/release-image.ts, packages/labs/vue-utils/src/wrapper-utils.ts
CI is broken based on the kernel used by GH Actions. We are using unbuntu-latest. [See this CI error](https://github.com/lit/lit/actions/runs/15080547701/job/42397010351?pr=4970). Pretty sure we can trust the content we are running so we should be able to just turn the sandbox off since this just generates an image.
It was also broken because it seems that Vue introduced a new hidden slot with the slotname `__` which seems to hold metadata we were not expecting. [Related CI failure](https://github.com/lit/lit/actions/runs/15080964528/job/42397632767?pr=4991)
| Parent | Children |
| -- | -- |
| (main) | [#4970](https://github.com/lit/lit/pull/4970) |
=> [ci] fix two broken CI issues

.changeset/five-deers-own.md, packages/lit-html/src/private-ssr-support.ts
Adjusted the comparison to use the Function.name property of the `_$resolve` function and the `resolveOverrideFn` in private ssr support to prevent attempted duplicative patching of a directive class.
It appears that after the first patching the directive, like `classMap`, that the conditional check remains `false`. The member/method on the class is still `_$resolve`, but its name is `ssrResolve`. Further processing of checking the Prototype of the directive with `proto.hasOwnProperty(resolveMethodName)` since `ssrResolve` doesn't exist. That path leads to an error being thrown and breaks SSR for that render.
Hopefully addresses Issue #4527
=> fix(lit-html,lit,lit-element): adjust ssr directive patch condition

.clinerules, .cursorrules, .prettierignore, .prettierignore-sync, .roorules, AGENTS.md, CLAUDE.md, package.json
Add a symlinks that link to the copilot instructions for
- [Cursor](https://cursor.com/)
- [Claude Code](https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/overview)
- [Roo Code](https://roocode.com/)
- [Cline](https://cline.bot/)
| Parent | Children |
| -- | -- |
| [#4970](https://github.com/lit/lit/pull/4970) |  |
=> feat(ai): add symlinks to copy AI instructions for more formats

.changeset/metal-bobcats-cross.md, packages/labs/ssr-react/src/node/enable-lit-ssr.ts
Added a guard to check if `React.createElement` was already patched with `litPatchedCreateElement` to prevent adding to the stack multiple calls to `litPatchedCreateElement`. 
Addresses issue #4986
=> fix(@lit-labs/ssr-react,@lit-labs/nextjs): Enable ssr create element patch

.github/workflows/release.yaml
pin to working version of changesets that alleviates this issue https://github.com/changesets/action/issues/501#issuecomment-2902386740
i thought they fixed it with 1.5.3 but turns out it's more broken.
=> [infra] pin changesets action version

.changeset/orange-oranges-hammer.md, packages/labs/gen-wrapper-react/goldens/test-element-a/package.json, packages/labs/gen-wrapper-react/src/index.ts
Earlier #4865 allows @lit/react to accept React 19 as peerdependency. This patch updates the generated package.json to include this version when using @lit-labs/gen-wrapper-react.
=> fix: widen React peer dependency range to include React 19

.changeset/tame-wombats-share.md, packages/labs/tsserver-plugin/src/lib/type-helpers/lit-expression-type.ts, packages/labs/tsserver-plugin/src/test/lib/fake-lit-html-types.ts, packages/labs/tsserver-plugin/src/test/lib/lit-expression-type_test.ts
Introduce the `getLitExpressionType` function to determine the appropriate type for lit-html binding expressions, including sentinel symbols and directive results.
=> Add func to get the effective type of a binding expression

.changeset/selfish-days-learn.md, packages/labs/tsserver-plugin/src/lib/lit-language-service.ts, packages/labs/tsserver-plugin/src/test/lib/lit-language-service_test.ts, packages/labs/tsserver-plugin/test-files/basic-templates/src/custom-element.ts
Starting to work on go to definition for templates. I'm sure there are a bunch more cases we need to consider.
This only works for same package definitions, since we're not analyzing node_modules.
I didn't test this in VS Code, only via the unit test.
I'm not sure when `getDefinitionAndBoundSpan()` is called either.
=> [labs/tsserver-plugin] Add getDefinitionAtPosition()

.changeset/cuddly-boats-slide.md, packages/labs/analyzer/src/lib/lit/template.ts, packages/labs/analyzer/src/test/server/lit/template_test.ts
This is the same as https://github.com/lit/lit/pull/5054, just based on `main`.
=> [labs/analyzer] Adjust attribute source locations in template parser

.changeset/smooth-mice-divide.md, packages/labs/ssr-client/src/lib/hydrate-lit-html.ts
This PR adds a cache for previously computed digest results. This should improve throughput when rendering the same `TemplateResult` multiple times.
=> [labs/ssr-client] Add digest cache

.changeset/sour-heads-study.md, packages/lit-html/src/lit-html.ts
- Create exportable union type `RenderRootNode` to replace `HTMLElement | DocumentFragment` for reusability
- Add type `SVGElement` to render root element union type 
- This resolves type error when passing an `SVGElement` as the `container` argument to `render(...)`, allowing SVG elements to be used as valid render roots
- #2282
=> [lit-html] Include SVGElement in render root union type

.changeset/metal-otters-laugh.md, .vscode/settings.json, packages/labs/ssr-react/src/lib/node/wrap-jsx.ts, packages/labs/ssr/README.md, packages/labs/ssr/package.json, packages/labs/ssr/src/demo/global/app-server.ts, packages/labs/ssr/src/demo/global/server.ts, packages/labs/ssr/src/demo/vm-modules/app-server.ts, packages/labs/ssr/src/lib/element-renderer.ts, packages/labs/ssr/src/lib/lit-element-renderer.ts, packages/labs/ssr/src/lib/render-lit-html.ts, packages/labs/ssr/src/lib/render-result-readable.ts, packages/labs/ssr/src/lib/render-result.ts, packages/labs/ssr/src/lib/render-value.ts, packages/labs/ssr/src/lib/render.ts, packages/labs/ssr/src/lib/util/escape-html.ts, packages/labs/ssr/src/test/integration/server/server.ts, packages/labs/ssr/src/test/integration/tests/basic-ssr.ts, packages/labs/ssr/src/test/lib/render-lit_test.ts, packages/labs/ssr/src/test/lib/render-result-iterator_test.ts, packages/labs/ssr/src/test/lib/render-result-readable_test.ts, packages/labs/ssr/src/test/lib/render-result_test.ts, packages/labs/ssr/src/test/test-files/render-test-module.ts
This gets rid of generators completely from the SSR code in favor of a thunk/trampoline approach where render functions can return thunks that are called to continue rendering. This keeps our ability to render synchronously or asynchronously, while improving perf.
Benchmarks from https://github.com/lit/lit/pull/5103 are merged into a separate branch https://github.com/lit/lit/tree/ssr-thunks-benchmarks and show an **18x** improvement compared to `main`.
This approach works by mapping a template's opcodes array into an array of strings or thunks and performing all render state access and mutation in those thunks. Consumers must iterate the array and when they get a thunk, they have to call it and process the return value. The return value can be undefined, a string, another render result, …
=> [labs/ssr] Convert generators to a trampoline pattern
